### ISSUE TITLE
2.2.16 Worst case seems like N^2

### ISSUE THREAD

**Issue by svezyridis** [reneargento/algorithms-sedgewick-wayne#101]
low is never updated so the code constantly merges from 0-N (first sub-array is pretty big all the time). I tried this and it is about 50 times faster for 1000000 random Doubles
```
 public static void sort(Comparable[] a) {
        int N = a.length;
        aux = new Comparable[N];
        int lo = 0;
        int mid = 0;
        int hi = 0;
        while (true) {
            mid = findSortedSubarray(a, lo);
            if (mid == N - 1) {
                if (lo == 0) //array is sorted
                    break;
                else {
                    lo = 0;
                    continue;
                }
            }
            hi = findSortedSubarray(a, mid + 1);
            merge(a, lo, mid, hi);
            lo = hi == N - 1 ? 0 : hi + 1;
        }
    }
```

**Comment by reneargento** [comment]
Thanks for the contribution.
The `low` variable had to be updated, otherwise this wouldn’t be the real natural merge sort algorithm.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/743d3752361a917040460b7bdc6ae0292b7274db
