### ISSUE TITLE
Possible mistake in 1.4.31 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#104]
There's a possible mistake in these lines, which should move half of items from one stack to another:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter1/section4/Exercise31_DequeWith3Stacks.java#L51
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter1/section4/Exercise31_DequeWith3Stacks.java#L90

However, after each iteration the size of the stack changes, as every iteration the item is popped from the stack, which leads to change to values `headStack.size() / 2` or `tailStack.size() / 2`. Consequently, only 1/3 of all items will be transferred, not half.

**Comment by reneargento** [comment]
Good catch, I fixed that bug on this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/4556c7fd6a64978cdbd74e4cccc89b763d0d8abc

**Comment by dragon-dreamer** [comment]
Thank you!
