### ISSUE TITLE
Solution to 1.4.30 is not amortized O(1)

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#105]
[This solution](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter1/section4/Exercise30_DequeWithStackAndSteque.java) is not amortized `O(1)`. Imagine that you've added many items either using `pushLeft` or `pushRight`, and then you start calling `popLeft` and `popRight` in turns. Every call to `popLeft` and `popRight` will take `O(n)`, because you move all remaining items from steque to stack and backwards.

You also do not use the `enqueue` method of steque, which means your solution does not benefit from using steque, you could just use two stacks.

Here's my solution in C++, which should provide amortized `O(1)` time for all operations called in any order. It's not exception-safe though, and it's impossible to make a generic exception-safe solution to this exercise (C++-only issue). I guess you could convert it to Java, as the algorithm will be essentially the same. It basically moves all items from the stack to the steque, when the stack is empty, and moves half of items from the steque to the stack, when the steque is empty.

```cpp
#include <cassert>
#include <cstddef>
#include <list>
#include <stack>
#include <utility>

//Helper class template steque
template<typename T>
class steque
{
public:
	template<typename Type>
	void push(Type&& val)
	{
		data_.push_back(std::forward<Type>(val));
	}

	template<typename Type>
	void enqueue(Type&& val)
	{
		data_.push_front(std::forward<Type>(val));
	}

	T pop()
	{
		assert(!empty());
		auto result(std::move(data_.back()));
		data_.pop_back();
		return result;
	}

	bool empty() const noexcept
	{
		return data_.empty();
	}

	std::size_t size() const noexcept
	{
		return data_.size();
	}

private:
	std::list<T> data_;
};

template<typename T>
class deque_with_steque_and_stack
{
public:
	template<typename Type>
	void push_back(Type&& val)
	{
		steque_.push(std::forward<Type>(val));
	}

	template<typename Type>
	void push_front(Type&& val)
	{
		stack_.push(std::forward<Type>(val));
	}

	bool empty() const noexcept
	{
		return steque_.empty() && stack_.empty();
	}

	std::size_t size() const noexcept
	{
		return steque_.size() + stack_.size();
	}

	T pop_front()
	{
		assert(!empty());

		if (stack_.empty())
			move_half_of_steque_to_stack();

		auto result(std::move(stack_.top()));
		stack_.pop();
		return result;
	}

	T pop_back()
	{
		assert(!empty());

		if (steque_.empty())
			move_stack_to_steque();

		return steque_.pop();
	}

private:
	void move_half_of_steque_to_stack()
	{
		auto half_steque = steque_.size() / 2;

		for (std::size_t i = 0; i != half_steque; ++i)
			steque_.enqueue(steque_.pop());

		half_steque = steque_.size() - half_steque;
		for (std::size_t i = 0; i != half_steque; ++i)
			stack_.push(steque_.pop());
	}

	void move_stack_to_steque()
	{
		while (!stack_.empty())
		{
			steque_.push(std::move(stack_.top()));
			stack_.pop();
		}
	}

private:
	steque<T> steque_;
	std::stack<T> stack_;
};
```

Test code:
```cpp
#include <iostream>

int main()
{
	deque_with_steque_and_stack<int> testdeque;
	for (size_t i = 0; i != 10; ++i)
		testdeque.push_front(i);

	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_front() << "\n";
	testdeque.push_back(100);
	testdeque.push_front(101);
	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_back() << "\n";
	std::cout << testdeque.pop_front() << "\n";
}
```

**Comment by reneargento** [comment]
You are right, that solution was not amortized O(1) for the pop() operations.
I updated the exercise based on your suggestion with an equivalent algorithm in java: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/3bc178fc6ca834332f9e8b5f14fb970852278851
Thanks for the contribution!

**Comment by dragon-dreamer** [comment]
Thanks for all your work! This repository is really something!
