### ISSUE TITLE
Small mistake in 1.5.14 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#106]
There's a small mistake in these lines:

https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter1/section5/Exercise14_WeightedQUHeight.java#L76
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter1/section5/Exercise14_WeightedQUHeight.java#L77

They should reference `ranks[leader2]`, not `ranks[leader1]`, because in the previous code fragment `ranks[leader2]` is incremented:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter1/section5/Exercise14_WeightedQUHeight.java#L74

**Comment by reneargento** [comment]
Fixed here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/2c81d847092dc40bc4dba5bbc334314bd4dcbf4d
Thanks!

**Comment by dragon-dreamer** [comment]
Awesome, thanks!
