### ISSUE TITLE
Over-complicated solution for 2.3.15

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#109]
It seems that the solution to 2.3.15 is over-complicated. There are basically two rather simple ways to solve this:
1. https://www.geeksforgeeks.org/nuts-bolts-problem-lock-key-problem/, which I guess is expected for the exercise and takes `O(n log n)`.
2. https://www.geeksforgeeks.org/nuts-bolts-problem-lock-key-problem-set-2-hashmap/, which takes `O(n)`.

**Comment by reneargento** [comment]
Updated it with the correct method: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/7d3169e6411e89cabe2cf85a0b82e7bd605f28d8
Thanks!
