### ISSUE TITLE
Redundant checks in 2.3.20 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#110]
Seems that some checks are redundant. For example:

https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter2/section3/Exercise20_NonrecursiveQuicksort.java#L94

Here the `leftQuickSortRange.low < leftQuickSortRange.high` check is redundant.

Directly from the code:
1. `leftSubArraySize > 1` (first part of the condition);
2. `leftSubArraySize = partition - currentQuickSortRange.low`;
3. `leftQuickSortRange.low = currentQuickSortRange.low`;
4. `leftQuickSortRange.high = partition - 1`.

From (2), (3) follows:
5. `leftQuickSortRange.low = partition - leftSubArraySize`.

From (5) and (1):
6. `leftQuickSortRange.low < partition - 1`.

From (6) and (4):
7. `leftQuickSortRange.low < leftQuickSortRange.high`

So the second check is redundant and implied by the first one.

The same is true for the following three conditions:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter2/section3/Exercise20_NonrecursiveQuicksort.java#L98
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter2/section3/Exercise20_NonrecursiveQuicksort.java#L102
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/fe4c6dd5a2d11567f6d54cb6e98f4a1a5c3983e5/src/chapter2/section3/Exercise20_NonrecursiveQuicksort.java#L106

**Comment by reneargento** [comment]
It makes sense that the `leftQuickSortRange.low < leftQuickSortRange.high` checks are redundant.
But are the `rightQuickSortRange.low < rightQuickSortRange.high` checks also redundant?

Directly from the code:

1. `rightSubArraySize > 1` (first part of the condition)
2. `rightSubArraySize = currentQuickSortRange.high - partition + 2`
3. `rightQuickSortRange.low = partition + 1`
4. `rightQuickSortRange.high = currentQuickSortRange.high `

From (2) follows:
5. `currentQuickSortRange.high = rightSubArraySize + partition - 2`

From (4) and (5)
6. `rightQuickSortRange.high = rightSubArraySize + partition - 2`

From (6) and (1)
7. `rightQuickSortRange.high > partition - 1`

And from (3) we know that 
`rightQuickSortRange.low = partition + 1`, which is different from `partition - 1` (from 7).

**Comment by dragon-dreamer** [comment]
It seems that the check is still redundant, because there's another mistake in this solution I've just noticed:

```java
QuickSortRange leftQuickSortRange = new QuickSortRange(currentQuickSortRange.low, partition - 1);
QuickSortRange rightQuickSortRange = new QuickSortRange(partition + 1, currentQuickSortRange.high);

//Size = right - left + 1
int leftSubArraySize = partition - currentQuickSortRange.low;
int rightSubArraySize = currentQuickSortRange.high - partition + 2;
```

For `leftSubArraySize` `Size = right - left + 1 = partition - 1 - currentQuickSortRange.low + 1 = partition - currentQuickSortRange.low`, which is correct.

For `rightSubArraySize` `Size = right - left + 1 = currentQuickSortRange.high - (partition + 1) + 1 = currentQuickSortRange.high - partition - 1 + 1 = currentQuickSortRange.high - partition`, while the code says `int rightSubArraySize = currentQuickSortRange.high - partition + 2`, which is not correct. If we take `int rightSubArraySize = currentQuickSortRange.high - partition`, then the second check becomes redundant.

**Comment by reneargento** [comment]
Nice catch, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/8df2262cf0164cbed6c00b98fe80b27a04af54b7

**Comment by dragon-dreamer** [comment]
Thanks! However, there's still a mistake (which I mentioned in my previous post) in rightSubArraySize calculation:

https://github.com/reneargento/algorithms-sedgewick-wayne/blob/8df2262cf0164cbed6c00b98fe80b27a04af54b7/src/chapter2/section3/Exercise20_NonrecursiveQuicksort.java#L90

`+ 2` is not needed here.

**Comment by reneargento** [comment]
Ops, I removed the redundant checks but forgot to update the array size calculation too.
It is fixed now on the latest commit.
