### ISSUE TITLE
Proof of 2.3.21 seems to be wrong

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#111]
Proposition M, which is asked to be proven, is the following: 

> No compare-based sorting algorithm can guarantee to sort N items
with fewer than NH - N compares, where H is the Shannon entropy, defined from
the frequencies of key values.

While the proof [provided in this repository](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter2/section3/Exercise21_LowerBoundForSortingWithEqualKeys.txt) results in the following statement:

> the number of compares used by any algorithm must be at least N lg N / f1! f2! ... fk! when there are k different values.

This statement does not prove Proposition M, as it does not say anything about Shannon entropy. And, I think, the formula `N lg N / f1! f2! ... fk!` is itself incorrect.

Here's what I believe is more correct approximation of the term

<img src="https://render.githubusercontent.com/render/math?math=\Large%20lg(\dfrac{N!}{f_1!\cdot%20f_2!\cdot%20...\cdot%20f_k!})">

Using logarithm properties this is the same as:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20lg(N!)%20-%20lg(f_1!\cdot%20f_2!\cdot%20...\cdot%20f_k!)">

<img src="https://render.githubusercontent.com/render/math?math=\Large%20=%20lg(N!)%20-%20(lg(f_1!)%20%2B%20lg(f_2!)%20%2B%20...%20%2B%20lg(f_k!))">

As <img src="https://render.githubusercontent.com/render/math?math=f_i%20=%20p_i\cdot%20N">, previous formula expands like this:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20lg(N!) - (lg((p_1\cdot N)!) %2B lg((p_2\cdot N)!) %2B ... %2B lg((p_k\cdot N)!))">

Then, using Stirling approximation:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NlgN%20-%20(N\cdot%20p_1lg(p_1\cdot%20N)%20%2B%20...%20%2B%20N\cdot%20p_klg(p_k\cdot%20N))">

Move `N` behind the brackets:

<img src="https://render.githubusercontent.com/render/math?math=\Large NlgN - N\cdot (p_1lg(p_1\cdot N) %2B ... %2B p_klg(p_k\cdot N))">

Expand logarithms using logarithm properties:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NlgN%20-%20N\cdot%20(p_1lgp_1%20%2B%20p_1lgN%20%2B%20...%20%2B%20p_klgp_k%20%2B%20p_klgN)">

Re-group terms inside brackets:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NlgN%20-%20N\cdot%20(p_1lgp_1%20%2B%20...%20%2B%20p_klgp_k)%20-%20N\cdot%20(p_1lgN%20%2B%20...%20%2B%20p_klgN)">

Now, the first term inside brackets is Shannon entropy <img src="https://render.githubusercontent.com/render/math?math=H%20=%20-(p_1lgp_1%20%2B%20...%20%2B%20p_klgp_k)">. Moreover, we can move `NlgN` term behind the brackets for the second term:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NlgN%20%2B%20NH%20-%20NlgN\cdot%20(p_1%20%2B%20...%20%2B%20p_k)">

Now <img src="https://render.githubusercontent.com/render/math?math=p_1%20%2B%20p_2%20%2B%20...%20%2B%20p_k%20=%201">, because this is the sum of all probabilities of each element in our range. Using this fact, we now get the following:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NlgN%20%2B%20NH%20-%20NlgN">

or simply

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NH">

Unfortunately, I still can not understand where the `- N` term comes from in the original `Proposition M`. I was not able to find any solutions to this, too. Maybe you could investigate more?

**Comment by dragon-dreamer** [comment]
Probably, however unlikely, there's a mistake in the book... If we consider all distinct elements in the range and then calculate `NH` for them:

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NH%20=%20-N\cdot%20(N\cdot%20p\cdot%20lgp)">

where `p = 1/N` (as all elements are distinct and have therefore equal probabilities to be in the range):

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NH%20=%20-N\cdot%20(N\cdot%20\dfrac{1}{N}\cdot%20lg\dfrac{1}{N})">

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NH%20=%20-N\cdot%20lg\dfrac{1}{N}">

<img src="https://render.githubusercontent.com/render/math?math=\Large%20NH%20=%20N\cdot%20lg{N}">

This is the same amount of compares as we have already calculated for compare-based sorting in `Proposition I`. There's no need for the term `- N` here.

As shown on [this Wiki page on Stirling's approximation](https://en.wikipedia.org/wiki/Stirling%27s_approximation), there's indeed `- N` term in it, but Sedgewick doesn't consider it in his book. I even tried to simplify the original formula <img src="https://render.githubusercontent.com/render/math?math=lg(\dfrac{N!}{f_1!\cdot%20f_2!\cdot%20...\cdot%20f_k!})"> considering this term when applying Stirling's approximation to logarithms, but still got the same result, as these `- N` terms just cancel each other in the end.

**Comment by reneargento** [comment]
Looks good!
I also tried to consider the extra -N term when applying Stirling's approximation and got to the same result. It looks like this term shouldn’t be on Proposition M.

I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/3bdb449a0f405a860a3a01dd18eb965bd1c7e1a6
I adapted it for a ternary tree (using logs on base 3) because we also have the case of equal keys in the comparisons, but as the final answer is only based on the total number of nodes and on Shannon entropy I think it doesn't make a difference.
Let me know if you think it covers everything.

**Comment by dragon-dreamer** [comment]
Looks good to me, thank you!

**Comment by nihil-admirari** [comment]
Sedgewick's own proof can be found at https://sedgewick.io/wp-content/themes/sedgewick/talks/2002QuicksortIsOptimal.pdf, slide 11. He uses $n! \\sim n\\,\\log\\,n - n$ in the numerator, but doesn't use $- f_i$ terms in the denominator. The rationale for that is not stated. Probably he wanted to make the numerator as small as possible while making the denominator as large as possible to have some wiggle room.

**Comment by reneargento** [comment]
Thanks for the reference to Sedgewick’s proof, I added it to the exercise: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/49e39494a947f48643548ff71c8eab46285178a9
