### ISSUE TITLE
Alternative binary search way for 2.4.31

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#114]
There's another way of performing binary search for [2.4.31](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter2/section4/Exercise31_FastInsert.java) exercise, which doesn't involve floating point arithmetic and index array creation. I would like to share this approach:

```java
private int log2(int value) {
	int result = 0;
	while ((value >>= 1) != 0) {
		++result;
	}
	return result;
}

private int binarySearchToGetTargetAncestor(int index) {
	int from = 0;
	int indexLevel = log2(index);
	int to = indexLevel;
	while (to != from) {
		int middle = from + (to - from) / 2;

		++numberOfCompares;
		if (ArrayUtil.more(priorityQueue[index / (1 << (indexLevel - middle))], priorityQueue[index])) {
			to = middle;
		} else {
			from = middle + 1;
		}
	}
	
	return index / (1 << (indexLevel - from));
}
```

Here we operate directly on levels of the tree.

**Comment by reneargento** [comment]
Nice approach, exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/154d9bff74eba372b4d251b1698bd185610d0744
Thanks!
