### ISSUE TITLE
More appropriate solution for 2.5.3

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#117]
In my opinion, Sedgewick is asking to fix a flawed `Comparable` implementation without changing the original logic. We need to keep the comparison with epsilon.

Here's a more correct way to compare double values with epsilon accuracy: https://gist.github.com/mitchwongho/8423e6cc8b47a4bbfa22

**Comment by reneargento** [comment]
How does the comparison with epsilon accuracy fixes the Comparable interface violation?
I updated the exercise with an example to highlight the issue: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/cb5c57244a7b64a0d03966241c568a4b9b6236c5
The comparison with epsilon seems to decrease the issue in the problem, but I'm not sure if there is any way to avoid it completely without using direct comparison (even if we consider that floating points cannot be represented with exact precision).

**Comment by dragon-dreamer** [comment]
The code I've linked (https://gist.github.com/mitchwongho/8423e6cc8b47a4bbfa22) has a correct `Comparable` implementation and at the same time keeps the original logic of comparing double values with epsilon **for equality**, not directly. It's OK to compare doubles directly using `>` or `<` operator **after** they've been compared for equality with epsilon.

I think, the idea of Sedgewick was to compare doubles for equality with epsilon, but I may be wrong, of course. What do you think?

**Comment by reneargento** [comment]
That could be the idea, the question is not very clear.
Maybe I'm missing something, but in practice, isn't the "flawed" implementation mentioned in the exercise going to have the same results as the code you have linked if we set `EPSILON` to `0.005`?

**Comment by dragon-dreamer** [comment]
I've thought a bit more about this question and yes, you're right! Both implementations will behave the same way, they are both "flawed". And the flaw is the following:

> let's assume a is 1.003, b is 1.006, c is 1.009, so we can get a == b; b==c; a < c at the same time, which is wrong.

Your solution is absolutely correct, I'm closing this issue.

**Comment by dragon-dreamer** [comment]
I'm sorry for reopening this issue, but I've analyzed the question a bit more and have another suggestion. It seems a generally bad idea to represent account balances as `double` because of the floating point precision errors.

Consider the following code:
```java
class Balance implements Comparable<Balance> {
    private double amount;
    public Balance(double amount) {
        this.amount = amount;
    }
    
    public void add(double amount) {
        this.amount += amount;
    }
    
    public double getAmount() {
        return amount;
    }
    
    public int compareTo(Balance that) {
        if (this.amount < that.amount) return -1;
        if (this.amount > that.amount) return +1;
        return 0;
    }
}

public class Main {
	public static void main(String[] args) {
	    Balance b1 = new Balance(0);
	    Balance b2 = new Balance(1);
	    
	    for (int i = 0; i != 10; ++i) {
	        b1.add(0.1);
	    }
	    
	    System.out.println(b1.compareTo(b2));
	    System.out.println(b1.getAmount());
	    System.out.println(b2.getAmount());
	}
}
```

For me, it outputs the following:
```
-1                                                                                                                                                
0.9999999999999999                                                                                                                                
1.0
```

However, the balances are expected to be the same: the first one was initialized to `1.0`, the second is calculated as `0.1 * 10`. But because of the floating point precision errors, we actually get different balances!

So, in my opinion, it's a good idea to represent account balances as integer or `BigInteger` types, because they don't suffer from any precision errors.

See also: https://stackoverflow.com/questions/61872/use-float-or-decimal-for-accounting-application-dollar-amount

**Comment by reneargento** [comment]
So besides comparing the values directly we can't use double due to its lack of precision.
It makes sense. I tested your code with BigDecimal and it seems to work.
I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/922344fbd7ffa05f40fda95105703e7c422c0f01
Let me know if it seems correct.

**Comment by dragon-dreamer** [comment]
Looks good for me, but I'm not sure if `BigDecimal` is a proper type to use. There's a small remark on this type:
> care should be exercised if BigDecimal objects are used as keys in a SortedMap or elements in a SortedSet since BigDecimal's natural ordering is inconsistent with equals

Here's some more information: https://stackoverflow.com/questions/19818537/why-is-bigdecimal-natural-ordering-inconsistent-with-equals

Probably that's worth mentioning in the solution, too (or probably it's worth to override the `equals` method for the `Balance` class).

Or probably we should ignore `equals`, because the original exercise is about `compareTo` only. I will close the issue, because for me the original question from the book is answered.

**Comment by reneargento** [comment]
That is a good point and in that case it also violates the Comparable interface. 
So even though `BigDecimal` would make the method work, it still does not seem the best answer.
I couldn't get your example code to work with `BigInteger` though. How would you do it?

**Comment by dragon-dreamer** [comment]
I guess, `BigDecimal` is fine. The following code:
```java
public static void main(String[] args) {
	System.out.println((new BigDecimal("1.0").compareTo(new BigDecimal("1.00"))));
	System.out.println((new BigDecimal("1.0").equals(new BigDecimal("1.00"))));
}
```
prints the following:
```
0
false
```

This means, that `compareTo` works as expected. We just need to make `equals` do the same thing for our `Balance` class:

```java
public class Balance implements Comparable<Balance> {
    ...
    private BigDecimal amount;
    public int compareTo(Balance that) {
        return this.amount.compareTo(that.amount);
    }
    public boolean equals(Balance that) {
        return this.amount.compareTo(that.amount) == 0;
    }
    ...
}
```
What do you think?

P.S. As for the `BigInteger` class, we could use it in case we make the lowest digit to represent the smallest fraction of the currency we're working with. For example, `BigInteger.valueOf(123)` could represent 1$ and 23 cents.

**Comment by reneargento** [comment]
Overriding the equals method looks good.
This should be enough to be a correct implementation of the Comparable contract.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/50088aafa5d355389fdd22acc2c32c20cf908b34
Thanks!
