### ISSUE TITLE
Solution for 2.5.27 is for another task?

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#118]
Probably I'm missing something, but in my book there's the following task under the **2.5.27** number:

> **2.5.27** _Sorting parallel arrays._ When sorting parallel arrays, it is useful to have a version
> of a sorting routine that returns a permutation, say index[], of the indices in sorted
> order. Add a method indirectSort() to Insertion that takes an array of Comparable
> objects a[] as argument, but instead of rearranging the entries of a[] returns an integer
> array index[] so that a[index[0]] through a[index[N-1]] are the items in ascending
> order.

However, there's a solution to a completely different task [Exercise27_OneDimensionalIntervals.java](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter2/section5/Exercise27_OneDimensionalIntervals.java) in the repository.

**Comment by dragon-dreamer** [comment]
Here's a solution for my 2.5.27 task:

```java
class Insertion {
    public static <T extends Comparable<T>> int[] indirectSort(T[] arr) {
        int[] result = new int[arr.length];
        for (int i = 0; i != arr.length; ++i) {
            result[i] = i;
        }
        
        for (int i = 1; i < arr.length; ++i) {
            for (int j = i; j != 0 && less(arr[result[j]], arr[result[j - 1]]); --j) {
                exch(result, j, j - 1);
            }
        }
        
        return result;
    }
    
    private static <T extends Comparable<T>> boolean less(T v, T w) {
        return v.compareTo(w) < 0;
    }
    
    private static void exch(int[] a, int i, int j) {
        int t = a[i]; a[i] = a[j]; a[j] = t;
    }
}

public class Main {
	public static void main(String[] args) {
	    Integer[] unsorted = { 1, 7, 0, 4, 2, 3 };
	    
	    int[] sortedIndices = Insertion.indirectSort(unsorted);
	    
	    System.out.println("Sorted indices: ");
	    for (int index : sortedIndices) {
	        System.out.print(index + " ");
	    }
	    
	    System.out.println();
	    System.out.println("Sorted array: ");
	    for (int index : sortedIndices) {
	        System.out.print(unsorted[index] + " ");
	    }
	}
}
```

**Comment by reneargento** [comment]
Seems to be the same issue mentioned here: https://github.com/reneargento/algorithms-sedgewick-wayne/issues/89
You may have a different printing of the book. You can see which printing you have on one of the first pages of the book (and also the year that it was published).
Some exercises (but not many) have changed on later printings.
The exercises in this repository are all based on the seventh printing (published September 2015)

**Comment by dragon-dreamer** [comment]
Thank you, I was not attentive enough, because your readme.md actually tells about it.
