### ISSUE TITLE
Alternative calculations for 3.1.14 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#119]
I guess, it would be better to use an unordered linked list symbol table implementation for 10<sup>6</sup> `put` and 10<sup>3</sup> `get` operations, while the [answer in this repository](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section1/Exercise14.txt) prefers a binary search symbol table.

Sedgewick gives us the following estimates:
> sequential search: search is `N` operations, insert is `N` operations **worst-case**
> binary search: search is `lgN` operations, insert is `2N` operations **worst-case**

So in the worst case, we'll get 10<sup>6</sup> + 10<sup>3</sup> ~ 10<sup>6</sup> operations for the sequential search symbol table and 2 * 10<sup>6</sup> + lg(10<sup>3</sup>) ~ 2 * 10<sup>6</sup> operations for the binary search symbol table. Obviously, the sequential search symbol table is preferred in this case.

Average case is similar for both table implementations, because there are much more `put` than `get` operations, so in the average case we get the same performance for both implementations.

This means, that we should choose the sequential search symbol table, because it performs better in the worst-case (and just the same in the average case).

**Comment by reneargento** [comment]
Makes sense, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/edc037418eb2ae6319a749e264022087f8121c99
Thanks!
