### ISSUE TITLE
3.1.27 solution does not take S time complexity into consideration

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#120]
For the case, when the symbol table is built from ordered items, [the solution](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section1/Exercise27_SmallTables.txt) tells the following:

> N inserts will have an order of growth of O(N lg N).
> Therefore, the order of growth of S should be O(N lg N), making the cost of building the table the same as the cost of all searches.

However, the complexity of the search operation `S` is itself `lg N`, which means, that the order of growth of `S` should be at least `N` to compensate the cost of building the table.

The same is true for the part when we build a table with random values (which takes `O(N`<sup>`2`</sup>`)`). The complexity of `S` is still `lg N`, which means that to compensate the cost of building the table, we must perform at least `O(N`<sup>`2`</sup>` / lg N)` `S` operations.

**Comment by reneargento** [comment]
Makes sense, exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/8a18a15fbe621f147f0852cb4657c08bee220128
Thanks!
