### ISSUE TITLE
Several correct algorithms for exercise 3.2.5

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#121]
The 3.2.5 exercise asks to build an optimal BST knowing the probabilities of searching of each element.

The [solution in the repository](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section2/Exercise5.txt) suggests to insert the keys in decreasing order of likely frequency of access. This may be not the best solution given our BST is unbalanced. Consider the following keys and their search frequencies:
```
5 - will be searched 10000 times, most popular
4 - will be searched 5000 times
3 - will be searched 3000 times
2 - 2000 times
1 - 1000 times
6 - 500 times
7 - 100 times
```

Inserting these keys in decreasing order of likely frequency of access will produce the following tree:
```
            5
         4    6
      3         7
   2
1
```

This is not optimal. For example, it will be faster to find the key `6` compared to the key `1`, but the search frequency of `6` is lower than of `1`.

There are several algorithms for this task: https://en.wikipedia.org/wiki/Optimal_binary_search_tree. Probably, it's worth mentioning this page in the solution.

**Comment by reneargento** [comment]
Interesting, I didn't know this was known as the optimal BST problem. 
Exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/1677025c4b91eebcbd5ae577bc4621dd8c6b1bdf
Thanks!
