### ISSUE TITLE
Some fixes for exercise 3.2.24 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#122]
There's the following statement in the proof of 3.2.24:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/154d9bff74eba372b4d251b1698bd185610d0744/src/chapter3/section2/Exercise24.txt#L6

I guess, there's a small mistake here. Only the last insert will make `~ lg N` compares for a balanced tree. All previous inserts will be faster.

So let's build a tree by inserting one element at a time. The first element will take `lg 1` compares to insert, the second will take `lg 2` compares, ..., N-th element will take `lg N` compares.

Then we'll add all these values:
`lg 1 + lg 2 + ... + lg N`
This is directly equal to (using logarithm properties):
`lg (1 * 2 * ... * N) = lg (N!)`
Finally, using Stirling's approximation, this is `~ N lg N`.

**Comment by reneargento** [comment]
Makes sense, exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/75d6902cb8f7dc9d1517042ea76a1fbff3b3d212
Thanks!
