### ISSUE TITLE
Several exercises in part 3.2 differ from the book

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#123]
I'm reading the forth edition of the book, and there are several exercises in part 3.2 which differ from their solutions in this repository:

1. **3.2.29** - "Tree traversal constant extra memory" in the repo, but "Binary tree check" in the book:
> 3.2.29 Binary tree check. Write a recursive method isBinaryTree() that takes a Node
> as argument and returns true if the subtree count field N is consistent in the data structure
> rooted at that node, false otherwise. Note : This check also ensures that the data
> structure has no cycles and is therefore a binary tree (!).
2. **3.2.30** - "BST reconstruction" in the repo, but "Order check" in the  book:
> 3.2.30 Order check. Write a recursive method isOrdered() that takes a Node and two
> keys min and max as arguments and returns true if all the keys in the tree are between
> min and max; min and max are indeed the smallest and largest keys in the tree, respectively;
> and the BST ordering property holds for all keys in the tree; false otherwise.
3. **3.2.31** - "Certification" in the  repo, but "Equal key check" in the book:
> 3.2.31 Equal key check. Write a method hasNoDuplicates() that takes a Node as argument
> and returns true if there are no equal keys in the binary tree rooted at the argument
> node, false otherwise. Assume that the test of the previous exercise has passed.
4. **3.2.32** - "Subtree count check" in the  repo, but "Certification" in the  book:
> 3.2.32 Certification. Write a method isBST() that takes a Node as argument and returns
> true if the argument node is the root of a binary search tree, false otherwise.
> Hint : This task is also more difficult than it might seem, because the order in which you
> call the methods in the previous three exercises is important.

**Comment by dragon-dreamer** [comment]
Moreover, for the "_Certification_" exercise Sedgewick suggests the following solution, which differs from the one in the repository (because the solution in the book relies on three previous exercises):

```java
private boolean isBST()
{
    if (!isBinaryTree(root)) return false;
    if (!isOrdered(root, min(), max())) return false;
    if (!hasNoDuplicates(root)) return false;
}
````

**Comment by reneargento** [comment]
Looks like the same case as I mentioned on https://github.com/reneargento/algorithms-sedgewick-wayne/issues/118

**Comment by dragon-dreamer** [comment]
Yes, I'm closing this issue.
