### ISSUE TITLE
(1.4.10) line 65 modification

### ISSUE THREAD

**Issue by emergencyd** [reneargento/algorithms-sedgewick-wayne#124]
I think it might be better to use:
high = middle - 1;

**Comment by reneargento** [comment]
You are right, in that case we know that `middle - 1` is a possible solution, so we can update `high` to that index. 
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/76f3b48e9bf61fd1adc072fb8ecb34ed53795afc
Thanks!
