### ISSUE TITLE
Addition for 3.4.7 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#125]
There's the following question in the book:
> 3.4.7 Consider the idea of implementing modular hashing for integer keys with the
> code (a * k) % M , where a is an arbitrary fixed prime. Does this change mix up the
> bits sufficiently well that you can use nonprime M?

The answer in the repository is:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/50088aafa5d355389fdd22acc2c32c20cf908b34/src/chapter3/section4/Exercise7.txt#L3

I would like to add, that `M` **must be coprime** with `a`, otherwise the distribution will be poor. Here's the proof:

1. `(a * k) % M = hash`
2. This means, that`a * k = M * q + hash` or `hash = a * k - M * q`, where `q` is any natural number.
3. Now let's consider that `M` and `a` are not coprime. This means, that `M = t * a`, where t is any non-zero natural number. `hash = a * k - M * q` expands to `hash = a * k - a * t * q = a * (k - t * q)`. This means, that all hash values will be divisible by `a`, which greatly reduces the distribution of keys. If `a = 37` and `M = 37 * t`, then all hash values will be only `0, 37, 74, 111, ...`.

**Comment by reneargento** [comment]
Good observation.
Exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/986d141ec777458b29d5bf614da14bcb36264b7a
Thanks!
