### ISSUE TITLE
Double hashing (3.4.28) implementation question

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#128]
The wording of the 3.4.28 exercise in my book is the following:
> **3.4.28 Double hashing.** Modify LinearProbingHashST to use a second hash function
> to define the probe sequence. Specifically, replace (i + 1) % M (both occurrences) by
> (i + k) % M where k is a nonzero key-dependent integer that is relatively prime to M.
> _Note_: **You may meet the last condition by assuming that M is prime.** Give a trace of the
> process of inserting the keys E A S Y Q U T I O N in that order into an initially empty
> table of size M =11, using the hash functions described in the previous exercise. Give
> the average number of probes for random search hit and search miss in this table.

The implementation [in the repository](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section4/Exercise28_DoubleHashing.java) does not take the statement "_You may meet the last condition by assuming that M is prime._" into consideration.

Initially the size of the hash table is set to 7, which is indeed prime:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/f27e7c7b4aa44e136a858d76a43d18e5251e2329/src/chapter3/section4/Exercise28_DoubleHashing.java#L250

However, when resizing, the size is either doubled or divided by 2, causing the new size of the hash table loose its primality:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/f27e7c7b4aa44e136a858d76a43d18e5251e2329/src/chapter3/section4/Exercise28_DoubleHashing.java#L151
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/f27e7c7b4aa44e136a858d76a43d18e5251e2329/src/chapter3/section4/Exercise28_DoubleHashing.java#L194

Moreover, the `secondaryHash` implementation does not match the exercise requirement. It firstly calculates `(i + hash) % size` and then tests if the resulting value is relatively prime to `size`, while the exercise requires to use `k` (and not the final hash value) which is relatively prime to `size` (and `size` has still to be prime).

Probably, it's worth resizing the hash table to the next or the previous prime number taken from the  `PRIMES` array instead of size doubling. This will greatly simplify the `secondaryHash` implementation. Any number from `1` to `size - 1` or from `size + 1` to `2 * size - 1` will be relatively prime to `size`, because `size` will always be prime. There will be no need to calculate factors to size, it will only be necessary to choose `k` from `1` to `size - 1` or from `size + 1` to `2 * size - 1` depending on the key.

**Comment by reneargento** [comment]
The idea of resizing the hash table based on the `PRIMES` array looks good.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/0a7e9ace3b020f46f9553eafe9520924c5a902e8
Thanks!

**Comment by dragon-dreamer** [comment]
Thanks! I would also advise to change the following lines (there are two of them):
```java
hash2 = hash2 != 0 ? hash2 : 1;
```
To something like this:
```java
hash2 = hash2 != 0 ? hash2 : size + 1;
```

The current behavior maps keys `[0, size)` to hashes `[1, size)`. This means that `size` values are mapped to `size - 1` distinct hash values, which slightly distorts the uniform distribution.

If you instead change `0` hash value to `size + 1` this will still keep all secondary hashes relatively prime to `size`. At the same time, `size` values will be mapped to `size` distinct hash values.

What do you think?

**Comment by reneargento** [comment]
Nice catch, updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d194e47e901094fd3f6e2070b3afcf0ce328cdc2
Thanks!
