### ISSUE TITLE
(1.4.20) some arrays might not be bitonic

### ISSUE THREAD

**Issue by emergencyd** [reneargento/algorithms-sedgewick-wayne#129]
int[] array4 = {2, 4, 8, 16, 32};
int[] array5 = {2, 1};
int[] array6 = {9};
they are not "increasing"  followed by decreasing

**Comment by reneargento** [comment]
A sequence of values can be bitonic with the increasing or decreasing parts empty.
Check the description on the section `Bitonic Sequence` here for example: https://www.geeksforgeeks.org/bitonic-sort/
