### ISSUE TITLE
2.1.13 Deck Sort Can be Implemented in Only One Shell Sort

### ISSUE THREAD

**Issue by VBhojawala** [reneargento/algorithms-sedgewick-wayne#13]
I think real question here is how you implement Comparable Interface rather than sorting.

enum Suit{
	SPADES, HEARTS, CLUBS, DIAMONDS;
}
class Card implements Comparable<Card>{
	int rank;
	Suit suit;
	
	public Card(int rank,Suit suit){
		this.rank=rank;
		this.suit=suit;
	}

	@Override
	public int compareTo(Card arg0) {
		Integer p =this.rank*(this.suit.ordinal()*13);
		Integer q =arg0.rank*(arg0.suit.ordinal()*13);
		

		return p.compareTo(q);
	}
	
	@Override
	public String toString() {
		return  this.suit.name()+" "+this.rank;
	}
	
}
public class DeckSort {
	
	
	public static void main(String[] args) {
		
		Card spadeQ=new Card(12, Suit.SPADES);
		Card heart5=new Card(5, Suit.HEARTS);
		Card diamond10=new Card(10, Suit.DIAMONDS);
		Card clubK=new Card(13, Suit.CLUBS);
		Card diamond9=new Card(9, Suit.DIAMONDS);
		
		
		ArrayList<Card> deck=new ArrayList<>();
		deck.add(clubK);deck.add(diamond9);deck.add(spadeQ);deck.add(heart5);deck.add(diamond10);
		
		//Use Shell Sort Instead
		Collections.sort(deck);
		
		for(Card c:deck) {
			System.out.println(c);
		}
		
	}

}

**Comment by reneargento** [comment]
I'm not sure that is what the question asks. The question is not very clear and if we read the beginning of the question it may seem that the question is related to implementing a Comparable method, but this part of the question makes it seem that it is asking for the description of a sorting method:

"... with the restriction that the cards must be laid out face down in a row, and the only allowed operations are to check the values of two cards and to exchange two cards (keeping them face down)."

Also, take a look at question 2.1.23:
"Deck sort. Ask a few friends to sort a deck of cards (see Exercise 2.1.13). Observe
them carefully and write down the method(s) that they use."

This question further seems to point that exercise 2.1.13 is just asking for a sort description.

**Comment by reneargento** [comment]
I'm closing this issue as it has been inactive for more than one year and it is apparently solved.
