### ISSUE TITLE
(1.4.24) the cost for findFloorIn2LgF might not be ~2lgF

### ISSUE THREAD

**Issue by emergencyd** [reneargento/algorithms-sedgewick-wayne#130]
please refer to https://stackoverflow.com/questions/17404642/throwing-eggs-from-a-building
    below is my code for this question :)

	public static int floor2(int[] a) {
            if (a[0] == 1) return 0;
		int loc = 1;
		while (loc < a.length) {
			if (a[loc] == 1) break;
			else loc *= 2;
		}
		
		int lo = loc / 2 + 1;
		int hi = Math.min(a.length - 1, loc);
		int mid;
		while (lo <= hi) {
			mid = lo + (hi - lo) / 2;
			if (a[mid] == 1) {
				if (a[mid - 1] == 0) return mid;
				else {hi = mid - 1;}
			}
			else {
				lo = mid + 1;
			}
		}
		return -1; // should not happen
	}

**Comment by reneargento** [comment]
There was a bug on the recursion that didn't make the solution use ~2lgF throws.
I updated and simplified the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/28c804c77e9798e496cd2803e1e2c7c253280385
Thanks!
