### ISSUE TITLE
Optimization for 3.5.16

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#131]
Currently, [3.5.16 solution](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section5/Exercise16.java) `sum` method takes `O(N + M + K)`, where `N` and `M` are sizes of `SparseVectorSum` hash tables, and `K` is max key of both of these vectors. Imagine having two vectors with just one key `10^8`: this line will take `10^8` iterations to add these two vectors:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/21e44f4c37a2ac2321f9c973516b03463bab4a4c/src/chapter3/section5/Exercise16.java#L53

It's possible to simplify and optimize this method, so if there's one key in these vectors, then only a single iteration is needed to add them:
```java
public SparseVectorSum sum(SparseVectorSum sparseVectorToSum) {
	for (Integer key : sparseVectorToSum.hashTable.keys()) {
		if (!hashTable.contains(key)) {
			put(key, sparseVectorToSum.get(key));
		} else {
			double sum = get(key) + sparseVectorToSum.get(key);
			if (sum != 0) {
				put(key, sum);
			} else {
				delete(key);
			}
		}
	}
	
	return this;
}
```

The complexity of this approach is `O(M)` (where `M` is the size of `sparseVectorToSum`).

**Comment by dragon-dreamer** [comment]
Also maybe it's a good idea not to compare `double` directly to `0` because of possible precision errors. Sedgewick gives a hint to introduce comparison with epsilon (`if sum < epsilon` instead of `if sum == 0`):
> Note: You need delete() (**and special attention to precision**) to handle the
case where an entry becomes 0.

**Comment by reneargento** [comment]
Good improvement, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/9019dadc9c9125c64fbc9c510c012ae1e00f3777
Thanks!

**Comment by dragon-dreamer** [comment]
Great, thank you!
