### ISSUE TITLE
No need to inherit RedBlackBST in 3.5.24

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#133]
There's no need to inherit `RedBlackBST` and implement `RedBlackBSTGetNodeOrPrevious` in [3.5.24](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section5/Exercise24_NonOverlappingIntervalSearch.java). The `get` method (which is overridden) is identical to the already implemented `floor` method. So it's possible to use `RedBlackBST` directly instead of `RedBlackBSTGetNodeOrPrevious` and call `floor` instead of `get`.

**Comment by reneargento** [comment]
Exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/dc036d5ce9d85b826541c92d3c2fb4eb18dd606b
Thanks!
