### ISSUE TITLE
(Ex1.5.2) Array accesses for find might be not right

### ISSUE THREAD

**Issue by emergencyd** [reneargento/algorithms-sedgewick-wayne#135]
while (p != id[p]) {p = id[p];} 
I think this step access id[] twice if p != id[p]. So my answer for "5-7, 0-3, 4-2" are 9, 5, 5

**Comment by reneargento** [comment]
You are right, that step access the array twice.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/438712053e48e9031c2d3e75011c8921b0391c0a
Thanks!
