### ISSUE TITLE
(1.5.3) the contents of the id[] and the array access might not be right

### ISSUE THREAD

**Issue by emergencyd** [reneargento/algorithms-sedgewick-wayne#136]
It seems that you didn't count the array access for sz[]. Also, the access number for find might not be right. BTW, please check your tree. According to your WeightedQuickUnion.java, the contents is not right. Below is my answer:
9-0: 9 1 2 3 4 5 6 7 8 9 ; 7 access
3-4: 9 1 2 3 3 5 6 7 8 9 ; 7 access
5-8: 9 1 2 3 3 5 6 7 5 9 ; 7 access
7-2: 9 1 7 3 3 5 6 7 5 9 ; 7 access
2-1: 9 7 7 3 3 5 6 7 5 9 ; 9 access
5-7: 9 7 7 3 3 7 6 7 5 9 ; 7 access
0-3: 9 7 7 9 3 7 6 7 5 9 ; 9 access
4-2: 9 7 7 9 3 7 6 7 5 7 ; 13 access

**Comment by reneargento** [comment]
I updated the array contents and access counts here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/879945c71fb74a6e46437d64ec032b9223a59869
I didn't add the size[] array access counts because the exercise doesn't mention it in the description.
Thanks!
