### ISSUE TITLE
Several potential flaws of 4.1.45 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#140]
It seems there are several flaws in [4.1.45 solution](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter4/section1/Exercise45_RealWorldGraphs.java).

1. At this line:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/d57681a5f016f08b91ac07f65e7380b469f7b0d9/src/chapter4/section1/Exercise45_RealWorldGraphs.java#L130
the loop continues without adding a new vertex to the subgraph, but we count this loop iteration as if the vertex was added. The same is true for the following line and edges:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/d57681a5f016f08b91ac07f65e7380b469f7b0d9/src/chapter4/section1/Exercise45_RealWorldGraphs.java#L172

2. Adjacent vertices are being added in the nested loop here:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/d57681a5f016f08b91ac07f65e7380b469f7b0d9/src/chapter4/section1/Exercise45_RealWorldGraphs.java#L139
However, they are not counted, the `vertex` variable is not incremented and the condition `vertex < randomVerticesToChoose` is not checked in this nested loop.

3. The loop
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/d57681a5f016f08b91ac07f65e7380b469f7b0d9/src/chapter4/section1/Exercise45_RealWorldGraphs.java#L167
actually can be made deterministic using the reservoir sampling approach.

4. Adjacent vertices of a random vertex are being added to the new graph. Edges from this vertex to its adjacent vertices are being added, too:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/d57681a5f016f08b91ac07f65e7380b469f7b0d9/src/chapter4/section1/Exercise45_RealWorldGraphs.java#L150
However, it's possible that some edges are missed after the outer loop finishes. Consider the following full graph: `0-1-2-3-4-5`. Then the code might add the vertex `0` and its adjacent vertices (`1`). The edge `0-1` is added to `allSubGraphEdges` in this case. The next iteration the code might add the vertex `3` and its adjacent vertices (`2` and `4`). Edges `2-3` and `3-4` are added to `allSubGraphEdges`. However, at this point we should also add the edge `1-2` (as the vertices `0`, `1`, `2`, `3`, `4` are already in the subgraph), which is never done if the loop terminates at this point.

5. I'm not sure if all possible subgraphs produced by the code are equally likely. The internal loop which adds adjacent vertices seems to distort the probability of all graphs being equally likely. The exercise itself does not require to add these adjacent vertices, in my book it says `choosing V vertices at random`, so probably this step is not needed at all. Probably it's a good idea to write simple test code and run it on a relatively small full graph to see if the probabilities of all subgraphs are the same.

**Comment by reneargento** [comment]
I had initially understood the exercise phrase of "subgraph induced by those vertices" as relating to the random vertices and their neighbors.
But on a closer look it seems that it is related only to the selected vertices, which makes things simpler.

I believe this update contain fixes to all the points you described: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/596c5edda52942ce9adc92cb7ac6694b407448b0
Thanks!

**Comment by dragon-dreamer** [comment]
Thanks, looks good to me, except for this part:
```java
Edge[] allSubGraphEdgesArray = new Edge[allSubGraphEdges.size()];
allSubGraphEdgesArray = allSubGraphEdges.toArray(allSubGraphEdgesArray);

// Randomly choose edges
for(int edgeIndex = 0; edgeIndex < randomEdgesToChoose; edgeIndex++) {
	int randomEdgeId = StdRandom.uniform(edgeIndex, allSubGraphEdgesArray.length);

	Edge randomEdge = allSubGraphEdgesArray[randomEdgeId];
	allSubGraphEdgesArray[randomEdgeId] = allSubGraphEdgesArray[edgeIndex];
	allSubGraphEdgesArray[edgeIndex] = randomEdge;

	randomSubGraph.addEdge(randomEdge.vertex1, randomEdge.vertex2);
}
```
The correct implementation of the reservoir sampling approach should look like this, I suppose:
```java
Edge[] allSubGraphEdgesArray = new Edge[randomEdgesToChoose];
for (int edgeIndex = 0; edgeIndex < randomEdgesToChoose; edgeIndex++) {
	allSubGraphEdgesArray[edgeIndex] = allSubGraphEdges.get(edgeIndex);
}

for (int edgeIndex = randomEdgesToChoose; edgeIndex < allSubGraphEdges.size(); edgeIndex++) {
	int randomEdgeId = StdRandom.uniform(0, edgeIndex + 1);
	if (randomEdgeId < randomEdgesToChoose) {
		allSubGraphEdgesArray[randomEdgeId] = allSubGraphEdges.get(edgeIndex);
	}
}

for(int edgeIndex = 0; edgeIndex < randomEdgesToChoose; edgeIndex++) {
	Edge edge = allSubGraphEdgesArray[edgeIndex];
	randomSubGraph.addEdge(edge.vertex1, edge.vertex2);
}
```

Also it seems that the following line is not needed anymore:
```java
import chapter3.section5.HashSet;
```

**Comment by reneargento** [comment]
The reservoir sampling approach chooses `allSubGraphEdges.size() - randomEdgesToChoose` random numbers, while the method I used chooses `randomEdgesToChoose` random numbers.
Both methods seem to generate a uniform distribution and usually `randomEdgesToChoose` will be smaller than `allSubGraphEdges.size() - randomEdgesToChoose`. Also, the code with just one loop seems to be more compact.
What do you think?
About the import you are right, I removed it on a separate commit.

**Comment by dragon-dreamer** [comment]
Well, I meditated on your code a bit more, and I think you are absolutely right, the code is correct and faster in terms of random number generator calls. The only advantage of the code I provided I can now think of is that it's more memory-efficient (it does not require copying all of the edges of the source graph to the separate large array).

**Comment by reneargento** [comment]
Now that you mentioned it, I noticed that we don't need to copy the list to an array, we can use it directly.
Java's `ArrayList` gives us constant time get() and set() operations.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/a14bc63c7cbfb06be0c92acde12b6c87d69b881e

**Comment by dragon-dreamer** [comment]
Perfect, thank you!
