### ISSUE TITLE
Deterministic interval generation in 4.1.46

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#141]
Is there a reason for the non-deterministic interval generation algorithm in [4.1.46 solution](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter4/section1/Exercise46_RandomIntervalGraphs.java#L109)?

I guess, it's possible to change this code:
```java
            double randomIntervalStart = 0;

            while (!randomIntervalGenerated) {
                randomIntervalStart = StdRandom.uniform();

                if (randomIntervalStart + length <= 1) {
                    randomIntervalGenerated = true;
                }
            }
```

To something like this:
```java
double randomIntervalStart = StdRandom.uniform(0, 1.0 - length);
```

**Comment by reneargento** [comment]
Generating the intervals deterministically is definitely the best approach.
Exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/23780ffef62af6b604ca6c61d3ae4ba2a60a9f47
Thanks!
