### ISSUE TITLE
Fixes and a simpler solution for 4.2.9

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#142]
I believe there's a simpler solution for the [4.2.9 exercise](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter4/section2/Exercise9.java).

But let's start with the fixes first. It's required to check if the size of `topologicalOrder` is the same as the amount of vertices in the graph. Otherwise, for example, the algorithm will always return `true` for an empty `topologicalOrder` list. So, the following check is required before running the main algorithm loop:
```java
if (topologicalOrder.size() != digraph.vertices()) {
	return false;
}
```

Moreover, it's required to check if the `visitedVertices` hashset already contains `vertex` before adding it. That is, the following modification is required to the main loop:
```java
for(int vertex : topologicalOrder) {
	if (visitedVertices.contains(vertex)) {
		return false;
	}

	visitedVertices.add(vertex);

	if (!dfs(vertex, digraph, visitedVertices)) {
		return false;
	}
}
```

If we skip this check, the algorithm will consider this a valid topological order:
```java
Digraph digraph1 = new Digraph(3);
digraph1.addEdge(0, 1);
digraph1.addEdge(0, 2);
digraph1.addEdge(1, 2);

List<Integer> topologicalOrder1 = new ArrayList<>();
//Notice all zeros here
topologicalOrder1.add(0);
topologicalOrder1.add(0);
topologicalOrder1.add(0);

//This will output true, but the expected result is false
System.out.println(checkTopologicalOrder.isTopologicalOrder(digraph1, topologicalOrder1) + " Expected: false");
```

Now let's turn to the simpler solution (which also fixes the above two issues):
```java
public boolean isTopologicalOrder(Digraph digraph, List<Integer> topologicalOrder) {
	DirectedCycle directedCycle = new DirectedCycle(digraph);
	if (directedCycle.hasCycle()) {
		throw new IllegalArgumentException("Digraph is not a DAG");
	}

	if (topologicalOrder.size() != digraph.vertices()) {
		return false;
	}
	
	boolean visited[] = new boolean[digraph.vertices()];
	for (int i = topologicalOrder.size() - 1; i >= 0; --i) {
		int vertex = topologicalOrder.get(i);
		if (visited[vertex]) {
			return false;
		}
		
		visited[vertex] = true;
		for (int neighbor : digraph.adjacent(vertex)) {
			if (!visited[neighbor]) {
				return false;
			}
		}
	}
	
	return true;
}
```

Observe, that when we iterate over the `topologicalOrder` in reverse, all neighbors of the vertex we're currently looking at must have been already visited. Thus, we don't even need DFS here. This solution will always take `O(V + E)`, while the original one may take `O(V * (V + E))` in the worst case.

**Comment by reneargento** [comment]
Nice solution. I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/f5f0a79b51ec8920a6900fc6f9cf249cd4048298
Thanks!

**Comment by dragon-dreamer** [comment]
Thanks!

**Comment by bitflame** [comment]
wow I really like this solution. It was curious about why we return false when the neighbor was not visited. I got exactly the explanation I was looking for. Very nice.
