### ISSUE TITLE
Incorrect 4.2.10 proof

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#143]
It seems to me, there exist counterexamples to [the proof you provided](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter4/section2/Exercise10.txt).

That proof states the following: `The topological sort that results from such algorithm depends on the order in which the vertices adjacent to each vertex are chosen.` However, this is not the only condition which might alter the topological order. The second condition is the order in which the vertices, which are not reachable from each other, are examined.

Consider the following graph with 4 vertices:
```
0 -> 1
0 -> 2
2 -> 3
```

For this graph, the following valid topological order will be never achieved with DFS: `0 - 2 - 1 - 3`. DFS will always follow the `2->3` branch before examining the vertex `1`.

**Comment by reneargento** [comment]
Interesting, so a DFS-based approach will always find a topological order, but it can’t always find any topological order.
Exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/4f1114ecb5abfafe5b889e5b8abc2ca42b026666
Thanks!
