### ISSUE TITLE
Question about the 4.3.19 solution

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#147]
My book has the following 4.3.19 exercise wording:

> 4.3.19 Suppose that you use a priority-queue implementation that maintains a sorted
list. What would be the order of growth of the worst-case running time for Prim’s algorithm
and for Kruskal’s algorithm for graphs with V vertices and E edges? When would
this method be appropriate, if ever? Defend your answer.

[The solution for this exercise in the repository](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter4/section3/Exercise19.txt) mentions scanning through all of the `V` entries to find the vertex with the smallest weight. Is it really needed to scan all the vertices? When we have a **sorted linked list by weight**, it takes `O(1)` to find or remove the item with the smallest weight. At the same time, it would take `O(N)` to insert a new item in such a list or to remove any item (except the minimum) from it.

Consequently, the worst-case complexity of the Prim's lazy algorithm would probably be `O(E^2)`, the complexity of the Prim's eager algorithm would be `O(E*V)`, and the complexity of the Kruskal’s algorithm would probably remain the same (`O(E*logE)`), because we build the sorted list in the constructor of the priority queue (just once), and this takes `O(E*logE)` to sort all edges by weight, and then we only apply the `delMin` operation, which takes `O(1)` for the sorted-list priority queue.

**Comment by reneargento** [comment]
It seems that this exercise changed in recent versions of the book.
This is the wording I see on mine:

> Suppose that you implement PrimMST but instead of using a priority queue to find the next vertex to add to the tree, you scan through all V entries in the distTo[] array to find the non-tree vertex with the smallest weight. What would be the order of growth of the running time for graphs with V vertices and E edges? When would this method be appropriate, if ever? Defend your answer.

**Comment by dragon-dreamer** [comment]
In this case your solution is correct. I'm sorry for creating an issue because of the differences in the exercises again, but I don't have a newer book (and wasn't able to find it online). In most cases, it's easy to guess the original question from the solution, but this exercise has really confused me.
