### ISSUE TITLE
Question about twoSumFaster2 method in Exercise 1.4.15

### ISSUE THREAD

**Issue by ontvzla** [reneargento/algorithms-sedgewick-wayne#150]
Hi Rene,

Thanks for making the repository, it has been really helpful. 
In regards to method twoSumFaster2  (https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter1/section4/Exercise15_1_TwoSumFaster.java), you mention on the comments that "it runs in O(n^2) when there are duplicate keys". I guess you comment that because of the **tempIndex** variables to control both inner while loops you use to shrink the window. In theory, if you modify the **start** and **end** variables in your inner while loops to count the frequencies from both array[start] and array[end], wouldn't that run in O(n) time? Maybe I am not understanding the problem correctly, it would be helpful if you could clarify.

Here is my example so you can better get the idea, basically in the inner loops when I match two numbers that sum 0 I count frequencies from both sides, respecting the lo<hi condition. At the end I just multiply frequencies to get the sum for that number.

    public int twoSumFaster(int[] input) {
        if (input.length < 2) return 0;

        sum = 0;
        int lo = 0;
        int hi = input.length - 1;
        int rightFrequency = 1;
        int leftFrequency = 1;

        while (lo < hi) {
            int leftNumber = -input[lo];
            int rightNumber = input[hi];

            if         (leftNumber > rightNumber) lo++; 
            else if (rightNumber > leftNumber) hi--;
            else {
                // Get right side frequency
                while (input[hi-1] == leftNumber && lo < hi-1) {
                    hi--;
                    rightFrequency++;
                }
                // Get left frequency
                while (-input[lo+1] == rightNumber && lo+1 < hi) {
                    lo++;
                    leftFrequency++;
                }
                sum += leftFrequency * rightFrequency;
                lo++;
                hi--;
                leftFrequency = 1;
                rightFrequency = 1;
            }
        }
        return sum;
    }

**Comment by reneargento** [comment]
Hi, I'm happy to know that the repository has been helpful for you.

You are right , if we modify both `start` and `end` indexes in the inner loops we can have linear time on that algorithm.
Notice that there is an edge case that has to been handled: when we have an array in which all values are 0.

I updated the exercise based on your suggestion and handling that edge case here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/893c4430288adee44c05313c91bf4ad6db842416
Thanks!

**Comment by reneargento** [comment]
Actually, a better handling of the zero values edge case is this: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/fe8403880a5d28ca2fb1711ba3eeb8663401b678
The edge case happens not only when all values in the array are zero, but also when we have elements with value zero in the middle of the array.

**Comment by ontvzla** [comment]
Hey Rene,

Dumb mistake forgetting about that case. Awesome. I just updated my code with your handleZerosEdgeCase method. Out of curiosity,  how did you end up with that formula ? I realize it is the same as calculating the combinations formula ( n! / (n - r!)*r! ).

Thanks for everything !

**Comment by reneargento** [comment]
I ended up with the formula based on the observation of how the zeros match:
If we have 6 zeros, the first one will match with the other 5, the second one with the other 4, and so on, until the fifth zero match the last one.
That is a sum of `1 + 2 + … + 5` matches, or, if we generalize it, `1 + 2 + … + (n - 1)` matches.
That sum can be written as: `(1 + (n - 1)) * (n - 1) / 2`

**Comment by ontvzla** [comment]
you're right. I forgot about that sequence formula. Thanks for taking the time to reply. Keep up the hard work !
