### ISSUE TITLE
Time complexity of 4.4.38 ("Sensitivity")

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#151]
Time complexity of the sensitivity algorithm is assumed to be `O(E * V)`:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/0690e5ecf3837a9bbc17c3f398df1a6ef8549274/src/chapter4/section4/Exercise38_Sensitivity.java#L49-L50

There's a loop to initialize the `sensitivity` matrix (which takes `O(V^2)`), and then Dijkstra is executed for each vertex, which takes `O(E*V*logV)`. Probably, total time complexity should be `O(V^2 + E*V*logV)`.

**Comment by reneargento** [comment]
You are right, exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/641914d57e2bbb936aab79321efb705c62936362
Thanks!
