### ISSUE TITLE
Mistake in the algorithm for 4.4.41

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#152]
It seems, there was a commit https://github.com/reneargento/algorithms-sedgewick-wayne/commit/e520f8647dd15ccd6dd2286d7aa0b176b9c2298d#diff-d736a533bd5c532c214ebb97a3828947L107 which has revealed a mistake in the algorithm. The call `changeKey` was replaced with `decreaseKey` on two lines. Now, when I run the algorithm, I get the following exception for the second graph:
```
Exception in thread "main" java.lang.IllegalArgumentException: Calling decreaseKey() with given argument would not strictly decrease the key
```

I started to dig deeper and finally found the mistake which caused the exception. It seems, the reason is in the following lines:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/0690e5ecf3837a9bbc17c3f398df1a6ef8549274/src/chapter4/section4/Exercise41_BidirectionalSearch.java#L126-L130

I changed them to this code:
```java
int modifiedVertexId = neighbor + edgeWeightedDigraph.vertices();
if (priorityQueue.contains(modifiedVertexId)) {
	priorityQueue.decreaseKey(modifiedVertexId, distToTarget[neighbor]);
} else {
	priorityQueue.insert(modifiedVertexId, distToTarget[neighbor]);
}
```

And the exception is gone, and the algorithm now produces the expected results.

**Comment by reneargento** [comment]
Good catch, exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/9dcba082d2cecaeb9390d5ea254ebc97e1a7ee8a
Thanks!
