### ISSUE TITLE
Another worst case for 3-way string quicksort (5.1.10)

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#153]
It seems, that there's another worst case for the 3-way string quicksort algorithm from the book. If we sort an array made of `N` one-character unique strings in reverse order (for example: `{"e", "d", "c", "b", "a"}`), the algorithm will examine `N + (N - 1) + (N - 2) + ... + 2` characters. Thus the complexity for this case is `O(N^2)`, where `N` is the number of strings.

There are other examples I can imagine. The following array:
```java
String s[] = {
	    "ccc", "ccb", "cca", "cbc", "cbb", "cba", "cac", "cab", "caa",
	    "bcc", "bcb", "bca", "bbc", "bbb", "bba", "bac", "bab", "baa",
	    "acc", "acb", "aca", "abc", "abb", "aba", "aac", "aab", "aaa"
};
```
requires 153 character examinations (by character examination I mean `s.charAt(d)` call), which is definitely more than the amount of characters in all of the source strings (81).

I can not yet derive the exact mathematical formula for the worst-case complexity and the requirements of the source array, but it is clear, that the algorithm can examine more characters than `N * W`.

**Comment by reneargento** [comment]
Makes sense, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/aa4d2f508deda39cd6e4d4e5832e2e529f21eb91
I remember seeing somewhere that the worst case for 3-way string quicksort is O(N * w * lgR), where N is the number of strings in the array, w is the strings' average length and R is the alphabet size. I haven't done experiments to comprove it though.

**Comment by dragon-dreamer** [comment]
Thank you! I'll let you know if I find out something else regarding this question.

**Comment by GenevaS** [comment]
I might have something for this, so please have a look:

For w = 1, we can have at most R unique strings. If we assume that they are in reverse order, we will have to check `R^2 = N` characters in the worst case.

For w = 2, there are R strings starting with the same character that have one of the R unique characters after it (e.g. 'aa', 'ab', 'ac', ...). If we assume that they are in reverse order, we will have to check `R^2 * R^2 = N * R^2` characters in the worst case.

For w = 3, the pattern gives us `R^2 * R^2 * R^2 = N * R^4`.

So, in the worst case, we would have to check `N * R^2(w - 1)` characters.
