### ISSUE TITLE
3.4.18

### ISSUE THREAD

**Issue by zzzasada** [reneargento/algorithms-sedgewick-wayne#154]
Would it be possible for you to justify some of your choices in the code?

**Comment by zzzasada** [comment]
More specifically, what getLoadFactor() represents?

**Comment by reneargento** [comment]
[getLoadFactor()](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/aa4d2f508deda39cd6e4d4e5832e2e529f21eb91/src/chapter3/section4/SeparateChainingHashTable.java#L149) is implemented on `SeparateChainingHashTableResize`'s superclass.
It computes the size of the lists used by the hash table with the formula K / L, where K is the total number of keys and L is the length of the internal symbol table array.
