### ISSUE TITLE
Solution to Exercise 2.3.10 doesn't answer the question 

### ISSUE THREAD

**Issue by Andrew-Kelley** [reneargento/algorithms-sedgewick-wayne#155]
In the exercise, we are asked to use Chebyshev's inequality, not simply run an expirement.

**Comment by reneargento** [comment]
You are right, I updated the exercise using Chebyshev's inequality: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/0eb000232979fbda518aa535157f6e9e23941313
Thanks!
