### ISSUE TITLE
Small correction for 5.3.18

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#158]
Here is what stated in the solution:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/bdf1ea5e075c67bb1cf52acaa7041c8d26903625/src/chapter5/section3/Exercise18.txt#L5-L13

However, it seems that the second check is going to be:
```
T1 T2 T3 … TM+1 TM+2 … TN-1 TN
   P1 P2 … PM
```

**Comment by reneargento** [comment]
Fixed: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/f3e7a175c165def21971578588bbc28fb5f54c50
Thanks!
