### ISSUE TITLE
Mistake in the regexp for 5.4.9?

### ISSUE THREAD

**Issue by dragon-dreamer** [reneargento/algorithms-sedgewick-wayne#159]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/bdf1ea5e075c67bb1cf52acaa7041c8d26903625/src/chapter5/section4/Exercise9.txt#L3-L4
It seems this regexp still allows two consecutive zeros:
```
(01|1)*01+0(01|1)*
          ^^^
These marked characters allow two zeros to be consecutive.
```

Possibly, the expression in the second group of parentheses should be `(10|1)`.

**Comment by reneargento** [comment]
You are right, exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/f3f316e46c6b6300a5771001f5373c656feee7c1
Thanks!
