### ISSUE TITLE
Incorrect subarray size in 2.3.7?

### ISSUE THREAD

**Issue by MrScislowski** [reneargento/algorithms-sedgewick-wayne#161]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/96b1e97a7cc81de1bc364c7b01e146a2f74d8211/src/chapter2/section3/Exercise7.java#L54

I get a different solution than you because of this line. Shouldn't it just be 
`int rightSubArraySize = high - partition;`?

For example, partitioning with low = 0, high = 6:
`0 1 2 3 4 5 6`
`E X A M P L E`
the partition will be 2, leaving a left subarray of size 2 - 0 = 2, and a right subarray of size 6 - 2 = 4.

Changing that line of code changes the conclusions in Exercise7.txt. I get:
Subarray size 0: 1/3 N
Subarray size 1: 1/3 N
Subarray size 2: 1/6 N

PS: Thanks so much for this repository; it's super helpful to be able to check my answers. The only downside is that I usually feel inadequate because your solutions are more elegant ;)

**Comment by reneargento** [comment]
You are right, I updated the size computation here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/f31578352b7774e857a664bf8768bca2200e75e0

I'm glad that the repository is being useful to you! It is expected that as you practice, your solutions will get more and more elegant as well :) And as you can see, there is always room for improvement.
Thanks for the contribution!
