### ISSUE TITLE
A tiny mistake

### ISSUE THREAD

**Issue by Jinchul81** [reneargento/algorithms-sedgewick-wayne#164]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/2d2a19f839dc1b2a1fb9437652145353cc7c83d6/src/chapter1/section5/QuickUnion.java#L33

Time complexity should be O(n). I guess you might be working based on QuickFind.java.

**Comment by reneargento** [comment]
You are right, I fixed it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/63c5ec22e0ca458bc250db455d4edb2ae1fb18f7
Thanks!
