### ISSUE TITLE
Remove duplicates in generated arrays Ex1.1.39

### ISSUE THREAD

**Issue by Adeboye** [reneargento/algorithms-sedgewick-wayne#165]
In exercise EX1.1.39 after sorting both arrays don't you need to remove duplicates to avoid recounting the same number seen in array1 in array2 ?

**Comment by reneargento** [comment]
You are right, we need to take into account the duplicate values.
There is no need to remove them though, we can just ignore values that we have seen before.
I added a check for it and some other small improvements on that exercise here:
https://github.com/reneargento/algorithms-sedgewick-wayne/commit/9662c992ea00bb4f7f5167bb7a114b9c771e0d13
Thanks!

**Comment by Adeboye** [comment]
nice! Thanks for this project, great work!
