### ISSUE TITLE
Minor Correction

### ISSUE THREAD

**Issue by AdamShamaa** [reneargento/algorithms-sedgewick-wayne#166]
Edit: push to stack should be underneath each "# done" not on top

https://github.com/reneargento/algorithms-sedgewick-wayne/blob/63c5ec22e0ca458bc250db455d4edb2ae1fb18f7/src/chapter4/section2/Exercise10.txt#L1-L23

Correct me if I am incorrect however your given example of topological order below may in fact be produced by a DFS-based algorithim.
>0 - 2 - 1 - 3  

Using the adjacency list below - a possible adjacency list from your example:
>0 -> 1 -> 2
>1 
>2 -> 3
>3

Proposition: A DFS-based algorithm may observe the source vertices of a graph in any given order. 
This is simply determined by the fact that a DFS constructor will call all vertices as determined by the developer.

See _Kosaraju’s_ algorithm listed below which is directly from the textbook - an example of a DFS-based algorithm which does not observes source vertices in the traditional 'start at 0 increment by 1 to V-1' way.

```
public KosarajuSCC(Digraph G)
{
  marked = new boolean[G.V()];
 id = new int[G.V()];
  DepthFirstOrder order = new DepthFirstOrder(G.reverse());
  for (int s : order.reversePost())
      if (!marked[s])
      {  dfs(G, s); count++;  }
}
```
Solution:
By using a DFS-based algorithm and checking the vertices in this listed order the example topological order will be produced.
>3, 0

Which will produce the given trace:
```
dfs(3)
    3 done
    push 3 to stack
dfs(0)
    dfs(1)
       1 done
       push 1 to stack
    dfs(2)
       check 3 (already marked)
       2 done
       push 2 to stack
0 done
push 0 to stack
```
Producing the stack:
```
0, 2, 1,  3
```
Therefore this statement isn't valid in this scenario:
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/63c5ec22e0ca458bc250db455d4edb2ae1fb18f7/src/chapter4/section2/Exercise10.txt#L20

*Side Note - Thank you for your repository over here from Toronto, Canada it has been very helpful

**Comment by reneargento** [comment]
Indeed, it looks correct. 
So it seems that there is no topological order that cannot result from applying a DFS-based algorithm. I reverted the exercise to its previous answer:  https://github.com/reneargento/algorithms-sedgewick-wayne/commit/916145a272efc54911f1a6367680e081b39705b0
Thanks for the contribution and I’m happy to know that the repository has been useful to you!
