### ISSUE TITLE
minor issue 1.5.4

### ISSUE THREAD

**Issue by sergiovasquez122** [reneargento/algorithms-sedgewick-wayne#168]
for the worst case inputs you have 9 components aka
id[]
0 1 2 3 4 5 6 7 8 9
where the worst case input only has 7 components.
removing the 8 and 9 for the id array and sz is sufficient to fix this issue,
everything else is correct. Thanks for the solution manual!

**Comment by reneargento** [comment]
I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/28a778356d7feffa6549309b7c1d52ea401dd815
Thanks for the contribution!
