### ISSUE TITLE
Issue in 1.5.3

### ISSUE THREAD

**Issue by sepehrhakimi90** [reneargento/algorithms-sedgewick-wayne#17]
Seems 1.5.3 solved with quick union while excersice requested to solve it with weighted quick union. If you check and find my concern is correct please let me know to share my answer with you.

**Comment by reneargento** [comment]
Exercise 1.5.3 used weighted quick union, but some values were indeed incorrect.
I updated them: https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter1/section5/Exercise3.txt

Thanks for pointing this out :) 
Let me know if your solutions are different than the updated ones.

**Comment by reneargento** [comment]
I'm closing this issue as it has been fixed and the last comment was made over a year ago.
