### ISSUE TITLE
Exercise 2.1.19

### ISSUE THREAD

**Issue by YRFT** [reneargento/algorithms-sedgewick-wayne#170]
I have made a test for this exercise. Below is the results for 100 array elements:

Random - Compares: 745 Exchanges: 451
Reversed - Compares: 500 Exchanges: 230
Ordered - Compares: 342 Exchanges: 0

Reverse order does not  seem like the worst case for shell sort.

**Comment by w1374720640** [comment]
I also found this problem. My approach is: create an array of length 100, randomly shuffle, determine the number of comparisons, and repeat the above process violently to find the worst case.😱

**Comment by reneargento** [comment]
@w1374720640 that seems to be the best approach to find the worst-case input.
The wording in the exercise also suggests that there is no deterministic answer (“uses as large a number of compares as you can find.”).

I updated the exercise to use that approach: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/074747b982f3f27f7253b6b412d97b99baaf498d
@YRFT thanks for reporting the issue and @w1374720640 thanks for suggesting an approach to solve it.
