### ISSUE TITLE
Exercise 2.2.12

### ISSUE THREAD

**Issue by w1374720640** [reneargento/algorithms-sedgewick-wayne#171]
Exercise requirements: Reduce the required extra space to max(M,N/M), but you have created (N/M-1) arrays of size M, the total extra space required is: (N/M -1) * M, approximately equal to N, the extra space at a certain moment is M, which does not meet the requirements of the question

**Comment by reneargento** [comment]
The `aux[]` array is recreated every time we call the `mergeBlocks()` method. We never have more than one of those arrays at the same time. 
The situation you describe would be the case if we were calling that function recursively, for example, where we would have multiple `aux[]` arrays existing at the same time.

**Comment by w1374720640** [comment]
If N=1000, M=10, then max(M,N/M)=100, but you only need an array of size 10 at the same time

**Comment by reneargento** [comment]
Correct, in that example we just need a size of 10 at the same time, which is even better than the `max(M, N / M)` that the exercise requires.
I’m not sure if there is something wrong with the exercise description or if there is another approach to it in that case. We could always make the `aux[]` array have size `N / M` when `N / M > M` just to keep the memory as `max(M, N / M)`, but a size `M` is always enough to do the merges.

**Comment by w1374720640** [comment]
Using bubble sort optimization exercise 2.2.12 can save half of the running time, I submitted a pull request, please check
