### ISSUE TITLE
Minor optimization

### ISSUE THREAD

**Issue by AdamShamaa** [reneargento/algorithms-sedgewick-wayne#173]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/074747b982f3f27f7253b6b412d97b99baaf498d/src/chapter5/section1/Exercise7.java#L35-L47

I noticed the queue implementation allows for the possibility to remove the auxiliary array (although memory savings would be rather negligible) slight savings of 2dn accesses- d the # of characters & n the number of strings - could be saved by copying to the input array directly (savings come from avoiding the .enqueue and .dequeue operations in the inner loops). Readability would also still be maintained. I've written below what that code could look like.

```
//Copy Back
int indexArray = 0;
for (int r = 0; r < count.length; r++){
	while (!count[r].isEmpty()) {
		String string = count[r].dequeue();
		array[indexArray++] = string;
	}
} 
```

-Thanks again, the repository has been very helpful

**Comment by reneargento** [comment]
Looks good, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/ab8070ab640f8cfb30dda079d6afa2a87c9c56ed
Thanks for the contribution!
