### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by AdamShamaa** [reneargento/algorithms-sedgewick-wayne#174]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/074747b982f3f27f7253b6b412d97b99baaf498d/src/chapter5/section3/Exercise4.java#L1-L44

I believe a more efficient solution exists, where the savings would come from the removal of the preprocessing for the DFA. 

Accordingly the search runtime would be approximately identical - the typical case is 1.1N character compares while the worst case is 2N character compares. There would be a large optimization by reducing the preprocessing of the DFA - run-time & space of R*M (where R is the radix & M is the pattern length). Additionally, this would avoid the M + N array accesses required for accessing the DFA.

I've written below the optimized version which requires no backtracking and no additional pre-processing contingent on the fact that this method is designed to specifically find "the first occurrence of M consecutive blanks in the string".  Therefore a DFA would not be required since all characters in the pattern are identical, if a mismatch were to occur in any case then the pattern index must restart at 0.

```java
public int findBlankCharacters(String txt, int M) {
		int N = txt.length();
		int consecutiveBlanks, i;
		for (i = 0, consecutiveBlanks = 0; i < N && consecutiveBlanks < M; i++) {
			if (txt.charAt(i) == ' ') consecutiveBlanks++;
			else consecutiveBlanks = 0;
		}
		if (consecutiveBlanks == M) return i-M;	  //found
		else return N;              		  //not found
}
```

**Comment by reneargento** [comment]
Exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/6595ced86fd7b896f32d6f64e830976537b7f494
Thanks!
For the character comparisons estimation, wouldn't it be N / 2 as an average in the typical text and N in the worst case?
It seems that we never do more than N comparisons with that method.

**Comment by AdamShamaa** [comment]
I agree! Thanks again, I truly appreciate your commitment and time in continuing to maintain this repository.
