### ISSUE TITLE
Issue in Chapter1/Section1/Exercise34_Filtering

### ISSUE THREAD

**Issue by imyuewu** [reneargento/algorithms-sedgewick-wayne#175]
Print the Kth smallest value, for K less than 100

This can be implemented as a filter, with a container size of K, does not require saving all values.

**Comment by reneargento** [comment]
You are right, I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/89c014b83277cb11951b94ad78e315febe15b3fd
Thanks for the contribution!

**Comment by sickboydroid** [comment]
I am not able to understand the meaning of the statement.
What does it mean to print the kth value??

**Comment by reneargento** [comment]
In this case `K` is a generalization of any possible number we can choose. 
For example, when we say "Print the 5th smallest value", K is equal to 5.

**Comment by Sdssourcing** [comment]
#
