### ISSUE TITLE
Exercise 1.4.18

### ISSUE THREAD

**Issue by sjbzhc** [reneargento/algorithms-sedgewick-wayne#178]
Hi, 

the description in the book (4th edition) defines a local minimum as: a[i-1] < a[i] < a[i+1]. The current implementation solves the problem: a[i-1] > a[i] && a[i] < a[i+1] (which is more complicated). I am assuming that the book did a mistake with the first < symbol, but I still wanted to let you know. 

Solving a[i-1] < a[i] < a[i+1] is simpler:

        for (int i =0; i < array.length - 2; i++) {
            if (array[i] < array[i+1] && array[i+1] < array[i+2]) {
                return array[i+1];
            }
        }

**Comment by reneargento** [comment]
Yep, the book did a mistake on the first `<` symbol.
It is registered on the errata: https://algs4.cs.princeton.edu/errata/errata-printing1.php
