### ISSUE TITLE
Unit test?

### ISSUE THREAD

**Issue by fengxiaohu** [reneargento/algorithms-sedgewick-wayne#179]
# @reneargento thanks for creating the precious repo.
it really help me.And I am wondering why there is no unit test in Solution code.
How do I test the solution code

**Comment by reneargento** [comment]
I'm glad to know that the repository has been useful to you!
On the `main()` method of the exercises there is usually a list with given inputs and expected results. You can check the result with those tests.

**Comment by fengxiaohu** [comment]
OK,thx
