### ISSUE TITLE
Duplicate tree shapes in 3.2.9

### ISSUE THREAD

**Issue by dbedrenko** [reneargento/algorithms-sedgewick-wayne#18]
For N = 5 you produce duplicate tree shapes, for example:

```
Insertion order: 5 2 1 4 3, 5 2 4 1 3
   5
  2
1   4
  3
```

and

```
Insertion order: 5 2 4 3 1
   5
  2
1   4 
  3
```

There should be 42 tree shapes for N = 5

PS: Thanks a lot for these solutions! I use them to check if my answers were correct, they are very well written :)

**Comment by reneargento** [comment]
Thanks for pointing out about the duplicate tree shapes, I fixed it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/39b88af12a56200cf870b83f21b7694f4ad2b5ef

And I'm glad the solutions have been useful to you! Thanks for the feedback :)

**Comment by reneargento** [comment]
I'm closing this issue as it has been fixed and the last comment was made over a year ago.
