### ISSUE TITLE
Exercize 2.5.2

### ISSUE THREAD

**Issue by kalyakinv** [reneargento/algorithms-sedgewick-wayne#180]
hi, thank you for your great work done

correct me if i'm wrong
there is way to make ex.2.5.2 (about compound words) even faster - from O(n^2) to O(n), 
we don't need to run through all elements in inner loop, searching for a compound word by its prefix-word (in outer loop)
because compound words will only be those which start with the same letter as their prefix-word
so may be smth like this:

    //O(n)
    public List<String> find() {
        var compoundWords = new ArrayList<String>();
        var wordSet = new HashSet<>(sortedWords);
        int iteration = 0;
        for (int i = 0; i < sortedWords.size(); i++) {
            var prefix = sortedWords.get(i);
            char prefixStartingChar = prefix.charAt(0);
            char wordStartingChar = prefixStartingChar;
            for (int j = i + 1; j < sortedWords.size() && wordStartingChar == prefixStartingChar; j++) {
                iteration++;
                var word = sortedWords.get(j);
                wordStartingChar = word.charAt(0);
                if (word.startsWith(prefix)) {
                    String postfix = getPostfix(prefix, word);
                    if (wordSet.contains(postfix)) {
                        compoundWords.add(word);
                    }
                }
            }
        }
        logger.info("words.size = {}, iterations = {}", sortedWords.size(), iteration);
        return compoundWords;
    }

**Comment by reneargento** [comment]
Hello and thanks!

The solution you are proposing is also O(n^2).
Consider the worst case where we have a list where all words start with the same letter. In this case we will have O(n^2) performance.

The current solution in the repository will also break from the inner loop if at any moment the next word does not have the outer loop word as a prefix.

**Comment by kalyakinv** [comment]
My fault, you're right, thx
