### ISSUE TITLE
Exercise 2.4.29.

### ISSUE THREAD

**Issue by YRFT** [reneargento/algorithms-sedgewick-wayne#181]
In deleteMax and deleteMin methods, the code first delete the top node in corresponding priority queue then delete the node in another priority queue.
To my way of thinking, the second procedure in above does not seem like correct.
The `deleteItem` method only executes a sink operation. But we can't determine we should do sink or do swim when we have exchanged the last node and the node we want to delete.

For example:

The MaxPQ is
```
           10
     5           9
   3   4       7   8
```
If we want to delete 4, we exchange 4 and 8.
```
           10
     5           9
   3   8       7   4
```
Then set the last node to null.
```
           10
     5           9
   3   8       7
```
Then we need to do a swim, not sink.

So I guess we should do both sink and swim in `deleteItem`.

**Comment by reneargento** [comment]
Good catch, in some cases we will also need to call the `swim` method.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/06b0a5b336350614150b3ecba433fe98e5777630
Thanks for the contribution!

**Comment by YRFT** [comment]
Ok, thanks.
