### ISSUE TITLE
4.3.2 Draw all of the MSTs of the graph depicted at right (all edge weights are equal).

### ISSUE THREAD

**Issue by Miroier** [reneargento/algorithms-sedgewick-wayne#184]
![image](https://user-images.githubusercontent.com/45321964/100424537-b13ba280-30c8-11eb-85d5-1ef6d510eb19.png)

This is my first time to raise issue. Maybe something is not so formal. My native language is not English, so there may be some problems in expression.

The number of edges in a tree is the number of nodes minus one, and a tree has no ring. Because this is a simple graph, 8 nodes, so the tree has 7 edges, and you can see that there are 5 possible rings out of 10 edges.

The idea is to go through the set of all the possible edges, and if the set size is 7, see if there's a ring, if there's no ring, then it's an answer.

```cpp
#include "cstdio"
#include <iostream>
using namespace std;
int main()
{
    int a[5] = {
        23,  //0000010111
        360, //0101101000
        720, //1011010000
        711, //1011000111
        952, //1110111000
    };
    int k = 7;
    int U = 1 << 10;
    int cnt = 0;
    for (int S = 0; S < U; S++)
        if (__builtin_popcount(S) == k)
        {
            bool flag = true;
            for (int i = 0; i < 5; i++)
                if ((S & a[i]) == a[i])
                    flag = false;
            if (!flag)
                continue;
            cnt++;
            printf("     9 8 7 6 5 4 3 2 1 0\n");
            printf("%2d: ", cnt);
            for (int i = 9; i >= 0; i--)
                printf("%2d", (S & (1 << i) ? 1 : 0));
            cout << endl;
        }
    return 0;
}
```
The number of the 10 edges, from zero to nine
![The number of the 10 edges, from zero to nine](https://user-images.githubusercontent.com/45321964/100424273-4d18de80-30c8-11eb-8e41-514858016bde.jpg)
My_answer_1
![My_answer_1](https://user-images.githubusercontent.com/45321964/100424378-789bc900-30c8-11eb-9efb-4eecb44422ac.jpg)
My_answer_2
![My_answer_2](https://user-images.githubusercontent.com/45321964/100424386-7afe2300-30c8-11eb-88a2-a224a0a45959.jpg)

**Comment by reneargento** [comment]
Nice approach for finding all the possible MSTs.
I updated the exercise with the ones missing here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/cca083da9071e2f898e7d8d82bef21a9782077ec
Thanks for the contribution!
