### ISSUE TITLE
Chapter 1 Section 3 

### ISSUE THREAD

**Issue by Adeboye** [reneargento/algorithms-sedgewick-wayne#185]
Hi,

Correct me if I am wrong but I believe there is an error in Chapter 1 Section 3 Circular Linked List in the remove(int index) method.  Btw line 98-102
```
current.next = current.next.next;

 if (current.next == last) {
       last = current;
}
```
Why is last set to be current if current.next == last ? Shouldn't the check be along these lines
```

            if (currentNode.next.next == first)  {
                currentNode.next = first;
                last = currentNode;
            } else {
                currentNode.next = currentNode.next.next;
            } 
```

Thanks

**Comment by reneargento** [comment]
You are right, the order of those two statements was inverted.
First we should check if we are deleting the `last` item and update the `last` reference, and then we delete it.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/92da7c68207fe8ab38ce9c9cc590ff82d93ce3f3
Thanks!

**Comment by Adeboye** [comment]
nice ! as always thanks for the wonderful work on this
