### ISSUE TITLE
Chapter 3 section 3,  exercise 37

### ISSUE THREAD

**Issue by Hunter-Chen** [reneargento/algorithms-sedgewick-wayne#186]
I think you misunderstood the problem in the book. 

3.3.37 _Memoryless. Show that red-black BSTs are not memoryless: for example, if you
insert a key that is smaller than all the keys in the tree and then immediately delete the
minimum, **you may get a different tree**._

Yet your answer was demonstrating how it can lead to **the same tree**

**Comment by reneargento** [comment]
Indeed, the previous answer was incorrect.
I fixed it with a correct red-black BST example here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/0b7f9eb11aa482ba3c10642d56fe995ad20dc033
Thanks!
