### ISSUE TITLE
A question about RedBlackBST. 

### ISSUE THREAD

**Issue by YRFT** [reneargento/algorithms-sedgewick-wayne#187]
In exercises 3.3.39, 3.3.40, 3.3.41. There are two implementations of balance in RedBlackBST. One in put method and another in balance method.

In put method we perform "rotate left" only if the left child is black and the right child is red. That's ok because if both children are red, we do not need "rotate". We can just perform "color flip" to raise the middle node up.

But in balance method, we do "rotate left" if the right child is red and do not check the left child. I can't figure out why we don't check the left child. In the current implementation if both children are red, we will do some useless work, because "rotate left" then "rotate right" will not change the tree. In my opinion, we should check the left child as we did in put method to save some work.

I have modified the code in balance method to include the check for the left child and run some tests with the "check" method in booksite. All the tests have been passed.

I have been confused for several days and appreciate any feedback. Thank you.

**Comment by YRFT** [comment]
I have just created a pull request to Kevin’s repo https://github.com/kevin-wayne/algs4/pull/101/commits/b2224bfc4ac8fa157addfbbbcfa64b99bfd926e2.

I will pay attention to the pull request and update this issue to reflect the result of the pull request to let you easy to know will the pull request be merged.

**Comment by reneargento** [comment]
Good question.
I did some tests and tried to find counter-examples to justify not checking both the left and right nodes at the beginning of the `balance()` method and could not find any issue with it.
It looks like it could be added and would avoid unnecessary left rotations.
Let’s see what will be the answer in the `algs4` repository.

**Comment by YRFT** [comment]
The balance method has been optimized in kevin-wayne/algs4@5729bbb.

I'll close this issue. Thanks again.
