### ISSUE TITLE
Exercise 1.1.20

### ISSUE THREAD

**Issue by kyicy** [reneargento/algorithms-sedgewick-wayne#188]
Write a recursive static method that computes the value of ln(N !).
https://tutorial.math.lamar.edu/classes/alg/logfunctions.aspx#MathJax-Element-87-Frame
```math
ln(N!) = ln(N * (N-1)!) = ln(N) + ln((N-1)!)
```
hence the solution
```java
double solution(int N) {
    if (N == 1) return 0;
    return solution(N - 1) + Math.log(N);
}
```

**Comment by reneargento** [comment]
Looks good, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/2684817f15a54e9d8cd07d47da91cafbaec4a617
Thanks for the contribution!
