### ISSUE TITLE
3.2.21 is not uniformly random

### ISSUE THREAD

**Issue by dbedrenko** [reneargento/algorithms-sedgewick-wayne#19]
If you give as input a tree:

```
        5
      /    \
     2     x
```

where `x` is a subtree containing 5 million children. The algorithm provided will return `2` 33% of the time, `5` 33% of the time, and one of the other ~5 million keys the other 33% of the time.

I think the usefulness of this function can be improved: below I provide my Python3 solution that I think is random with a uniform distribution:

```

    def _random_key(self, node):
        # We managed to get to a leaf without picking a node.
        if (not node.left) and (not node.right):
            return node

        rand_for_cur = random.uniform(0, 1)
        # 1/N chance to pick the current node, this is needed for internal nodes
        # to be candidates in the selection.
        if rand_for_cur < (1/self.size()):
            return node
        else:
            if node.left is not None:
                left_child_size = node.left.subtree_size
            else:
                left_child_size = 0

            rand_for_move = random.uniform(0, 1)
            chance_move_left = left_child_size / node.subtree_size
            if not node.left:
                return self._random_key(node.right)
            elif not node.right:
                return self._random_key(node.left)
            else:
                if rand_for_move < chance_move_left:
                    return self._random_key(node.left)
                else:
                    return self._random_key(node.right)
```

**Comment by dbedrenko** [comment]
Never mind, I found an even better solution in this project!

 https://github.com/ChangeMyUsername/algorithms-sedgewick-python/blob/master/chapter_3/module_3_2.py

Get a random number between 0 and size(), then pass that to `select()`.

**Comment by reneargento** [comment]
Nice, a clean and efficient solution indeed.
Thanks for suggesting an improvement to the exercise, it definitely wasn't choosing nodes uniformly at random.

I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/a942e27fb667b7ae446c902a183604a1e4e06074

**Comment by reneargento** [comment]
I'm closing this issue as it has been fixed and the last comment was made over a year ago.
