### ISSUE TITLE
Exercise 1.4.10 (Simpler version of iterative version of binary search IN PYTHON)

### ISSUE THREAD

**Issue by nedas-dev** [reneargento/algorithms-sedgewick-wayne#196]
Hi, Rene!

I believe this is an easier iterative version of binary search to understand than the one given, though it is written in python.

P.S. Just really want to say thank you for this repository it really helps me along the way!
```
def binarySearchSmallestIndex(array, key):
    low = 0
    high = len(array) - 1
    lowestIndex = -1

    while low <= high:
        mid = low + (high - low) // 2
        if array[mid] == key:
            lowestIndex = mid
            high = mid - 1
        elif key > array[mid]:
            low = mid + 1
        else:
            high = mid - 1

    return lowestIndex
```

**Comment by reneargento** [comment]
Hi Nedas!
I'm happy to know that the repository has been useful to you!

Thanks for the contribution as well. As this iterative version is similar to the existing one, I added a comment on the exercise pointing to this page for reference: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/da6e8b1a722906306b164222f203dd2207b0d9e7
