### ISSUE TITLE
2.1.13

### ISSUE THREAD

**Issue by nedas-dev** [reneargento/algorithms-sedgewick-wayne#198]
Hey, Rene!

You were saying that you would use shellsort or quicksort or mergesort. Fix me if i misunderstand something but i believe that only insertion sort, bubble sort and mergesort are STABLE sorting algorithms meaning that they do not mess up the order when you're sorting something twice or more by different means of sorting (as in this case by suit and by the rank).

I will attach the file that i'm looking at from the online material of the book.
<img width="824" alt="runtimes-official" src="https://user-images.githubusercontent.com/63434432/112740252-3e382080-8f30-11eb-9d5c-1ffda10d68ac.png">

**Comment by reneargento** [comment]
Hey Nedas.
Good point, we need a stable sort in this case.
It seems insertion sort might be the best choice then. I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/fc28e15b124fcec3840dc466dda5a44711d396bb
Thanks!

**Comment by zefrawg** [comment]
The concept of stability is not introduced until later in the chapter. More importantly, it isn't at all necessary to sort the cards twice. Instead, we should compare both suit and card at once. Example: 🂲 is unambiguously higher ranked than 🃎 (regardless of their relative ranks within their own suit).

I believe the best answer here is selection sort, but for a non-obvious reason: We are dealing with physical objects! With a selection sort, you may have to look at more cards (twice as many in the average case), but you'll only have to swap their positions at most 52 times versus at most 676 times with an insertion sort. And you can't just cheat and slide the cards as a group. That's not an allowed operation. You have to move them by exchanging two at a time. That's a lot of work!

**Comment by reneargento** [comment]
That is a good point, we can use only one sort in this case.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/c889e4a77133268d209463c37d829218710a3966
Thanks for the contribution!

**Comment by LeoLi2002** [comment]
That insprises me a lot! Theoratically, maybe shell sort is the best answer for this question( among all the three sort introduced in this section ). But in reality, it seems unrealastic to calculate which pairs to check or to exchange. So, doing a lot of repeatition may be a better answer than doing a lot of plus and multiply (which is the basis of shell sort )in this case.
