### ISSUE TITLE
Ex1.5.12&Ex1.5.13 the author asks for an iterative method

### ISSUE THREAD

**Issue by DominicPeng0125** [reneargento/algorithms-sedgewick-wayne#204]
> Modify quick-union (page 224) to include path compression, by **adding a loop** to union() that links every site on the paths from p and q to the roots of their trees to the root of the new tree.

Hi. It seems like the author is asking for an iterative method for Ex1.5.12 and Ex1.5.13 but the current solution is based on recursion. Although I also agree that the recursive method is better in terms of simplicity, we could include an alternative based on iteration just to better meet the requirement of the question?
Here is my code:
```java
public int find(int p)
{
    int root = p;
    while (root != id[root]) root = id[root];
    while (p != id[p])
    {
        int tmp = id[p]; // temporary holder for the next site on the same path to be changed
        id[p] = root;
        p = tmp;
    }
    return root;
}

```

**Comment by reneargento** [comment]
You are right, in this case it is better to have the iterative method.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d60885b21a9f535e82f42c1ee3df44d6eb5fb36c
Thanks for the contribution!

**Comment by DominicPeng0125** [comment]
You are welcome. This repository has helped me a lot :)
