### ISSUE TITLE
Chapter1.Section3 Exercise4 return true directly worked failed.

### ISSUE THREAD

**Issue by SunJenry** [reneargento/algorithms-sedgewick-wayne#207]
```	
private boolean isBalanced(String input) {

		char[] parentheses = input.toCharArray();
		Stack<Character> stack = new Stack<>();
		
		for (char parenthesis : parentheses) {
			if (parenthesis == '('
					|| parenthesis == '['
					|| parenthesis == '{') {
				stack.push(parenthesis);
			} else {
				if (stack.isEmpty()) {
					return false;
				}
				
				char firstItem = stack.pop();
				
				if (parenthesis == ')' && firstItem != '('
						|| parenthesis == ']' && firstItem != '['
						|| parenthesis == '}' && firstItem != '{') {
					return false;
				}
			}
		}
		
                 //return true;
		return stack.isEmpty();
	}
```

Return true directly will work failed in case like ```[()```.

So, I think may be return `stack.isEmpty()` will solve this problem.

**Comment by reneargento** [comment]
You are right, we need to check if the stack is empty at the end.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/aa13aaec2ccbc6c1f90b616b4df6832578b67c6c
Thanks for the contribution!

**Comment by bitflame** [comment]
Thanks. Rene, not to trouble you, but if you have some time, would you mind
have a look at my code below? I don't know junit5 and streams all that
well, but I have managed to make some progress but this unit test only runs
once even though I know I have more data in it. Either way I am so glad to
have found your github site. It has helped me a lot.

class KdTreeTest {
    static class KdTreeArgumentsProvider implements ArgumentsProvider {
        final static File folder = new File("src/main/resources/kdtests/");
        // read the data for each test from the files in a directory
that contains the points, rectangle(s), and the expected result(s)
        // create the kdtree and add points to it by reading two
double values from a file. I wonder how I should design the
        // input data file. Ideally I want all the points first, then
I want to create a rectangle, but it would be nice to
        // have one file that results in multiple test instances with
the same KdTree but different rectangles and expected
        // results
        KdTree kt = new KdTree();
        // create a rectangle by reading four double values from a
file. May be possible to put the data in the same file
        // that way one file has all the data for one test instance
        RectHV r = new RectHV(0.1, 0.1, 0.5, 0.6);
        // Just adding two points to expected points for now, but it
can be expanded.
        Point2D p1 = new Point2D(0.1, 0.2);
        Point2D p2 = new Point2D(0.8, 0.9);
        Point2D[] expectedPoints = {p1, p2};

        // pass the tree instance and the rectangle along with the
expected results to a test method to validate the result
        // the expected results are a set of Points
        @Override
        public Stream<? extends Arguments>
provideArguments(ExtensionContext extensionContext) throws Exception {
            int i = 0;
            int instanceDataLength=300;
            Object[] instanceData = new Object[instanceDataLength];
            for (final File fileEntry : folder.listFiles()) {
                String fileName = fileEntry.getName().toUpperCase();
                if (fileName.endsWith(".TXT")) {
                    Scanner scanner = new Scanner(fileEntry);
                    kt = new KdTree();
                    while (scanner.hasNext()) {
                        double x = scanner.nextDouble();
                        double y = scanner.nextDouble();
                        Point2D p = new Point2D(x, y);
                        kt.insert(p);
                    }
                    instanceData[i++] = kt;
                    instanceData[i++] = r;
                    instanceData[i++] = expectedPoints;
                    if (i>instanceDataLength) instanceData=
resizeArray(2*3,instanceData);
                }
            }
            return Stream.of(Arguments.of(instanceData));
        }
        Object[] resizeArray(int newSize, Object[] oldInstanceDataArray){
            Object[] newArray = new Object[newSize];
            for (int i=0; i < oldInstanceDataArray.length;i++) {
                newArray[i]=oldInstanceDataArray[i];
            }
            return newArray;
        }
    }

    @DisplayName("should create a rectangle with the given coordinates
and test KdTree's range() function")
    @ParameterizedTest(name = "{index}=> kt={0},r={1},expectedPoints={2}")
    @ArgumentsSource(KdTreeArgumentsProvider.class)
    void range(KdTree kt, RectHV r, Point2D[] expectedPoints) {
        Assertions.assertNotNull(kt.range(r));
    }
}

**Comment by reneargento** [comment]
For that `KdTreeTest` I would suggest you take a look at tutorials for how to use JUnit with input from files.

**Comment by bitflame** [comment]
Ok. Thank you so much.
