### ISSUE TITLE
exercise 2.2.16 has better running time

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#217]
The question is
```
Analyze the running time of this algorithm in terms of the array size and the number of maximal increasing sequences in the array
```

The provided answer is
```
Running time: O(n lg IS)
```

If `IS` is the _maximal increasing sequences_, that means the array has at least `N/IS` chunks at the "bottom" to merge with.  Thus`IS` defines the lower bound of running time. I think the better answer is
```
Running time: Omega(n lg IS)
```

**Comment by reneargento** [comment]
It makes sense. I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/3228554761158f488c480743cd3e1ad43d3f1481
Thanks for the contribution!
