### ISSUE TITLE
Exercise25_ComputationalNumberTheory, the size of PriorityQueue add 1 maybe reduntant?

### ISSUE THREAD

**Issue by SunJenry** [reneargento/algorithms-sedgewick-wayne#219]
[`Exercise25_ComputationalNumberTheory`](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter2/section4/Exercise25_ComputationalNumberTheory.java)'s `main()`:
```
public static void main(String[] args) {
        Exercise25_ComputationalNumberTheory computationalNumberTheory = new Exercise25_ComputationalNumberTheory();

        int n = 1000; //1000000;
        PriorityQueue<ValueForComputation> priorityQueue = new PriorityQueue<>(n + 1, PriorityQueue.Orientation.MIN);

        ...
    }
```
the size of the  `PriorityQueue` add 1, but the  `PriorityQueue`'s constructor already do this :
```
   public PriorityQueue(int size, Orientation orientation) {
        priorityQueue = (Key[]) new Comparable[size + 1];
        this.orientation = orientation;
    }
```
So, maybe inside the `Exercise25_ComputationalNumberTheory`'s `main()`, we don't need add 1?

**Comment by reneargento** [comment]
It seems that adding 1 is not needed in this case, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/70c41d3a52d8001d9b4b6dadd26ebf569bafdf51
Thanks for the contribution!
