### ISSUE TITLE
An error in Readme.md

### ISSUE THREAD

**Issue by iSMohapatra** [reneargento/algorithms-sedgewick-wayne#220]
Hey bud,

Thanks for the work. I thought of pointing out a type. 
'The exercises answered on this repository are based on the seventh printing of the book (of September 2015). Other printings of the book (especially older ones) may have exercises in a slightly different order.'

It would be great if you could change it to the fourth edition of the book.

Cheers!

**Comment by reneargento** [comment]
The first line of the readme file mentions it is the fourth edition of the book.
Notice that editions and printings are different things. This repository is based on the 4th edition of the book and its 7th printing.
