### ISSUE TITLE
exercise 3.1.6 has better answer

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#221]
3.1.6

```
Give the number of calls to put() and get() issued by FrequencyCounter, as a
function of the number W of words and the number D of distinct words in the input.
```

I think we can give answer using W and D only

The related logic of `FrequencyCounter` is 
```
      if (st.contains(word)) {
        st.put(word, st.get(word) + 1);
      }
      else {
        st.put(word, 1);
      }
```

That means for each word `put()` Is called once, to either put `1` or put incremented number.
But the first occurrence of a distinct word does not invoke `get()`. Only subsequent calls do.

Therefore, I think better answer is 
```
number of calls to put(): W
number of calls to get(): W - D
```

**Comment by reneargento** [comment]
Looks good, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/788ea4719c21e806ca36f59dd84b2cb5a08b21f0
Thanks for the contribution!
