### ISSUE TITLE
exercise 3.1.20 proof is incomplete

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#223]
The hint from the question states 
```
Hint : Start by showing that C(N) is monotonic: C(N)   C(N+1) for all N > 0.
```

So I think it is important to prove ` C(N) is monotonic:` but in your [answer](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section1/Exercise20.txt)  it is taken as a given
```
C(N) is monotonic: C(N) <= C(N + 1) for all N > 0.
```

Here is my prove of the monotonicity of `C(N)` using induction.

1. It is trivial to prove
```
C(1) = 1
C(2) = 1 or 2
```

Thus we have 
```
C(1) <= C(2)
```

Assume for all N=[0, K]
```
C(N+1) >= C(N)
```

Thus we have 
```
C(K+1) <= C(K)
```

Looking at  the starting `mid`, which when `lo=0` and `hi=N`
```
int mid =lo + (hi - lo) / 2 = hi/2
```

Let's use `L` to represent size of left half, and `R`for size of right half, and `mid` element has size `1`

When `N=K+1` Total size is `L + 1 + R`

When N=K+2, 
```
int mid =lo + (hi - lo) / 2 = (hi+1)/2 = (N+1)/2
```

When N increment by 1 from `K+1` to `K+2`,the `mid` point remains either the same or shift to the right by 1. 

1. if `mid` remains same, then `L` remains same, and `R` is incremented by 1.  Since (R+1) <= K+1, we have
```
C(K+2) =   C(L) + 1 + C(R+1)
            >= C(L) + 1 + C(R) = C(K+1)
```

2. `mid` shift  to the right by 1 , then`L` is incremented by 1, and `R` remains same. Since (L+1) <= K+1, we have
```
C(K+2) =   C(L+1) + 1 + C(R)
            >= C(L) + 1 + C(R) = C(K+1)
```

How have proved that
```
Given C(K+1)>=C(K) it is also true C(K+2)>=C(K+1).
```

Q.E.D

**Comment by reneargento** [comment]
Looks good, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/dbafb107cc3464818ab9379ff0165eee59963ceb
Thanks!
