### ISSUE TITLE
exercise 3.1.26 can be simplified

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#224]
In [exercise 3.1.26](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section1/Exercise26_FrequencyCountDictionary.java)

I think these simplifications can be achieved.

1) `Word` is like a row/record in database, and `wordValue` is the _primary key_. I don't think we need to implement `Word` as comparable, we just need the _primary key_ to be comparable, and in this case, the primary key is String and is inherently comparable.

As such `Word` can be simplified as 

```
    private class Word {

        private String wordValue;
        private int frequency;
        private int orderFoundInFile;

        private Word(String wordValue) {
            this.wordValue = wordValue;
        }
    }
```

2) When constructing a symbol table `binarySearchSymbolTable`, again we consider the `wordValue` as the primary key and thus use that naturally as the key for symbol table. The value of the symbol table is the `Word` object. This maps to the same ideal that a _primary key_ indexes the _row_/record in a database table. For these reasons I recommend defending symbol table as type `<String, Word>`

```
        BinarySearchSymbolTable<String, Word> binarySearchSymbolTable = new BinarySearchSymbolTable<>();
```

3) At the end, since we are using the comparator with `Arrays.sort()`, we do not need to make 2 copies of the _words_, instead we can just to make one copy and sort it twice with different comparators.

```
        Word[] wordsInSymbolTable = new Word[binarySearchSymbolTable.size()];

        Arrays.sort(wordsInSymbolTable, new Comparator<Word>() {
            @Override
            public int compare(Word word1, Word word2) {
                return word1.frequency - word2.frequency;
            }
        });
        Arrays.sort(wordsInSymbolTable, new Comparator<Word>() {
            @Override
            public int compare(Word word1, Word word2) {
                return word1.orderFoundInFile - word2.orderFoundInFile;
            }
        });
```

Just my two cents...

**Comment by reneargento** [comment]
Thanks for the contribution and the PR!
