### ISSUE TITLE
exercise 3.2.13 has redundant null check

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#228]
In [3.2.13 line 64 second while() loop](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/4c95374eb011668b15d5f5e5e199110b7d59b40d/src/chapter3/section2/Exercise13.java#L65) the 
```
65           while (current != null) {

                int compare = key.compareTo(current.key);
                current.size = current.size + 1;
```

It is trivial to show that the `current != null` is always true and the two `break` statements are the only way out of the loop.   Thus the null check is redundant and it is same as
```
65           while (true) {

```

**Comment by reneargento** [comment]
I added this and some other minor improvements in the commit https://github.com/reneargento/algorithms-sedgewick-wayne/commit/ca091990396d9e23bc5c7284aee07114b0355052
Thanks!
