### ISSUE TITLE
exercise 3.2.14 has some minor improvements

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#229]
Please note your code runs just fine. These are the finer improvements when checking my implementations with yours.

in [exercise 3.2.14](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section2/Exercise14.java)

`min()` and `max` implementation has __unreachable__ statements, and can be simplified
```
 public Key min() {
            ...
            return null; // this is unreachable because as long as 'root' is not null, there is always a min key.
}
```

A simplified version is 
```
        public Key min() {
            if (root == null) {
                throw new NoSuchElementException("Empty binary search tree");
            }

            Node current = root;

            while (current.left != null) {
                current = current.left;
            }

            return current.key;
```
_Same_ issue exist with `max()`

For `min(Node node)` it is simpler to just check null once at the beginning 
```
        public Node min(Node current) {
            if (current == null) {
                return null;
            }

            while (current.left != null) {
                current = current.left;
            }

            return current;
        }
```

**Comment by faame** [comment]
changes made to PR #227 [this revision|https://github.com/reneargento/algorithms-sedgewick-wayne/pull/227/commits/4851c6f1c81f9b27d063e5b317da9aabcfabfd8f]

**Comment by reneargento** [comment]
PR merged, thanks!
