### ISSUE TITLE
Question about 1.3.48

### ISSUE THREAD

**Issue by shimshahs** [reneargento/algorithms-sedgewick-wayne#23]
algorithms-sedgewick-wayne/src/chapter1/section3/Exercise48_TwoStacksDeque.java

The problem asks to implement two stacks with a single Deque. Unless I am misunderstanding something here, the solution seems to be using 2 Stacks and implementing a Deque.

**Comment by reneargento** [comment]
You are right, it was implemented on the other way around.
I fixed it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/6efa43107e6ad2fb9b65316d4bc6961f5f28d5ff
Thanks for the contribution!

**Comment by reneargento** [comment]
I'm closing this issue as it has been fixed and the last comment was made over a year ago.
