### ISSUE TITLE
exercise 3.2.23 has a small error

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#230]
[exercise 3.2.23](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section2/Exercise23.txt) counter example is wrong (maybe an accidental typo)

The final section 
```
2- Delete B, then A
    A
      D
     C  

    D
     C 
```
should be
```
2- Delete B, then A
    A
      D
     C  

    D
   C  
```

**Comment by reneargento** [comment]
Fixed here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/4950f1ee6bbd9e2674aecc1a4d9d850f19e960fe
Thanks!
