### ISSUE TITLE
exercise 3.3.3 has incorrect answer

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#231]
In [exercise 3.3.3](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter2/section3/Exercise3.txt) The sequence provided __does not__ result in a 2-3 search tree of height 1.
I think the initial error is here
```
Insertion order: E M R X A C H S

Insert E     E

Insert M     E
              M
```
when inserting `M` it inserts into existing two node, forming a 3 node. thus it is
```
Insert E     E

Insert M     EM
```

Continue the drawing, the provided sequence `E M R X A C H S` would result in a tree of height-2
```
      M
  C      S
A  EH   R X
```

One correct sequence is
```
E A M X R C H S
```

**Comment by reneargento** [comment]
Updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/da6854724e0adb6a387a467aae85cfb2596fde90
Thanks!
