### ISSUE TITLE
The solution of exercise 4.3.15 seems wrong.

### ISSUE THREAD

**Issue by YRFT** [reneargento/algorithms-sedgewick-wayne#232]
The new edge and the old MST must form a cycle. We must remove the max-weight edge in the cycle regardless of whether the new edge is the min-weight edge.

For example, the current MST is:

```
     (4)
1 --------- 2
            |
            | (3)
            |
3 ----------4
     (1)
```

If we add an edge `1-3 (weight: 2)`, the `1-2(weight: 4)` should be removed. But according to the current solution, the newly added edge will be removed which is wrong.

**Comment by reneargento** [comment]
You are right, we should always remove the max-weight edge.
Exercise updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/455c8de64d270b3702e5b17e2084a20408baddb0
Thanks!
