### ISSUE TITLE
exercise 3.4.4 can be more efficient

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#233]
In [exercise 3.4.4](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section4/Exercise4.java), 

1)  alphabet is __bounded__ at 26: since keys are alphabet and keys must be unique, we can safely say that max size of key set is 26 (all upper cases).
2) `M` is  upper __bounded__  at 26: since we know at least there is one solution with `a=1, M=26` where there is no collisions. Only in this case M may not be minimum.  but `M=26` should be the upper bound.
3) `M` is lower __bounded__ at `letterValues.length` because when there is no collision, this minimum size gives a 100% load factor.
3) `a` is  __bounded__  at `M`. In any solution, `a` cannot be multiple of `M`, so let's assume `a` is larger than `m` and expressed as `a=jM+x` where `x < M`, then 
```
(a*k)%M = ((j*M + x) * k) % M =( jM*k + x * k) % M = (x * k) % M, where x < M
``` 
Thus we only need to consider case `a < M`

With the 4 bounds explained, the loop

```
        for(int m = 2; m <= 100; m++) {
            for(int a = 1; a <= 1000; a++) {
            ...
            }
        }
```

becomes 
```
        for(int m = letterValues; m <= 26; m++) {
            for(int a = 1; a < m; a++) {
            ...
            }
        }

```

**Comment by reneargento** [comment]
Good analysis. I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/3d601a65b1a584247dfcfae11f24f7a87d35be20
Thanks!
