### ISSUE TITLE
exercise 3.4.19 should not sort keys

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#235]
In [exercise 3.4.19](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section4/Exercise19.java) the implementation of `keys()` tries to sort the keys before returning.

From design pers-perspective this is not a good practice.
1) hash table does not require `Key` to be `Comparable` 
2) does not have any ordering information.  This means that doing `sort()` in hash table implementation is no more efficient than doing the sorting outside hash table (i.e. at client code).

The following code won't work well if some keys are `Comparable` and some are not, which is possible if the types of keys are from two child classes of a common parent class, and one child class is Comparable while the other is not.
```
            if (!keys.isEmpty() && keys.peek() instanceof Comparable) {
```

For above reasons, we should leave the sort() to client code.

**Comment by reneargento** [comment]
Good point, exercise updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/b3d4bacd071e33821dec6da7788b62cc3660943c
Thanks!
