### ISSUE TITLE
exercise 3.4.21 missed one implementation

### ISSUE THREAD

**Issue by faame** [reneargento/algorithms-sedgewick-wayne#237]
[exercise 3.4.21](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter3/section4/Exercise21.java) is not the intended answer.

The answer is to follow the analysis in _proposition M_ on page 473, as hinted by this statement in the "Discussion" section:
```
Discussion: We compute....Thus, given a table, we can quickly compute the average cost o search miss in that table (see EXERCISE 3.4.21)."
```
 The correct implementation should use equation 
```
1 +  N/(2*M) + sum(pow(s[i], 2))/(2*M) for all clusters,  s[I] is the size of the each cluster in table 
```

I submitted PR #238 to add the extra implementation

**Comment by reneargento** [comment]
Thanks for the contribution.
The computation of the average cost of search misses by load factor and by cluster sizes seem to be equivalent, but we can have both methods in the answer.
