### ISSUE TITLE
Maybe there something wrong in exercise 4.1.14

### ISSUE THREAD

**Issue by lemonadeseason** [reneargento/algorithms-sedgewick-wayne#24]
0 (source)
 / \
1 - 2
You said that "Using a stack the distance from 0 to 1 will be 1 and from 0 to 2 will be 2.
Using a queue, the distance from 0 to both 1 and 2 will be 1."

but code in dfs just add all vertices adjacent to 0,so 1,2 will be added to stack.At the same time,calculate distTo[1] and distTo[2],which will be 1 rather than 2.
Things can be different in other cases.like this one:
          0 (source)
            / \
          1 - 2
             \   \
               \    3
                  \   \
                      4      
Shortest distance from root to 4 is 2(0->1->2),but we may get a wrong answer 0->2->3->4.

**Comment by reneargento** [comment]
You are right, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/730aa9eefe777d28db0a2508e1bce77ff00bffc9
Thanks for the contribution!

**Comment by reneargento** [comment]
I'm closing this issue as it has been fixed and the last comment was made over a year ago.
