### ISSUE TITLE
Correction to Question 4.4.9

### ISSUE THREAD

**Issue by GenevaS** [reneargento/algorithms-sedgewick-wayne#242]
I agree with the logic of the solution, but I believe there is an execution error. The error in the table is not the distance between Norwich and New London. It is the distance between Norwich and Westerly.

The distance of 101 between Norwich and Westerly is the sum of the paths from Norwich to Providence (distance = 48) and Providence to Westerly (distance = 53). By removing the direct path worth 101, we can see that there is a shorter path through New London with a distance of 30 (distance = 12 + 18). 

```
            Providence  Westerly  New London  Norwich
Providence       -         53         54        48
Westerly         53         -         18        30    
New London       54        18          -        12
Norwich          48        30         12         -

              Providence                   Westerly                      New London                     Norwich
Providence       -                  Providence->Westerly             Providence->New London    Providence->Norwich
Westerly    Westerly->Providence              -                      Westerly->New London      Westerly->New London->Norwich
New London  New London->Providence  New London->Westerly                       -               New London->Norwich
Norwich     Norwich->Providence     Norwich->New London->Westerly    Norwich->New London                 -
```

**Comment by reneargento** [comment]
Fixing the distance between Norwich and Westerly in this case makes sense.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/999bfe4b815bff0fbcc52d2366537bfa588c022e
Thanks for the contribution!
