### ISSUE TITLE
Q. 5.1.8: Empty Subarrays/Unused Extra Space in 3-way String Quicksort

### ISSUE THREAD

**Issue by GenevaS** [reneargento/algorithms-sedgewick-wayne#244]
I believe that the answer to this is `N+1`.

In the first pass, 3-way String Quicksort does have two empty partitions because every key is equal to the partitioning character. However, after this, the algorithm _does_ start putting elements in the partition for (key < partitionKey): the strings that have no characters left. 

For example, the second pass will populate the subarrays like this: ['a'], ['aa', 'aaa', ...], []. The algorithm will not do anything with the ['a'] subarray because it only has one element, so the number of characters examined does not change.

If we are counting only the _empty_ subarrays, then we get `2 + sum of 1 from 2 to N = 2 + (N - 1) = N + 1`.

**Comment by reneargento** [comment]
It seems that when all keys have the same characters (even with different quantities), there will always be two empty subarrays.
I did some debugging to check this case with an array consisting of [ "a", "aa", "aaa" ]

There are two cases that can happen during each pass of the sort:
1- The pivot is equal to `a`, where all characters compared to it will be equal, leading to two empty subarrays: the smaller and the higher element subarrays.
2- The pivot is equal to `-1`, where all characters compared to it will be higher, leading to two empty subarrays: the smaller and the equal element subarrays.

**Comment by GenevaS** [comment]
I think I have a solution: it's not the empty subarrays that are the issue, it's the number of copies we make of the array due to recursion. At each iteration, we make an exact copy of the array without one entry. Since we know that the array is already sorted, this means that we make copies of `N` elements, then `N-1` elements, and so on until we make a copy of the array with a single element in it. We end up using what we know to be `N(N+1)/2` space we don't need to.

**Comment by reneargento** [comment]
But in the algorithm we are always passing (and copying through the recursion) the entire array. We just update the `low` and `high` indexes.
