### ISSUE TITLE
Q. 5.1.10 Worst Case for 3-way String Quicksort

### ISSUE THREAD

**Issue by GenevaS** [reneargento/algorithms-sedgewick-wayne#245]
[Reference Issue #153]

I believe the worst case is `O(w*N*R)`. We get this from a recurrence relation `T(w)`.

First, the base case `T(1)` (e.g. 'a', 'b', 'c', `R = 3`). Thanks to @dragon-dreamer 's solution, the worst case for strings of length 1 is when we only remove one string from the list every pass. If we take `N = R^w`, this becomes `Sum[i=0..R] i = R(R+1)/2`.

To build the worst case for string of length 2 (`T(2)`), we take each string from `T(1)` and append it to the end of each character in `R`. So if we had single character strings 'a', 'b', 'c', with `R = 3`, our two character list is: 'aa', 'ab', 'ac', 'ba', 'bb', 'bc', 'ca', 'cb', 'cc'. 

Here, we can see that the list can be split into `R` groups: one for each character in `R` appended to every string of length `w-1`. When quicksort does its partitioning, it will put all strings starting with 'a' in the same partition, then do what it did for `T(1)` because removing the first character 'a' from those strings gives us 'a', 'b', 'c' again. The same thing happens for strings starting with 'b' and 'c'. So, for `R=3`, it will check `3R + 2R + R` characters in the first position of the string. Then it needs to check the second string characters in each group of `R`.

We can see that the list can be split into `R` groups: one for each character in `R` appended to every string of length `w-1`. For some value `w`, quicksort will remove `R` strings from the list with each partition. It will then need to check `R*T(w-1)` more characters for each of those groups. This gives us the recurrence `T(w) = (R^(w-1)*Sum[i=0..R] R-i) + R*T(w-1)`, which simplifies to:
```
T(w) = R^(w+1) + R^w   + R*T(w-1)
      ---------------
            2
```
Solving the recurrence gives us: 
```
T(w) = w*(R^w)*(R+1)
      ---------------
            2
```

Substituting `N=R^w`:
```
T(w) = w*N*(R+1)
      ----------
          2
```

Which is `O(w*N*R)`.

**Comment by reneargento** [comment]
This looks like an improvement over the previous solutions, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d776b841defa1f26a4f00517c40d349117821d11
Thanks for the contribution!
