### ISSUE TITLE
In Exercise 1.4.33 answer for double[][] memory requirement seems wrong

### ISSUE THREAD

**Issue by Andrew-Goo** [reneargento/algorithms-sedgewick-wayne#247]
For line 39: Amount of memory needed: 8 + 4 + 4M + ***12*** + 8MN = 8MN + 4M + 24 bytes

I think it should be 8 + 4 + 4M + ***12M*** + 8MN = 8MN + 16M + 12 bytes

Is it possible that M was left out by accident?

**Comment by reneargento** [comment]
Yep, it was left out by accident.
It is now fixed in: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/cb996468d8165175e2c79bf3037a37b6eb6acb95
Thanks for the contribution!
