### ISSUE TITLE
In exercise 2.1.30, non-integer t-value should be better

### ISSUE THREAD

**Issue by suyj-git** [reneargento/algorithms-sedgewick-wayne#249]
Hi, @reneargento. Thanks for this great work!

In the exercise, `t`-value could be non-integer and I find you have not tested it yet. Thus, I have tested `t`-value ranging from 2 to 16 by a step of 0.1.

Please find the distributions of time cost (in microseconds) versus `t` below:
![time_vs_t](https://user-images.githubusercontent.com/14037313/167259993-8a9aa7aa-f8d5-4c30-af0a-a5af200e7a6b.png)

As you can see, time costs of integer `t`-values are usually worse than non-integer. And the best three `t`-values are here:
```
7.1 : 87798 microseconds
1, 7, 50, 357, 2541, 18042, 128100, 909512, 6457535, 45848500, 325524355,

7.2 : 89656 microseconds
1, 7, 51, 373, 2687, 19349, 139314, 1003061, 7222041, 51998697, 374390624,

5.4 : 92299 microseconds
1, 5, 29, 157, 850, 4591, 24794, 133892, 723019, 3904305, 21083251, 113849560,
```

The phenomena is very curious. My naïve justification for this phenomena will be that if `t`-value are integer, there will be a moderate number of expected useless comparisons when `h`-sorting with each element of the increment sequence. For example, after `64`-sorting the random array of 10^6, there will be 10^6/64 = 15625 elements already in place but comparisons between these elements are still carried out in `16`-sorting. These elements are less likely to be in final place because they stay the same sequences as in `64`-sorting. It is not the case for non-integer `t`-value, which makes some elements having a chance to be in a different sequence in next `h`-sorting.

Since I am writing the exercises in C++, I can't make a pull request to let you directly reproduce the results.  You can copy the best three increment sequence above and test them in your code to see if it is the case.

Best regrads,
Yangjie.

**Comment by reneargento** [comment]
Thanks for the contribution!
Your idea for why non-integer `t`-values generate better runtimes makes sense.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/34ea412fab8e5a97b5176a470d88f02870429cc3
In my case, running shellsort with `t`-values from 2 to 16 and incrementing by 0.1, I got the best results with the values 2.10, 2.30 and 2.20.

**Comment by suyj-git** [comment]
Thanks for that. I am going to close the issues.
