### ISSUE TITLE
Exercise 2.1.10

### ISSUE THREAD

**Issue by jaeheonshim** [reneargento/algorithms-sedgewick-wayne#254]
I think it's also worth mentioning that in shell sort, h-sorting eventually reaches a point where the increment is 1. Selection sort with an increment of 1 is well... just selection sort, so by using selection sort for h-sorting you'll end up doing regular selection sort on top of a bunch of unnecessary work.

**Comment by reneargento** [comment]
That is also a valid reason.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/2d2397514c9e9cbf817313544f9c748242d9407e
Thanks for the contribution!
