### ISSUE TITLE
Exercise26_LazyDeleteLinearProbing

### ISSUE THREAD

**Issue by WmWyn** [reneargento/algorithms-sedgewick-wayne#255]
let size=8 and have 2 keys, then call method: put(key1,value1) delete(key1) put(key2,value2) delete(key2) , now tombstoneItemCount=2  and keySize=2,  keysSize  + tombstoneItemCount = 2 + 2 >=4 = size / 2。
![image](https://user-images.githubusercontent.com/16416113/171191737-51769a57-58f3-4d32-ba77-865ca0f895f9.png)

now call put() method will trigger resize(16), after resize, size=16 keysSize=2 tombstoneItemCount=0 。 keysSize = 2 <= 16/8=size/8 . so call delete() will trigger resize(8)

![image](https://user-images.githubusercontent.com/16416113/171192961-9ca2b9b9-3028-4a5d-ad6b-b02fb552b0e1.png)

**Comment by reneargento** [comment]
That is correct, but at that point (after the final `resize(8)`), we have `tombstoneItemCount` = 0.
This means that the next put() or delete() operation will not trigger a resize.
Considering the number of operations we had in this example (2 puts for the two initial keys and then 3 more put() and 3 more delete()), this is 2 resizes for 8 operations which doesn't look so bad.
