### ISSUE TITLE
1.4.13 FixedCapacityStackOfStrings with capacity C and N entries

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#256]
A reference to a string array (`String[]`) uses 8 bytes, which should be taken into account.

**Comment by reneargento** [comment]
Thanks for the contribution, I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/a30445ced2e66ace5cebd198cd7f4852d49996d0
