### ISSUE TITLE
1.4.15 threeSumFaster2 may also has some mistakes

### ISSUE THREAD

**Issue by davisrain** [reneargento/algorithms-sedgewick-wayne#258]
public static int threeSumFaster1(int[] a) {
        int count = 0;

        Arrays.sort(a);
        if ((a[0] < 0 && a[a.length - 1] < 0) || (a[0] > 0 && a[a.length - 1] > 0))
            return count;

        int num = countZeroNum(a);
        count += num * (num - 1) * (num - 2) / 6;

        Loop: for (int i = 0; i < a.length; i++) {
            int start = i + 1;
            int end = a.length - 1;
            while (start < end) {
                if (a[i] + a[start] + a[end] > 0) {
                    end--;
                } else if (a[i] + a[start] + a[end] < 0) {
                    start++;
                } else {
                    if (a[start] == 0 && a[end] == 0) {
                        continue Loop;
                    }

                    // there is a situation, for example, part of array is -2 0 1 1 1 1 2.
                    // at the beginning, i pointer at -2, start pointer at 0, end pointer at 2.
                    // then start++ end--, starter pointer at first 1, end pointer at last 1.
                    // start pointer continual ++ until (start + 1 < end).
                    // equalStartElements = 3 and equalEndElements = 1 at this time.
                    // so count += 1*3, but the correct method to calculate combinations of 1 is (4 * 3 / 2 = 6)
                    if (a[start] == a[end]) {
                        num = end - start + 1;
                        count += num * (num - 1) / 2;
                        continue Loop;
                    }

                    int startElement = a[start];
                    int equalStartElements = 1;

                    while (start + 1 < end && a[start + 1] == startElement) {
                        start++;
                        equalStartElements++;
                    }

                    int endElement = a[end];
                    int equalEndElements = 1;

                    while (end - 1 > start && a[end - 1] == endElement) {
                        end--;
                        equalEndElements++;
                    }

                    count += equalStartElements * equalEndElements;

                    start++;
                    end--;
                }
            }
        }
        return count;
    }

**Comment by reneargento** [comment]
I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/4fc314bbd01856b85fd265eb52ba98c79bd68f96 
Thanks for the contribution!
