### ISSUE TITLE
2.1.30 Rounding error in floating-point arithmetic

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#259]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/c3502bcb2eb13763b86b949857128324a3058a2f/src/chapter2/section1/Exercise30_GeometricIncrements.java#L45

In the above `for` loop, the variable `tValue` is added with 0.1 in each iteration. Because 0.1 cannot be accurately represented by floating-point numbers, each addition may introduce a new rounding error, as you can see in the following example.

```java
for (double t = 2; t <= 5; t += 0.1) {
    StdOut.println(t);
}
```

```java
2.0
2.1
2.2
2.3000000000000003
2.4000000000000004
2.5000000000000004
2.6000000000000005
2.7000000000000006
2.8000000000000007
2.900000000000001
3.000000000000001
3.100000000000001
3.200000000000001
3.300000000000001
3.4000000000000012
3.5000000000000013
3.6000000000000014
3.7000000000000015
3.8000000000000016
3.9000000000000017
4.000000000000002
4.100000000000001
4.200000000000001
4.300000000000001
4.4
4.5
4.6
4.699999999999999
4.799999999999999
4.899999999999999
4.999999999999998  // Supposed to be 5.0
```

This behavior may break the function [`generateIncrementSequence`](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/c3502bcb2eb13763b86b949857128324a3058a2f/src/chapter2/section1/Exercise30_GeometricIncrements.java#L61), and lead to wrong results. For example, if we call it with 4.999999999999998 instead of 5.0, we get the increment sequence as follows:

```java
[390624, 78124, 15624, 3124, 624, 124, 24, 4, 1]
```

while the desired increment sequence is 

```java
[390625, 78125, 15625, 3125, 625, 125, 25, 5, 1]
```

One possible solution is simple, as shown by the following code. Instead of performing inexact floating-point addition, we could get the correct number within acceptable precision by a division of two integers.

```java
for (int i = 20; i <= 50; ++i) {
    double t = i / 10.0;
    StdOut.println(t);
}
```

```java
2.0
2.1
2.2
2.3
2.4
2.5
2.6
2.7
2.8
2.9
3.0
3.1
3.2
3.3
3.4
3.5
3.6
3.7
3.8
3.9
4.0
4.1
4.2
4.3
4.4
4.5
4.6
4.7
4.8
4.9
5.0
```

**Comment by reneargento** [comment]
Good point, it is now updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/277eef1ae06c30c919d724529b81c792eb7b63b0
Thanks!
