### ISSUE TITLE
2.4.7 where kth largest can appear in a heap

### ISSUE THREAD

**Issue by oeyh** [reneargento/algorithms-sedgewick-wayne#26]
4th largest can also appear on position 2 or 3 when 3rd largest is child of 2nd largest.
So in summary, 4th largest can appear on position 2 to 15, cannot appear on 1 and 16-31.

**Comment by reneargento** [comment]
Nice catch. 
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/b8d2c20c1651343ae68e306b3473db9b058dc221
Thanks for the contribution!

**Comment by oeyh** [comment]
Thanks! 

This repo is very helpful to me. Glad that I can contribute.
