### ISSUE TITLE
2.2.17 Natural mergesort for linked list

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#261]
It seems to be the same problem as in #101. The algorithm always merges the first sorted subarray with the second sorted subarray, resulting in the time complexity of $O(N^2)$.

**Comment by reneargento** [comment]
Yes, the natural mergesort for linked lists had the same issue.
It is updated now: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/66b23a36cefae5b11b83ac09efece3acbce106ef
Thanks!
