### ISSUE TITLE
2.2.29 The number of passes in natural mergesort

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#262]
> **2.2.29** _Natural mergesort_. Determine empirically the number of passes needed in a natural mergesort (see Exercise 2.2.16) for random `Long` keys with $N=10^3, 10^6$, and $10^9$. _Hint_: You do not need to implement a sort (or even generate full 64-bit keys) to complete this exercise.

According to the exercise description, we need to determine the number of times to traverse (pass) the entire array in the natural mergesort. To be clear, look at the following example from [Wikipedia](https://en.wikipedia.org/wiki/Merge_sort#Natural_merge_sort) for which natural mergesort needs 3 passes to sort it.

```
Start          :  3  4  2  1  7  5  8  9  0  6
Select runs    : (3  4)(2)(1  7)(5  8  9)(0  6)
Merge (pass 1) : (2  3  4)(1  5  7  8  9)(0  6)
Merge (pass 2) : (1  2  3  4  5  7  8  9)(0  6)
Merge (pass 3) : (0  1  2  3  4  5  6  7  8  9)
```

In order to count the number of passes, we **do not** need to implement a complete natural mergesort, because we only need the number of indices between `lo` and `hi`. For the same example as above, the process is as follows.

```
Index          :  0  1  2  3  4  5  6  7  8  9
                  |  |  |  |  |  |  |  |  |  |
Start          :  3  4  2  1  7  5  8  9  0  6
Select runs    : (3  4)(2)(1  7)(5  8  9)(0  6)
                  |  |  |     |        |     |
lo             :  0  |  |     |        |     |
hi             :     |  |     |        |     9
n (4)          :     1  2     4        7

Merge (pass 1) : (2  3  4)(1  5  7  8  9)(0  6)
                        |              |
n (2)          :        2              7

Merge (pass 2) : (1  2  3  4  5  7  8  9)(0  6)
                                       |
n (1)          :                       7

Merge (pass 3) : (0  1  2  3  4  5  6  7  8  9)

n (0)          : Done (3 passes total)
```

The corresponding Java program is as follows:

```java
/* Count the number of passes needed in a natural mergesort for a[]. */
static <T extends Comparable<T>> int count(T[] a) {
    int n = 0; // The number of indices between lo and hi.
    for (int hi = a.length - 1, i = find(a, 0, hi); i != hi; i = find(a, i + 1, hi)) {
        ++n;
    }
    if (n == 0) {
        /* 1 pass is needed for sorted input. */
        return 1;
    }
    for (int cnt = 1;; ++cnt) {
        if ((n /= 2) == 0) {
            return cnt;
        }
    }
}

/* Find the last index of the first sorted subarray in a[lo...hi]. */
static <T extends Comparable<T>> int find(T[] a, int lo, int hi) {
    T prev = a[lo];
    for (++lo; lo <= hi; ++lo) {
        T curr = a[lo];
        if (curr.compareTo(prev) < 0) {
            return lo - 1;
        }
        prev = curr;
    }
    return hi;
}
```

After running the above program with $N = 10, 10^2, 10^3, 10^4, 10^5, 10^6$ and repeating the experiment 100 times, I got the following results.

```java
        N    Passes
       10       2.9
      100       6.0
    1,000       9.1
   10,000      13.0
  100,000      16.0
1,000,000      19.0
```

It is not difficult to see that the number of passes needed is equal to $⌊lg(N)⌋$. Thus, I believe that for $N=10^9$, the number of passes is $⌊lg(10^9)⌋ = 29$.

**Comment by reneargento** [comment]
That makes sense. On every pass natural mergesort merges all pairs of unsorted sub-arrays. In the worst case there are N / 2 unsorted sub-array pairs on the first pass, then N / 4 pairs on the next pass, and so on, leading to lg(N) passes.
Exercise updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/c87176d57f61894b15b9ff022ec86b4d22cfc90e Thanks!
Thanks!

**Comment by reneargento** [comment]
That makes sense, it is now updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/a30b6fbed6ce35634d722269d126206a6b6c12a9
