### ISSUE TITLE
2.5.6 The recursive version of `select()`

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#265]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/a30b6fbed6ce35634d722269d126206a6b6c12a9/src/chapter2/section5/Exercise6.java#L39

A typo: `array[low]` should be returned in the above line instead of `low`.

**Comment by reneargento** [comment]
Updated: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/f083c3fe3c9f4d3b03c94b6d940b9a3cede58809
Thanks!
