### ISSUE TITLE
2.5.7 The number of compares required by `select()`

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#266]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/a30b6fbed6ce35634d722269d126206a6b6c12a9/src/chapter2/section5/Exercise7.txt#L3

A typo: `2N * ln` => `2 * lnN`.

**Comment by reneargento** [comment]
Updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/07ceb17197611712d299ee9b43afa403dc08231c
Thanks!
