### ISSUE TITLE
4.3.24 - Reverse-delete algorithm - Time complexity

### ISSUE THREAD

**Issue by kyzooghost** [reneargento/algorithms-sedgewick-wayne#271]
Thank you for the epic work you've put into this repo.

I was doing 4.3.24 and I believe that the time complexity of the reverse-delete algorithm should be O(E^2), as opposed to O(E lg E) that you've written in https://github.com/reneargento/algorithms-sedgewick-wayne/blob/a30b6fbed6ce35634d722269d126206a6b6c12a9/src/chapter4/section3/Exercise24_ReverseDeleteAlgorithm.txt#L12

Focusing on this code block in https://github.com/reneargento/algorithms-sedgewick-wayne/blob/a30b6fbed6ce35634d722269d126206a6b6c12a9/src/chapter4/section3/Exercise24_ReverseDeleteAlgorithm.java#L35-L44

```java
        // Iterating over each edge
        for (Edge edge : edges) {
            edgeWeightedGraph.deleteEdge(edge);
           
            // ConnectedComponentsEdgeWeightedGraph performs a DFS - O(V + E)
            ConnectedComponentsEdgeWeightedGraph connectedComponentsEdgeWeightedGraph =
                    new ConnectedComponentsEdgeWeightedGraph(edgeWeightedGraph);
            if (connectedComponentsEdgeWeightedGraph.count() > 1) {
                edgeWeightedGraph.addEdge(edge);
            }
        }
```

The algorithm performs a DFS for each Edge => O(E+V) performed E times => ~O(E^2)

**Comment by reneargento** [comment]
I'm happy to hear the repository is being useful to you!

You are correct in saying that the time complexity of the `minimumSpanningTreeWithReverseDelete()` algorithm is `O(E^2)` - there is a comment mentioning that on top of the method too.
But notice that the question asks about the order of growth of the number of edge-weight compares. On the DFS there are no edge-weight compares. We only have these comparisons during the edges sort.

So while the algorithm runs with time complexity `O(E^2)`, the order of growth of the number of edge-weight compares is `O(E lg E)`.
