### ISSUE TITLE
4.3.33 - Time complexity

### ISSUE THREAD

**Issue by kyzooghost** [reneargento/algorithms-sedgewick-wayne#272]
Querying whether the time complexity of the `check()` method is O(V * V * lg V) as opposed to O(V * E)

https://github.com/reneargento/algorithms-sedgewick-wayne/blob/a30b6fbed6ce35634d722269d126206a6b6c12a9/src/chapter4/section3/Exercise33_Certification.java#L35-L63

```java
        // Iterating over each edge in MST in the outer loop - there are V - 1 edges in the MST.
        for (Edge edgeInMST : proposedMinimumSpanningTree) {
            unionFind = new UnionFind(edgeWeightedGraph.vertices());

            // Iterating over each edge in the MST in the inner loop.
            for (Edge edge : proposedMinimumSpanningTree) {
                if (edge != edgeInMST) {
                    int vertex1 = edge.either();
                    int vertex2 = edge.other(vertex1);

                    // Each union operation has a time complexity of O (lg V) - we insert V elements into the UnionFind data structure.
                    unionFind.union(vertex1, vertex2);
                }
            }
       
            ...
```

UnionFind.union operation performed in V * V instances => O (V * V * lg V) time complexity bottleneck.

**Comment by reneargento** [comment]
The union operation on a UnionFind data structure using path compression and union-by-rank is `α(n)`, where `α` is the inverse Ackermann function.
So a more accurate order of growth for the running time might be `O(V^2 * α(n))`.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/c900c9f70557fa5d28b879baac1a6505c9c5017a
Thanks!
