### ISSUE TITLE
3.2.7 Calculating the internal path length of a `BST`

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#276]
Let `path(x)` be the internal path length of a `BST` rooted at `x`. We have `path(null) = 0` and

```java
path(x) = x.size - 1 + path(x.left) + path(x.right)
```

The `x.size - 1` term takes into account that the root contributes 1 to the path length of each of the other `x.size - 1` nodes in the tree. Based on this relationship, we could write a recursive method `avgCompares()`

```java
double avgCompares() {
    return root == null ? 0 : (double) path(root) / root.size + 1;
}

int path(Node x) {
    return x == null ? 0 : path(x.left) + path(x.right) + x.size - 1;
}
```

or a nonrecursive one which adds a field `path` to each node in the tree.

```java
// update the field `path` with
// `x.path = path(x.left) + path(x.right) + x.size - 1;`
// in put(), delete(), deleteMin(), and deleteMax().

double avgCompares() {
    return root == null ? 0 : (double) root.path / root.size + 1;
}

int path(Node x) {
    return x == null ? 0 : x.path;
}
```

**Comment by reneargento** [comment]
Updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/8bd3c7c7e54fdd523ede3645114fdf5dfc5f5ffe
Thanks for the contribution!
