### ISSUE TITLE
3.2.8 Calculating the internal path length of an optimal `BST`

### ISSUE THREAD

**Issue by ghost** [reneargento/algorithms-sedgewick-wayne#277]
Let's begin by a trival example. A optimal `BST` with 8 nodes is drawn as follows:

```
           Path Length  Number of Nodes
    ()          0              1
  ()  ()        1              2
 ()()()()       2              4
()              3              1
```

And its internal path length can be calculated as $1 * 2 + 2 * 4 + 3 * 1 = 13$. For an optimal `BST` with $N$ nodes, its height is $H = \lfloor log_2N \rfloor$, which also is the maximum path length in that tree. For nodes on the first $H$ levels, the total path length is

$$
\sum_{i = 1}^{H - 1}i * 2^i = (H - 2)2^H + 2
$$

For the last level, we have

$$
[N - (2^H - 1)]H = (N - 2^H + 1)H
$$

Add them up, we get

$$
(H - 2)2^H + 2 + (N - 2^H + 1)H = (N + 1)H - 2^{H + 1} + 2
$$

```java
// Compute the average number of compares needed 
// by a random search hit
// in an optimal `BST` with `n` nodes.
static double optCompares(int n) {
    if (n == 0) {
        return 0;
    }
    int h = (int) (Math.log(n) / Math.log(2)); // height
    return ((n + 1) * h - Math.pow(2, h + 1.0) + 2) / n + 1;
}
```

**Comment by reneargento** [comment]
Nice O(1) solution.
Updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/4ba0dbd7f1c20ec0c852bb820508f0866326eb10
Thanks!
