### ISSUE TITLE
longestPrefixOf() - Problem

### ISSUE THREAD

**Issue by joe63** [reneargento/algorithms-sedgewick-wayne#279]
refering to : chapter5/section2)/TernarySearchTrie.java -> longestPrefixOf()

Ich have tried to port your solutions to Python. The function  longestPrefixOf is in my Python-program not working correct.
I inserted : 
she
sells
sea
shells
by
the
sho
shore

the given samples by querring longestPrefixOf('shell') -> **she** and  longestPrefixOf('shellsort') -> **shells**  are ok .
but when I try  longestPrefixOf('short')  - > **short** which should be **sho**.

Does the Java-Program deliver the right result (sho)?

thanks in advise
BR Joe

**Comment by reneargento** [comment]
There was a bug on the `longestPrefixOf()` method.
It is now fixed: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/728031b59e1642a4bee120f0b9570b86ffa3f6fd
Thanks for reporting this issue!
