### ISSUE TITLE
Ex_1.4.26_3Collinearity   exceptional case: two different lines whihc have the same slope

### ISSUE THREAD

**Issue by amwsffkhtd** [reneargento/algorithms-sedgewick-wayne#286]
Hi, 

please try this case: two different lines whihc have the same slope, it doesn't work with the algorithm of Exercise26_3Collinearity .
for example:
```
  Point2D pointA = new Point2D(1, 1);
            Point2D pointB = new Point2D(2, 2);
            Point2D pointC = new Point2D(3, 3);
            Point2D pointD = new Point2D(0, 1);
            Point2D pointE = new Point2D(1, 2);
            Point2D pointF = new Point2D(2, 3);
            Point2D[] points2 = {pointA, pointB, pointC, pointD, pointE, pointF};
            int numberOfTriples1 = countTriples(points2); // expect 2, but the output is 16.
```

**Comment by reneargento** [comment]
Indeed, that implementation is not the correct way to compute collinear points.
After reviewing the question, I noticed that we are asked to explain a reduction from the 3-SUM problem to the 3-collinearity problem, and not to implement it.
Based on that, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d1e8922eb593d3925c308bb70221bc9be76a6b9b
Thanks for reporting the issue!
