### ISSUE TITLE
Ex 1.4.7 - k++ not considerd for tilde approximation

### ISSUE THREAD

**Issue by patentfox** [reneargento/algorithms-sedgewick-wayne#287]
Operation `k++` is also executed ~N<sup>3</sup>/6 times, so actual tilde approximation should be ~5N<sup>3</sup>/6

```java
public static int countTriples(int[] arr) {
  int count = 0;
  for (int i = 0; i < arr.length; ++i) {
    for (int j = i + 1; j < arr.length; ++j) {
      for (int k = j + 1; k < arr.length; ++k) {
        if (arr[i] + arr[j] + arr[k] == 0) {
          ++count;
        }
      }
    }
  }
  return count;
}
```

Similarly, for grand total, all the comparisons and arithmetic operations which are part of for loop statement should be considered.

[link](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter1/section4/Exercise7.txt)

**Comment by reneargento** [comment]
The exercise mentions a `cost model that counts arithmetic operations (and comparisons) involving the input numbers`.
The increments and comparisons of the for-loop variables are not directly related to the input numbers, so I think they shouldn’t be considered on that cost model.

**Comment by patentfox** [comment]
Thanks for response.
