### ISSUE TITLE
Ex 2.2.6, arrayAccessCount might be wrong 

### ISSUE THREAD

**Issue by ajfg93** [reneargento/algorithms-sedgewick-wayne#29]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/ef93b87326adec0b3ec5585e8cb5829b87ff13a7/src/chapter2/section2/Exercise6.java#L124-L156

When doing a compare `a[i] < aux[j]` or assignment `a[i] = aux[j]`, this should be counted as twice array access. 

So I think the `numberOfArrayAccesses ` increasement in order should be:
`numberOfArrayAccesses += 2; `
`numberOfArrayAccesses += 4;` 
`numberOfArrayAccesses += 2; `

And you can tell from *Proposition G* of Page 275, 6NlgN at most array access, and *4NlgN at least array access (approximately)* . So [Exercise6.txt](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter2/section2/Exercise6.txt) is wrong I think.

The result I get:

[MergeSortArrayTrial.xlsx](https://github.com/reneargento/algorithms-sedgewick-wayne/files/2708063/MergeSortArrayTrial.xlsx)

The result I get is very close to *6NlogN* and I think this should be correct.

related C++ code: 
https://gist.github.com/ajfg93/9b55b2f7b1de7f86ed7f9ac5c6c8a56a

**Comment by reneargento** [comment]
You're right, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/9142d91cc7eb617e33d38258e08bec8f03828c9f
Thanks for the contribution!
