### ISSUE TITLE
The solution of exercise 4.3.32, specified set, seems to be incorrect for me.

### ISSUE THREAD

**Issue by YRFT** [reneargento/algorithms-sedgewick-wayne#293]
We can create a new graph and set the weights of the specified edges to a new value less than any edge weights in the original graph. Then we can just run any MST algorithm to find an MST of the created graph and use this MST to find an MST containing all the specified edges of the original graph.

**Comment by reneargento** [comment]
Thanks for reporting, the solution in the repository was incorrect.
The solution you proposed works. I updated the repository with a solution that is a bit different but looks simpler to me. You can check it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/b4a3b35f8b476447e2a52a29e3796ebdde737648
Thanks for the contribution!

**Comment by YRFT** [comment]
OK, thanks.
