### ISSUE TITLE
object error

### ISSUE THREAD

**Issue by lhjl1065** [reneargento/algorithms-sedgewick-wayne#298]
On line 50 of Exercise23_CompareQFandQUErdosRenyi.java,The type used to create the unionfind object is incorrect, resulting in an inaccurate rate.

**Comment by reneargento** [comment]
Thanks for reporting this issue, the experiment results make more sense now.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/4a7916a987e57b2a6db458a82bbe4beedf73da05
