### ISSUE TITLE
4.2.29 Minor improvement suggestion

### ISSUE THREAD

**Issue by pharrukh** [reneargento/algorithms-sedgewick-wayne#302]
https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter4/section2/Exercise29_LCAInDAG.java

I would suggest two improvements.
First, you can move the responsibility to find sources to the Digraph by keeping an extra array of indegrees:
```ts
export class Digraph {
  // ...
  private indegreeList: number[] // <- this was added
  // ...

  addEdge(v: number, w: number): void {
    const error = `There are only ${this.V()} vertices, you are passing an edge [${v}, ${w}]`
    if (v >= this.V() || w >= this.V()) throw new Error(error)

    this.adjList[v].add(w)
    this.indegreeList[w]++ // <- this was added
    this.eCount++
  }

  indegree(v: number): number {
    return this.indegreeList[v]
  }

  sources(): number[] {
    const sources = []
    for (let v = 0; v < this.V(); v++) {
      if (this.indegree(v) === 0) sources.push(v)
    }
    return sources
  }
```

And the second improvement is in memory or in general about the number of calculations, as there could be only one LCA, we can just keep two variables for it and the height.

```ts
export function getLowestCommonAncestorForDAG(
  G: Digraph,
  v: number,
  w: number
): number {
  const cycleFinder = new DirectedCycle(G)
  if (cycleFinder.hasCycle())
    throw new Error("The digraph has a cycle, so it is not a DAG")

  const sources = G.sources()
  let lca = null
  let maxH = -Infinity
  const marked = Array.from({ length: G.V() }, () => false)

  function dfs(u: number, h: number = 0): void {
    const reachabilityFinder = new DirectedDFS(G, u)
    if (
      reachabilityFinder.marked(v) &&
      reachabilityFinder.marked(w) &&
      maxH < h &&
      v != u &&
      w != u
    ) {
      lca = u
      maxH = h
    }
    marked[u] = true

    for (const w of G.adj(u)) {
      if (marked[w]) continue
      dfs(w, h + 1)
    }
  }

  for (const s of sources) dfs(s)

  return lca
}
```

I tested the function with [your examples](https://github.com/pharrukh/algorithms/blob/main/graph/directed-graph/creative/dag-lowest-common-ancestor.ts).

What do you think @rene-argento-movile ?

**Comment by reneargento** [comment]
I believe that your first suggestion, of keeping track of in-degrees on the Digraph, makes sense.
And I noticed that the Digraph class already had that information, so I updated the exercise to use it. I still kept the computing of sources on the exercise as that is not needed on many other places.
Exercise updated here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/2793283465555fe3385dee3aeb11153e9bf0b896

For the second suggestion, of using only two variables for the LCA and node height, it seems that it reduces the number of variables used, but increases the running time of the algorithm.

With that approach you are doing a DFS to check the reachabilities (with `reachabilityFinder`) for every node inside the DFS.
This makes the overall running time of the algorithm `S * (V + E) * (V + E)`, as the DFS is run for every source. On the original approach, I did a `S * (V + E)` pre-processing on the constructor to compute all max heights, and on the `getLCA()` function, we get the LCA with a `V + E` running time per query.

Thanks for the suggestions!
