### ISSUE TITLE
EXERCISE 3.3.24 - worst case for red-black BSTs

### ISSUE THREAD

**Issue by qiuhaha** [reneargento/algorithms-sedgewick-wayne#303]
If you insert the key in descending order, the height of the tree would be 2 lg N alright, but I have calculated the average path length in this case. The value, though slightly bigger than that of a perfectly balanced tree, still approaches lg N when N is large.
Suppose that N = 2^(h+1) - 2, then by my calculation, the total internal path length L = 2^(h+1) + (2h-1)*(2^h) - 2h - 1, which would approach N lg N when N is very large.
I checked and checked, and it seemed that my calculation is right. Maybe there is an error in the text?

**Comment by reneargento** [comment]
That is a good question.
The book mentions that the worst-case for the red-black tree is a 2-3 tree that is all 2-nodes except that the leftmost path is made up of 3-nodes.
This is also mentioned on Sedgewick's paper on red-black trees: 
https://sedgewick.io/wp-content/themes/sedgewick/papers/2008LLRB.pdf
The relevant quote from that paper is this:
```
This worst case is realized, for example, in a tree whose nodes are all black except for
those along a single path of alternating red and black nodes.
```
It seems that inserting the nodes in reverse order (generating a "skinny tree") achieves that scenario. It is also the solution I found when researching for worst-case scenarios for red-black trees.

Some possible explanations could be:
1- The worst-case height for the red-black tree is not the same as the case to achieve an average path length of 2 lg N.
2- Since the book uses the left-leaning red-black tree variant, it needs a different insertion order to generate the worst-case average path length and height.

**Comment by reneargento** [comment]
Also, note that we are not looking for the internal path length here.
The exercise mentions only the paths from the root to a null link. Maybe that could explain the difference.

**Comment by qiuhaha** [comment]
> Also, note that we are not looking for the internal path length here. The exercise mentions only the paths from the root to a null link. Maybe that could explain the difference.

The difference between external path length and external path length is exactly 2N, so it's not gonna make a difference here when consider the average.

**Comment by qiuhaha** [comment]
Btw, while I'm at it, there's also an error in the solution for exercise 4.3.8: Given any cycle in an edge-weighted graph (all edge weights distinct), the edge of maximum weight in the cycle does not belong to the MST of the graph.
In your proof, you suppose the maximum-weighted edge _e_ in the cycle is in the MST, then you just choose any edge, _f_ that is also in the cycle but not in the MST. The problem is that, tough adding _f_ to the MST will certainly create **a** cycle, this cycle doesn't necessarily include _e_. Let's say the two endpoints of _e_ are v and w. What you have to do is find an edge x-y in the original cycle such that x is connected to v without w and y is connected to w without v (note that x could be v or y could be w). That way when you add x-y to the MST, you can certainly create a cycle including both v-w and x-y. I have not found a way to prove such an edge definitely exists though.

**Comment by qiuhaha** [comment]
Also, your solution for 4.3.26 is wrong too, though the link and description provided there are very helpful.
Firstly, within each equal-weight block, the point is to identify bridges, but your code just finds one cycle, ignoring the (high) possibility that multiple cycles exist. You could use the code in algs4/Bridge.java, but since that code doesn't handle parallel edges, you will have to make some modification.
Secondly, your code run in E*V time, instead of E*log E time. The problem is that you include all the vertices in the subgraph, and DFS run in E+V time, so while the number of edges is small, you still introduce a _V_ factor for every equal-weight block (If all weights are distinct, then the running time is exactly O(E*V)). But that's if your code doesn't include other errors that I haven't spotted. Because when I tried to run your code on the large graph **largeEWG.txt**, Java actually threw **OutOfMemoryError** because heap space is exhausted.
I have actually written the solution myself. I didn't make a pull request because our coding styles differ quite much, but you can check out the code here if that helps. 
[CriticalEdge.java.txt](https://github.com/reneargento/algorithms-sedgewick-wayne/files/13785966/CriticalEdge.java.txt)

**Comment by reneargento** [comment]
> > Also, note that we are not looking for the internal path length here. The exercise mentions only the paths from the root to a null link. Maybe that could explain the difference.
> 
> The difference between external path length and external path length is exactly 2N, so it's not gonna make a difference here when consider the average.

I see. In that case, the reason might be explained by the two possible scenarios I wrote above, or, as you mentioned, by an error in the text.

**Comment by reneargento** [comment]
> Also, your solution for 4.3.26 is wrong too, though the link and description provided there are very helpful. Firstly, within each equal-weight block, the point is to identify bridges, but your code just finds one cycle, ignoring the (high) possibility that multiple cycles exist. You could use the code in algs4/Bridge.java, but since that code doesn't handle parallel edges, you will have to make some modification. Secondly, your code run in E_V time, instead of E_log E time. The problem is that you include all the vertices in the subgraph, and DFS run in E+V time, so while the number of edges is small, you still introduce a _V_ factor for every equal-weight block (If all weights are distinct, then the running time is exactly O(E*V)). But that's if your code doesn't include other errors that I haven't spotted. Because when I tried to run your code on the large graph **largeEWG.txt**, Java actually threw **OutOfMemoryError** because heap space is exhausted. I have actually written the solution myself. I didn't make a pull request because our coding styles differ quite much, but you can check out the code here if that helps. [CriticalEdge.java.txt](https://github.com/reneargento/algorithms-sedgewick-wayne/files/13785966/CriticalEdge.java.txt)

Nice catch on the bug with the cycles and the runtime.
Thanks for the contribution and for providing your code too, it has been really helpful on fixing the solution.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/89b5256729bd7b3fb798abc278a82d6a703907dc

**Comment by qiuhaha** [comment]
Your solutions help a lot too.
Also, another problem found in the solution for exercise 4.4.37. I've read the post you provide, and noticed that different from the original post, you treat every shortest path edge from s to t as a bridge, and you use the breadth-first walk approach someone else mentioned in the comment instead of the methods the post suggests. But that approach is to do the BFS on the SPT, and in you solution the BFS is done on the original graph. So there's a little bug there.
But that doesn't matter much, since the original post is wrong anyway. The crux of the whole approach lies on bridge bi not being on the shortest paths from s to u or from v to t if u is in the island with index <= i and v is in the island with index > i. The former is true, while the latter is not. 
Consider the example below (this is an example that causes problem in your solution too):
```
edgeWeightedDigraph1.addEdge(new DirectedEdge(0, 1, 10));
edgeWeightedDigraph1.addEdge(new DirectedEdge(1, 2, 10));
edgeWeightedDigraph1.addEdge(new DirectedEdge(2, 3, 10));
edgeWeightedDigraph1.addEdge(new DirectedEdge(3, 4, 10));
edgeWeightedDigraph1.addEdge(new DirectedEdge(4, 5, 10));
// other Path
edgeWeightedDigraph1.addEdge(new DirectedEdge(3, 7, 1));
edgeWeightedDigraph1.addEdge(new DirectedEdge(7, 2, 1));
edgeWeightedDigraph1.addEdge(new DirectedEdge(2, 6, 10));
edgeWeightedDigraph1.addEdge(new DirectedEdge(6, 8, 1));
edgeWeightedDigraph1.addEdge(new DirectedEdge(8, 7, 1));
edgeWeightedDigraph1.addEdge(new DirectedEdge(0, 2, 30));
edgeWeightedDigraph1.addEdge(new DirectedEdge(3, 5, 30));
int source1 = 0;
int target1 = 5;
```
The edge causing the problem here is 8->7, while vertex 8 is in the island 2 and 7 is in the island 3. Though vertex 7 is in the island 3, the shortest path (also the only path) from 7 to 5 must pass through bridge b2 (2->3). So, while being the only irreplaceable edge here, the bypass length of b2 is infinity, this method erroneously computes 63.

**Comment by qiuhaha** [comment]
> Your solutions help a lot too. Also, another problem found in the solution for exercise 4.4.37. I've read the post you provide, and noticed that different from the original post, you treat every shortest path edge from s to t as a bridge, and you use the breadth-first walk approach someone else mentioned in the comment instead of the methods the post suggests. But that approach is to do the BFS on the SPT, and in you solution the BFS is done on the original graph. So there's a little bug there. But that doesn't matter much, since the original post is wrong anyway. The crux of the whole approach lies on bridge bi not being on the shortest paths from s to u or from v to t if u is in the island with index <= i and v is in the island with index > i. The former is true, while the latter is not. Consider the example below (this is an example that causes problem in your solution too):
> 
> ```
> edgeWeightedDigraph1.addEdge(new DirectedEdge(0, 1, 10));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(1, 2, 10));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(2, 3, 10));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(3, 4, 10));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(4, 5, 10));
> // other Path
> edgeWeightedDigraph1.addEdge(new DirectedEdge(3, 7, 1));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(7, 2, 1));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(2, 6, 10));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(6, 8, 1));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(8, 7, 1));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(0, 2, 30));
> edgeWeightedDigraph1.addEdge(new DirectedEdge(3, 5, 30));
> int source1 = 0;
> int target1 = 5;
> ```
> 
> The edge causing the problem here is 8->7, while vertex 8 is in the island 2 and 7 is in the island 3. Though vertex 7 is in the island 3, the shortest path (also the only path) from 7 to 5 must pass through bridge b2 (2->3). So, while being the only irreplaceable edge here, the bypass length of b2 is infinity, this method erroneously computes 63.

Computing another set of island numbers from the target using reverse graph may fix the problem, but I'm not terribly sure. That language in the original post is not very strict or precise, and the technical terms the poster chose are not widely used in graph theory (couldn't find them in Wikipedia), so I'm not so sure that there aren't other errors hidden in the proofs.

**Comment by qiuhaha** [comment]
I've done some further thinking, and I believe computing a different set of island numbers from the target is gonna fix the problem. My original concerns are the correctness of treating every shortest path edge as bridges, because this may result in different island number for a single vertex, and it's no longer true that if the shortest path from s to v passes bridge i, then it must also pass bridge 1, 2, ...i-1. Upon further consideration, I'm basically convinced these are not gonna affect the result.

**Comment by reneargento** [comment]
Thanks for reporting the bug when computing the islands in exercise 4.4.37.
I fixed it to do the BFS on the reverse graph with this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/0e7ead4b25d451da17b6f35841b045f0b6b3d07c
I agree this should now give the correct results.
