### ISSUE TITLE
Exercise 6.37 - maxflow with sink removed

### ISSUE THREAD

**Issue by juliovr** [reneargento/algorithms-sedgewick-wayne#304]
In the main() given in [Exercise37.java](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter6/networkflow/Exercise37.java), the graph has 3 branches down to a sink (capacities in parenthesis):
0---(5)--->1---(4)--->4---(3)--->6
0---(8)--->2---(10)--->5---(7)--->6
0---(2)--->3---(2)--->6

The current algorithm uses the minimum capacity for each branch, but it is using the last one as well (which is connected to the removed sink):
0->1->4->6 = 3
0->2->5->6 = 7
0->3->6 = 2
total maxflow = 12

But removing the sink (node id 6), the minimum capacity for each branch would be:
0->1->4 = 4
0->2->5 = 8
0->3 = 2

given a total of maxflow 14.

Here is my solution:
``` java
private static double getMaxFlow(FlowNetwork G, int source, int target) {
	double maxflow = 0.0;
	for (FlowEdge e : G.adj(source)) {
		int w = e.to();
		if (w != target) {
			double minCapacity = e.capacity();
			maxflow += dfs(G, w, target, minCapacity);
		}
	}

	return maxflow;
}

private static double dfs(FlowNetwork G, int v, int target, double minCapacity) {
	for (FlowEdge e : G.adj(v)) {
		if (v == e.from()) {
			int w = e.to();
			if (w == target) {
				continue;
			}

			if (e.capacity() < minCapacity) {
				minCapacity = e.capacity();
			}

			return dfs(G, w, target, minCapacity);
		}
	}

	return minCapacity;
}
```

**Comment by reneargento** [comment]
Fixed now on this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d9a81720d849cf8523a00eb2982272a0935b6a78
Thanks for the contribution!
