### ISSUE TITLE
Potential Issue with 4.4.34

### ISSUE THREAD

**Issue by hermantulleken** [reneargento/algorithms-sedgewick-wayne#306]
I think there may be an issue with your solution to this problem:

https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter4/section4/Exercise34_MonotonicShortestPath.java#L5

For a graph like

```
0---(1)-->1---(7)-->2---(6)-->3
\---(4)-->4---(5)---^
```

Or:
```
0->1: weight 1
1->2: weight 7
2->3: weight 6
0->4: weight 4
4->2: weight 5
```

The algorithm reports the best path to vertex 2 to be via vertex 4 instead of via vertex 1.

I think the underlying issue is the best path to 2 is via 1, but the best path to 3 is not, since `0->1->2->3` is not monotonic (even though `0->1->2` is). 

I am not sure what the solution is; it seems not possible to store information that enables you to retrieve both paths using only one `edgeTo` per vertex. I therefore wonder how to interpret the hint in the textbook. 

> [!WARNING]
> I have not run your exact code. I translated your algorithm to C#, and since it is rather subtle I may well have made a mistake. However, I do believe the underlying principle to be true. Besides, I get the same results as in your example, and my unit tests where sub-paths are always shared pass. If you test it, test the path to both vertex 2 and 3.

**Comment by reneargento** [comment]
Thanks for reporting this issue.

Indeed, there was a bug with paths to vertices that had different sub-paths.
And I agree that we can't retrieve all possible paths with just one `edgeTo` array.

I updated this exercise to keep the list of edges on the path to each vertex.
The performance won't be the same as using just one `edgeTo` array, but it seems to be the only way where we can retrieve all possible monotonic paths.

The updated version can be found here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/1ddd1da3cc0637fe5cfefbb6a2f4c77cb33a56fe

**Comment by reneargento** [comment]
After further consideration, I updated the exercise to use an array of `Path` objects, in a way that we don't need to store all edges in each path.
This allows us to retrieve all possible monotonic paths and requires just references to Paths, optimizing the runtime.
This is the commit with the update: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/7aa3ff7cb3333f80605e9fb56c6463bb54c681bf

**Comment by hermantulleken** [comment]
Ah, I think this is a nice solution.
