### ISSUE TITLE
Question about Chapter 1, Section 3, Exercise 9

### ISSUE THREAD

**Issue by ru2saig** [reneargento/algorithms-sedgewick-wayne#308]
First off, thank you for this wonderful work! 

Coming to my question, I've attempted exercise 1.3.9, and was looking at the solution is located here (this repo): [src/chapter1/section3/Exercise9.java](https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter1/section3/Exercise9.java), and I realized that the implementation will not work for and expression like 1 + sqrt 5.0 ) ) / 2.0 ), since it does not have unary operators. It also will not handle something like 1 + 2 ) ); extra closing parenthesis. 

I don't think that the program directly specified that we have to support unary operators, or extra parentheses. But what are your thoughts on these issues? 

Here's my solution which can handle those cases:
```java
import edu.princeton.cs.algs4.Stack;
import edu.princeton.cs.algs4.StdIn;
import edu.princeton.cs.algs4.StdOut;

public class InsertParen {

    private static String makeParens(String missingParen)
    {
	Stack<String> ops = new Stack<String>();
	Stack<String> vals = new Stack<String>();

	String unaOps = "sqrt";
	String binOps = "+ - * /";
	
	String[] missingParenTokens = missingParen.split("\\s+");

	for (String token : missingParenTokens) {
	    if (unaOps.contains(token) || binOps.contains(token)) {
		ops.push(token);
	    } else if (token.equals(")")) {
		String result = "";

		if (ops.size() == 0) { // ensures that any expression with extra closing parens are opened
		    result = "( " + vals.pop() + " )";
		} else {
		    String op = ops.pop();
		    
		    if (unaOps.contains(op)) { // handles unary operators
			result = op + " ( " + vals.pop() + " )";
		    } else { // we have a binary operation!
			String v2 = vals.pop();
			String v1 = vals.pop();
			result = "( " + v1 + " " + op + " " + v2 + " )";
		    }
		}
		
		vals.push(result);
	    } else { // a number!
		vals.push(token);
	    }
	}
	
	return vals.pop();
    }

    /*
     * Running: 
     * echo "1 + 2  )  ) )" | java-algs4 InsertParen.java
     * echo "1 + 2 ) * 3 - 4 ) * 5 - 6 ) ) )" | java-algs4 InsertParen.java
     */
    public static void main(String[] args)
    {
	while(StdIn.hasNextLine()) {
	    String missingParen = StdIn.readLine();
	    StdOut.println(makeParens(missingParen));
	}
    }
}

```

**Comment by reneargento** [comment]
Looking at the arithmetic expression example given in the book, both binary and the sqrt unary operator are handled, so it makes sense to handle both of them.
I updated the exercise to handle the sqrt unary operator too: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/5465741e0e138039ea629267b68c05f15a5e05df

Extra closing parenthesis are not mentioned (and we can always add more complexity to any exercise, such as more operators and other invalid symbols), so I didn’t add code for it.

Thanks for the contribution!
