### ISSUE TITLE
Question about 1.1.12

### ISSUE THREAD

**Issue by Taylor-McNeil** [reneargento/algorithms-sedgewick-wayne#31]
Hey, I might be wrong here but I believe the first for loop creates the array 9 8 7 6 5 4 3 2 1 0. Then the second for loop reverses the first array, making it 0 1 2 3 4 5 6 7 8 9. I believe this happens because you have to determine the inner bracket first. So during the first round with i=0, a[i]=9, therefore a[a[i]] is really a[a[0]=9]==0, its confusing but I think is what is happening.

**Comment by reneargento** [comment]
You are right about the first loop, it does create the array 9 8 7 6 5 4 3 2 1 0.
However, notice that on the second loop, after half of the array is reversed, we no longer have the values 9 8 7 6 5 (they have been overwritten with 0 1 2 3 4).
That is why the end result is 0 1 2 3 4 4 3 2 1 0.

If you run the code at https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter1/section1/Exercise12.java you can see this in practice.

**Comment by YaochengTong** [comment]
please check #38

**Comment by reneargento** [comment]
Ok, so even though the array final values will be 0 1 2 3 4 4 3 2 1 0, the last loop prints the index, and not the values of the array.
This seems like a typo in the book, but you are right, the output will be 0 1 2 3 4 5 6 7 8 9.
Thanks for the contribution!
