### ISSUE TITLE
1.4.5 answers are wrong

### ISSUE THREAD

**Issue by mathieu2em** [reneargento/algorithms-sedgewick-wayne#32]
the tilde notation defines ~f(N) as a function with which the  limit of the actual stuff happening ( g(n) divided by ~f(n)  ) tends to 1 when n tends to infinity to 

1.4.5
  a) ~N (this one is ok )
  b) ~1 
 you wrote 1/N but for f(N) = 1 + 1/N , the limit when n -> infinity of  (1 + 1/N)/(1/N) = infinity so ~F(N) is clearly not = to 1/N
  c) ~1  
  d) ~2N^3
  e) ~1
lg2(2N)/lg2(N) = lg2(2)/lg2(N) + lg2(N)/lg2(N) = 1 + lg2(2)/lg2(N) 
lim n-> infinity  ( 1 + lg(2)/lg(N) ) /1 = 1/1 + 0/1 = 1  so ~1
 f) ~2
 lg(N²+1)/lg(N) approximately = lg(N²)/lg(N) = 2lg(N)/lg(N) = 2 

lim n-> inf. 2/2 =1 so ~2
 ... etc

**Comment by reneargento** [comment]
You are right, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/61632d73ba4a0903755d085053a348f6baa14abd 
Thanks for the contribution!

**Comment by YaochengTong** [comment]
for g question, N^100 / 2^N should result in 0. #39

**Comment by reneargento** [comment]
Thanks, updated at: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/73f845819c2665b54236a5075faa19f7f69add7d
