### ISSUE TITLE
1.1.36 and 1.1.37 arrays should get reinitialized before each shuffle

### ISSUE THREAD

**Issue by ccumulatio** [reneargento/algorithms-sedgewick-wayne#33]
Otherwise the badShuffle() in 1.1.37 won't show bad results in the end.

**Comment by reneargento** [comment]
Thanks for the contribution!
I added the reinitializations here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/3ad44914c70a29823cb3c256fe87af7979528c0e
