### ISSUE TITLE
1.1.30 Prime vs Coprime

### ISSUE THREAD

**Issue by alexrad89** [reneargento/algorithms-sedgewick-wayne#34]
The problem ask that the numbers be coprime not that both should be prime.
So just checking that largest does not have a remainder when diving by the smallest should do it.

**Comment by reneargento** [comment]
That approach would fail for values such as 8 and 12 -> the result of 12 % 8 is equal to 4, yet they are not coprime.

**Comment by alexrad89** [comment]
Fair enough, so then you dont need to increment from 2 to "biggestValue" you can stop at smallestValue.

**Comment by reneargento** [comment]
True, that is a good improvement.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/e5ef673ffae7834b501d5ff91d3d5c445f171482
Thanks for the contribution!

**Comment by shrutigupta23** [comment]
We can use gcd by Euler division method here. If gcd is 1 then nos are coprime else they are not. Reduces time complexity.

**Comment by reneargento** [comment]
Good idea, I added it in this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d74098db020089ca44f4cb7d4211480291a7eb70
Thanks for the contribution!

**Comment by reneargento** [comment]
Good point, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/1d97484445f5efd5ad7b6e85f33bbcc3c6cdce17
Thanks for the contribution!

**Comment by anirudh-sethi** [comment]
The only integers that coprime to zero are 1 and -1 https://proofwiki.org/wiki/Integers_Coprime_to_Zero

**Comment by a-set** [comment]
The only integers that are coprime to zero are 1 and -1 https://proofwiki.org/wiki/Integers_Coprime_to_Zero

**Comment by reneargento** [comment]
Thanks for the contribution, I updated the exercise for handling zeros correctly here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/81380b26aa3e86cd226ea6ca5af04fbd6af62811

**Comment by lui-coding** [comment]
```
private static boolean isCoprime(int i, int j) {
        if (i == j && i != 1) {
            return false;
        }

        if (i == 0 || j == 0) {
            return handleZero(i, j);
        }
        return gcd(i, j) == 1;
    }
```

The first if statement (if (i == j && i != 1)) is unnecessary because the gcd function already handles this case. When i == j, gcd(i, j) will return i (or j), and the result will naturally determine whether the numbers are coprime. This simplifies the code and avoids redundancy. Consider removing this condition.

**Comment by reneargento** [comment]
Thanks for the contribution, I updated the exercise: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/f0d676084f1c7898acd65a9c03b900ed1637ffe3
