### ISSUE TITLE
3.2.9 missing shape for n=4

### ISSUE THREAD

**Issue by Scharling** [reneargento/algorithms-sedgewick-wayne#36]
If you have the insertion order: 1 3 2 4 you will get a tree shaped like the reverse of the tree with insertion order 4 2 1 3 or 4 2 3 1. (I can't get Github to format it, so it would shot the tree structure.) P.S. love your work!

**Comment by Scharling** [comment]
(And it is missing from your n=4 possible shapes)

**Comment by reneargento** [comment]
Thanks for the contribution!
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/8e371fe233ab80d2344a774866aed1675e636e89
