### ISSUE TITLE
3.4.10

### ISSUE THREAD

**Issue by Kongkille** [reneargento/algorithms-sedgewick-wayne#37]
How are there 2 Qs in 3.4.10 on M=16?

There cannot be duplicate keys in a hashtable? 

Thank you

**Comment by reneargento** [comment]
Some insertions were incorrect, I fixed them in this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/a8bbc132d6b21c84013e05b14881cb18a82934c7

Thanks for the contribution!
