### ISSUE TITLE
Ex 1.5.2 Bug in solution

### ISSUE THREAD

**Issue by kaustubhb** [reneargento/algorithms-sedgewick-wayne#4]
The correct solution I think is below.
Thanks for the effort to create this repository! It helps a lot to cross check solutions.

Initial - [0,1,2,3,4,5,6,7,8,9]

```
9-0
[0,1,2,3,4,5,6,7,8,0]
0 1 2 3 4 5 6 7 8
9

3-4
[0,1,2,4,4,5,6,7,8,0]
0 1 2 4 5 6 7 8
9     3

5-8
[0,1,2,4,4,8,6,7,8,0]
0 1 2 4 6 7 8
9     3     5

7-2
[0,1,2,4,4,8,6,2,8,0]
0 1 2 4 6 8
9 7   3   5

2-1
[0,1,1,4,4,8,6,2,8,0]
0 1 4 6 8
9 7 3   5
  2

5-7
[0,1,1,4,4,8,6,2,1,0]
0 1 4 6 
9 7 3   
  2
  8
  5

0-3
[4,1,1,4,4,8,6,2,1,0]
1 4 6 
7 3   
  2
  8
  5
  0
  9

4-2
[4,1,1,4,1,8,6,2,1,0]
1 6 
7   
4 
3 
2
8 
5
0
9
```

**Comment by reneargento** [comment]
Thanks! It is good to know that the repository is being useful :)

Nice catch regarding the array values, I just updated the answer.

I am not sure I understood the forest of trees that you drew though (or if any spacing got lost in Github's formatting).
Please take a look in the updated forest of trees in the commit https://github.com/reneargento/algorithms-sedgewick-wayne/commit/7798a6b79d09f459a8690ba7b4d6edbf91926d28

Let me know what you think about it. If you find any more bugs please let me know!
Thanks for contributing to the repository!

**Comment by kaustubhb** [comment]
Thanks for your reply. Cross checking my solutions with your repository feels almost like working along with a study pal!
Formatting was indeed lost due to spacing. I have updated the comment. However, I did not preserve the hierarchy within forest.
