### ISSUE TITLE
1.3.36 Shuffle

### ISSUE THREAD

**Issue by Oreshnik** [reneargento/algorithms-sedgewick-wayne#40]
Hello!
It seems to me, that the shuffle algorithm has a little bug. We should choose random index between 0 and i + 1, not size (see https://youtu.be/54rMYC2pEtw?t=236 or StdRandom.shuffle implementation, or Collections.shuffle implementation).
Thanks)

**Comment by reneargento** [comment]
You are right, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/77ff05826721f95048c79050ed6c966006147950
Thanks for the contribution!
