### ISSUE TITLE
ex 1.3.26 forgotten size

### ISSUE THREAD

**Issue by Oreshnik** [reneargento/algorithms-sedgewick-wayne#41]
Hello!
There is a lack of size changing in some methods, such as 
delete (ln 72, 79)
remove(ln 93, 100)
removeAfter(ln 132)
insertAfter(ln 149)

Thank you!

**Comment by reneargento** [comment]
Nice catch(es)! I fixed them here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/abbc5e2d4714ac829869df4e76ca1199cc7995f7
Thanks for the contribution!
