### ISSUE TITLE
2.2.17 - natural sort (?)

### ISSUE THREAD

**Issue by dbf256** [reneargento/algorithms-sedgewick-wayne#42]
In task description they ask: "Implement  a  natural  mergesort  for  linked  lists. ". In 2.2.16 they describe "natural mergesort" for arrays as finding sorted sub-arrays, but looks like in 2.2.17 solution we just increase size of sublist twice for each iteration, shouldn't we search for sorted sublists?
Thanks.

**Comment by reneargento** [comment]
You are right, I updated the exercise with a correct implementation of a natural mergesort in this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/cb467b1d019c9f9c4f6e46081603b7be8549e5da
Thanks!

**Comment by dbf256** [comment]
Thanks for fix!
