### ISSUE TITLE
1.4.34 Hot Or Cold. Based on your answer i have written a more simplify code

### ISSUE THREAD

**Issue by hpmss** [reneargento/algorithms-sedgewick-wayne#43]
I dont know whether this is correct or not but following your testing in "main" function this turns out to be correct for all of your tests. Proportional to 2*O(log N).

    public static int keyGuess(int key,int start,int end) {
		
		if(start > end || start == end) {
			return -1;
		}
		
		int initGuess = start + (end - start) / 2;
		
		if(initGuess == key) {
			return initGuess;
		}
		
		int secondGuess = initGuess + 1;
		
		if(secondGuess == key) {
			return secondGuess;
		}
		
		boolean isHotter = isHotter(initGuess,secondGuess,key);
		
		if(isHotter) {
			return keyGuess(key,secondGuess,end);
		}else {
			return keyGuess(key,start,initGuess);
		}
		
	}
	
	public static boolean isHotter(int previous,int current,int key) {
		if(Math.abs(current - key) < Math.abs(previous - key)) {
			return true;
		}else {
			return false;
		}
	}
    public static void main(String[] args) {
		StdOut.println(keyGuess(4,1,10));
		StdOut.println(keyGuess(12,1,20));
		StdOut.println(keyGuess(19,1,20));
		StdOut.println(keyGuess(20,1,20));
		StdOut.println(keyGuess(21,1,20));
		StdOut.println(keyGuess(-1,1,100));
		
	}

**Comment by reneargento** [comment]
There is an issue with this implementation. Every time we call keyGuess() we are making 2 new guesses that are independent from the previous one.
The exercise asks to compare all new guesses with the guess previous to it.

**Comment by hpmss** [comment]
I see ! thanks alot
