### ISSUE TITLE
1.4.26 Exercise26_3Collinearity

### ISSUE THREAD

**Issue by shftdlt** [reneargento/algorithms-sedgewick-wayne#48]
For the first test case (where all six points are on the same line), why is the expected count 10 instead of C(3, 6) = 6! / (3! * 3!) = 20?

```
Point2D[] points = new Point2D[6];
for(int i = 0; i < points.length; i++) {
    Point2D point = new Point2D(i, i + 1.5);
    points[i] = point;
}

int numberOfTriples1 = exercise26_3Collinearity.countTriples(points);
StdOut.println("Number of triples: " + numberOfTriples1  + " Expected: 10");
```

Notice in countTriplesUsingSlopes() there is a break statement (line 128) in the for loop which is counting the triples.
```
for (Integer index : pointIndexes) {
    if (index > i && index > j) {
        triples++;  
        break;   // is this break really necessary?
    }
}
```

**Comment by reneargento** [comment]
The expected should be 20.
I removed the unnecessary break condition and updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/07585ee341b2a503febf797239fefe906614c432
Thanks for spotting that!
