### ISSUE TITLE
2.5.11

### ISSUE THREAD

**Issue by dbf256** [reneargento/algorithms-sedgewick-wayne#50]
For HeapSort call we populate array starting from 0 index:
System.arraycopy(array, 0, heapSortCopy, 0, array.length);
but looks like HeapSort.heapSort / sortdown expects first element at index 1 and 0 element is not processed correctly?

**Comment by reneargento** [comment]
The index for the heap sort array was incorrect, I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/ee65784b3427a30031a50f5c197a03a3cd9f47d4
Thanks!
