### ISSUE TITLE
1.4.16 : the solution is linearithmic not linear

### ISSUE THREAD

**Issue by AsemK** [reneargento/algorithms-sedgewick-wayne#53]
The solution uses sort() which is linearithmic. If you want a linear solution avoid sort. Traverse the (non sorted) array to get the smallest two numbers.

**Comment by reneargento** [comment]
The exercise asks for a linearithmic runtime in the worst case. So using sort() is ok.
Also, I'm not sure if I understand how your linear solution works.
If we have an array such as `1 5 20 21`, the two smallest numbers would be `1` and `5`, but the closest pair is `20` and `21`.
