### ISSUE TITLE
3.2.1

### ISSUE THREAD

**Issue by LegendaryKokiri** [reneargento/algorithms-sedgewick-wayne#55]
Hello! First of all, thanks for creating this repository! I've found it very helpful for my development as I work through the book's practice problems.

Second, I just had a quick question for Question 3.2.1. You say that there should be a total of 27 compares to form a binary search tree for E A S Y Q U E S T I O N. However, when I do the problem, I keep coming up with 28. I think the discrepancy is that only one compare is counted for the second "S," whereas two should be counted--one to determine that S > E and a second to determing that S == S and should thus replace the existing S in the tree.

Thanks for your time!

**Comment by reneargento** [comment]
Hello! I'm happy to know the repository has been helpful to you.

About question 3.2.1, you are right, there was one compare missing in the count.
I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/4882566d5d1c2776a84b2115c0001d3382b4d637

Thanks for the contribution!

**Comment by LegendaryKokiri** [comment]
You're very welcome!
