### ISSUE TITLE
4.1.10

### ISSUE THREAD

**Issue by dbf256** [reneargento/algorithms-sedgewick-wayne#56]
> If the graph has a node of degree one, removing it gives a connected graph.
> Example: o - o
> Otherwise, every path in the graph belongs to a cycle.
> 
> 

I think that it is not correct if you have such graph:

```
   b          f
  /   \     /  \
a     c - e    g
  \d/       \h/


```

Path c-e is not a part of the cycle

**Comment by LegendaryKokiri** [comment]
Hello! Obviously, I'm not reneargento, but I think I can answer your question.

In your example, path c-e is indeed part of a cycle. For example, you can follow this path:
a-b
b-c
**c-e**
e-f
f-g
g-h
h-e
**e-c**
c-d
d-a

Recall that the book defines a cycle as "a path with at least one edge whose first and last vertices are the same." In other words, a cycle can consist of a repeating edge. However, you are correct in saying that your graph is not a SIMPLE cycle, as the book defines a simple cycle as "a cycle with no repeated vertices (except the requisite repetition of the first and last vertices)."

Therefore, path c-e cannot be part of a simple cycle. However, it can be part of a regular cycle. As such, c-e is still part of the cycle, and reneargento's proof will hold.

Hopefully this is helpful!
