### ISSUE TITLE
5.4.11 -- Permutations

### ISSUE THREAD

**Issue by LegendaryKokiri** [reneargento/algorithms-sedgewick-wayne#59]
I was working 5.4.11, and I came up with a different answer for part c. We both agree that we can have one thousand 1's and zero 01's, 998 1's and 2 01's, etc. However, I came out with an answer of 2^500 instead of 500, as the 01's and 11's can be placed in multiple permutations.

To illustrate with a simpler example, if our bitstring had to be 6 bits long instead of 1000 bits long, the following bitstrings would match our regular expression (I use "|" as a separator just for clarity.):

==6 1's and 0 01's==
1. 11 | 11 | 11
==4 1's and 1 01==
2. 11 | 11 | 01
3. 11 | 01 | 11
4. 01 | 11 | 11
==2 1's and 2 01's==
5. 11 | 01 | 01
6. 01 | 11 | 01
7. 01 | 01 | 11
==0 1's and 3 01's==
8. 01 | 01 | 01

This answer of 2^3 corresponds to the 2^500 that I calculated for 5.4.11c.

**Comment by LegendaryKokiri** [comment]
P.S. I hope you don't feel like I'm trying to emphasize your mistakes or call you out or anything like that. Know that your work has caught my mistakes or helped me understand exercises many more times than I've posted issues here!

**Comment by reneargento** [comment]
Makes sense, part `c` should be `2^500`, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/0fc6890ac7f0df70da1ec86ef30e740d904b0cdb

Thanks for all the contributions! It is always great to have them, this is the idea of the repository, to have it better and improved as more and more people work on the exercises.
If you find anything else don't hesitate to open more issues or PRs, they are always welcome.

**Comment by LegendaryKokiri** [comment]
Thanks, reneargento!
