### ISSUE TITLE
1.3.26

### ISSUE THREAD

**Issue by sdxxxa** [reneargento/algorithms-sedgewick-wayne#60]
remove() repeat item not act as expect: add(1 1 1 2 3 1 1 1 2 3 1 1 1,
remove (1,
print: 2 3 1 2 3 1

**Comment by reneargento** [comment]
Looks like the method was only checking the next element and not all the next ones. 
I corrected it in this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/3d5efa255eab624249da27ce18ca2a5fed08cabd
Thanks for the contribution!
