### ISSUE TITLE
3.2.4: the answer omits option b

### ISSUE THREAD

**Issue by CharlieLei** [reneargento/algorithms-sedgewick-wayne#61]
> The sequence that cannot be the sequence of keys examined is:
> d. 2, 7, 3, 8, 4, 5

The option b is [4, 10, 8, 7, 5, 3]. "10" is the next key of "4", which means that the search path goes to the right subtree of "4".Therefore, "3" cannot appear in the search path. So, option b cannot be the sequence of keys examined as well.

**Comment by reneargento** [comment]
You are right, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/c368fe3818b0cd75f94e6c39a632c7511d6c5dd7
Thanks!

**Comment by oddhus** [comment]
In my version of the book (bought aug 2019) the option b is [4, 10, 8, 6, 5] which is a valid sequence.

**Comment by reneargento** [comment]
I see, so newer versions of the book have a different sequence on option b.
I updated the exercise here to make that note: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/c3344fb1631429798f8dbfad18c52b2d9fa9f399
Thanks!
