### ISSUE TITLE
Exercise 3.2.11

### ISSUE THREAD

**Issue by Oreshnik** [reneargento/algorithms-sedgewick-wayne#63]
You didn't mention 1 2 4 3.
Actually, we can build variants of the N-tree with all combination of right and left links on nodes with child. Say, for N = 4:
```
\       \        \       \       /      /       /       /
 \       \       /       /       \      \      /       /
  \      /      /        \       /       \     \      /

```
Thus, the number of different BST shapes is 2^(N-1)

**Comment by reneargento** [comment]
Thanks for the contribution!
I updated the exercise here:
https://github.com/reneargento/algorithms-sedgewick-wayne/commit/557bf5b9f38aa8a4d0db316d10b4aea42ca959b5

**Comment by Oreshnik** [comment]
Thank you!

**Comment by shycool** [comment]
I find the rule to build the N-tree . 
Every time you must choose max or min value, so every time we have 2 choice but the last,
and then the number is 2^(N-1)
