### ISSUE TITLE
Exercise 1.5.6. Why is the fact that 10 machine instructions required for each iteration of the loop not taken into account?

### ISSUE THREAD

**Issue by QiotoF** [reneargento/algorithms-sedgewick-wayne#65]
Hello! Thank you a lot for this repo, it helps me a lot in studying.

My question is about answer on exercise 1.5.6. 
Shouldn't the result be also multiplied by 10? (So the answer is 0.6 seconds)
Particularly, 
> Each find operation makes on the worst case lg(10^9) ~ 30 instructions

there should be 30 iterations, not instructions, isn't it? So to get amount of instructions, we multiply by number of instructions per iteration and get 30*10=300 instructions.

**Comment by reneargento** [comment]
It is good to know that the repository is being useful to you!
You are right, the 10 instructions per iteration were not being considered.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d1078f238704b2ac4e45569f84862ce3ba666d66
Thanks for the contribution!
