### ISSUE TITLE
1.1.36 and 1.1.37

### ISSUE THREAD

**Issue by thiendao1407** [reneargento/algorithms-sedgewick-wayne#73]
Hello!
Exercise 1.1.36 requires to print an M-by-M table such that **row i gives the number of times i wound up in position j** for all j, so I think the code in Main method should be

```
while (n-- > 0) {
	initializeArray(array);
	shuffle(array);

	for (int j = 0; j < array.length; j++) {
		positions[(int) array[j]][j]++; //the value of array[j] means row index i
	}
}
```
Same for 1.1.37. Beside that, 1.1.37 requires to choose a random integer between 0 and N-1
in our shuffling code instead of one between i and N-1, and we can revise code in badShuffle method as below 

`int randomIndex = StdRandom.uniform(n);`

Thank you.

**Comment by reneargento** [comment]
You are right, I updated both exercises here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d3405ae7cf1390abbfbe1b9b04e6b9830a222fa7
Thanks for the contribution!
