### ISSUE TITLE
It seems that answer on exercise 2.1.3 is not correct

### ISSUE THREAD

**Issue by QiotoF** [reneargento/algorithms-sedgewick-wayne#76]
Hello. Thank you for this repository.

It seems that answer on exercise 2.1.3 is not correct. Your answer is Z R E N E A B C. I counted the number of times the test a[j] < a[min] succeeds during the operation of selection sort and it equals to 10. If we take an array H G F E D C B A (same length as yours), for example, this number will be 16. So Z R E N E A B C is not right answer.

**Comment by reneargento** [comment]
Hello.
You are right. So far the worst case I have found for selection sort is when it sorts an array in reverse sorted order (such as the one you mentioned).
I updated the exercise to reflect this: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/a64d9e3da88652b45668f24f3977788acc0d4ee0
Thanks!

**Comment by Rapid-Turtle** [comment]
@reneargento Ex 2.1.3 requires us to maximize the number of times a[j] < a[min] **_fails._** The above answer maximizes the number of times it succeeds. I think the answer should be an ordered array A B C D E F G H.

**Comment by reneargento** [comment]
@BOTbkcd Your answer is correct for previous versions of the book, where exercise 2.1.3 asked us to maximize the number of times that `a[j] < a[min]` fails. On the seventh printing of the book, on which this repository is based, it asks us to maximize the number of times it succeeds. So the answer above is correct.
