### ISSUE TITLE
5.4.1 (1)

### ISSUE THREAD

**Issue by ZjoeyZ** [reneargento/algorithms-sedgewick-wayne#78]
Hello, really appreciate your repository.

Here is the qustion:
Regular expression for strings that contain exactly four consecutive As.
your answer : 
A{4} | A{4}[^Ae].* | .*[^Ae]A{4} | .*[^Ae]A{4}[^Ae].*

why there is a 'e' next to 'A'? 
I don't think your answer can match 'eAAAAe'

[https://github.com/reneargento/algorithms-sedgewick-wayne/blob/master/src/chapter5/section4/Exercise1.txt](url)

**Comment by reneargento** [comment]
The `e` is the empty string. The last line in the file mentions this, but after a closer look to the regular expression, I noticed that we don’t need it.
I removed it in this commit: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/bfa4910084baf8ce2b97383106085f07fafeeaea
Thanks for the question!

**Comment by ZjoeyZ** [comment]
hello,another question at this one,
"Regular expression for strings that contain no more than four consecutive As"
your answer is [^A{5}]*A{0-4}[^A{5}]*.
the book said: "A sequence of characters within square brackets represents any **one** of those characters, . If preceded by a ^, a sequence within square brackets represents any character but one of those characters".
so i think [^A{5}] is same as [^A] ?

**Comment by reneargento** [comment]
You are right, thanks for pointing that out.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/2161f2a2b4a1434c66f14bf17de34f98af34900d
