### ISSUE TITLE
What is the best way to build the source here

### ISSUE THREAD

**Issue by bitflame** [reneargento/algorithms-sedgewick-wayne#85]
Hi 
I built the source for the course using Maven, and I put your source in a different folder but can not run the code that references Stdout library. Is there a way that worked for you or someone you know to add your source to the same project? Perhaps a subdirectory of a /lib or something? 
As soon as I added your source, the same pom from  the course took over and added it to the project, but I ran into the error when I tried to run the questions that involved using  stdout

**Comment by reneargento** [comment]
Hi,
I haven't tried adding the source of this project to other projects, but notice that this project has a `/libs` folder with the `algs4.jar` file that should contain all the source code from the book.
So you can run them together by simply cloning this repository and making sure you reference all the libraries inside the `/libs` folder.

**Comment by bitflame** [comment]
Thank  you. Yes that worked.
