### ISSUE TITLE
Wrong question answered in Exercise 4.2.20

### ISSUE THREAD

**Issue by moinmir** [reneargento/algorithms-sedgewick-wayne#86]
The answer for 4.2.20 in Exercise20.txt is for a true-false question. The actual exercise on the book is to write a client for finding a directed Eulerian cycle.

**Comment by reneargento** [comment]
You may be looking at an older version of the book.
I know that on the first printing of the book (of March 2011) exercise 4.2.20 is the question for finding a directed Eulerian cycle.
On later versions that question has been moved to exercise 4.2.28.
The questions answered on this repository are based on the seventh printing of the book (of September 2015).
