### ISSUE TITLE
1.4.14

### ISSUE THREAD

**Issue by bitflame** [reneargento/algorithms-sedgewick-wayne#87]
Update to my previous post. I realized what is happening. The left and right indices traverse the array past the previous indices of loops and look for the required value i.e. the last number to 4sum. I appreciate a comment if it is otherwise. 

Thank you so much for creating this content. Is it possible to add some comments to the solution for 1.4.14. I don't see how elementIndexLeft and Right work. I typed in your solution and compiled it, and I see the right values. I don't understand why you do: 
if (elementIndexLeft < k+1){
                        if (elementIndexRight >= k+1){
                            elementIndexLeft=k+1;
                        } else {
                            continue;
                        }
...

**Comment by reneargento** [comment]
You are right, that check is there to make sure we are only considering values we have not seen before (with indices >= `k + 1`).

**Comment by bitflame** [comment]
Thanks.

**Comment by emergencyd** [comment]
int[] array2 = {1, 2, 3, 4, -4, -5, -6, 2, 4, -1};
StdOut.println("4 sum: " + fourSum(array2));
StdOut.println("Expected: 13");

I think the expected value is 8 rather than 13...... below is my code

`public static int FourSum(int[] a) {
		int N = a.length;
		int count = 0;
		Arrays.sort(a);
		for (int i = 0; i < N; i++)
			for (int j = i + 1; j < N; j++)
				for (int k = j + 1; k < N; k++)
					if (BinarySearch.indexOf(a, -a[i]-a[j]-a[k]) > k) count++;
		return count;
	}`

**Comment by reneargento** [comment]
There are 13 pairs in that array, they are:
```
-6 -1 3 4
-6 -1 3 4
-6 1 2 3
-6 1 2 3
-5 -1 2 4
-5 -1 2 4
-5 -1 2 4
-5 -1 2 4
-5 1 2 2
-4 -1 1 4
-4 -1 1 4
-4 -1 2 3
-4 -1 2 3
``` 
Your method does not find all of them because it is ignoring the case where the 4th key exists more than once.
You can check this issue with this array: {-6, 1, 2, 3, 3}
Your method says there is 1 pair, when there is actually 2:
```
-6 1 2 3
-6 1 2 3
```
