### ISSUE TITLE
Question 1.4.23

### ISSUE THREAD

**Issue by bitflame** [reneargento/algorithms-sedgewick-wayne#89]
Hi 
The version of the book I have calls this problem Binary Search for a fraction, but you have a different name for it and it does not look like it solves the same problem. The problem statement is:  
Binary search for a fraction. Devise a method that uses a logarithmic number of
queries of the form Is the number less than x? to find a rational number p/q such that 0
< p < q < N. Hint : Two fractions with denominators less than N cannot differ by more
than 1/N 2.

**Comment by reneargento** [comment]
It seems that on newer versions of the book that question has been replaced by the "Binary search with duplicates" question.
Searching for that question title on the internet showed some discussions about how it seems unclear. That may be the reason why it was removed / replaced for another question.

**Comment by bitflame** [comment]
Thanks.
