### ISSUE TITLE
Exercise33_MemoryRequirementsOnA32BitMachine.txt

### ISSUE THREAD

**Issue by bitflame** [reneargento/algorithms-sedgewick-wayne#90]
Hi 
Where did you find the different fields for the String class please? I looked in the jdk source in src.zip and only see the following: 
private final char value[];
private int hash; // Default to 0
private static final long serialVersionUID = -6849794470754667710L;
and 
private static final ObjectStreamField[] serialPersistentFields = new ObjectStreamField[0];
I have version 8, but I am trying to make sure I can arrive at the same answer you have. 
Thanks.

**Comment by reneargento** [comment]
Chapter 1.4 of the book has a section on memory, where it explains the fields in different objects, including the String class.
Older versions of the book have a description of the String object on Java 6 and earlier, whereas newer versions of the book have a description for both String on Java 6 and earlier and String on Java 7 and later.

**Comment by bitflame** [comment]
Thank you so much. Sorry for asking something I should have seen. I did read that section, but needed to read it one more time.
If I have not said it before, this content is immensely helpful.
