### ISSUE TITLE
Exercise 1.4.9 may have wrong answer

### ISSUE THREAD

**Issue by luowyang** [reneargento/algorithms-sedgewick-wayne#93]
The current answer 2^b^logN=N^b comes from the observation of T(16) and T(1), which does not take N0 into account. To get the correct answer, you should consider T(N0) to T(16N0).
T(N0)     = T                                           = T*((2^b)^log1) = T*1^b
T(2N0)   = T*(2^b)                                 = T*((2^b)^log2) = T*2^b
T(4N0)   = T*(2^b)*(2^b)                      = T*((2^b)^log4) = T*4^b
T(8N0)   = T*(2^b)*(2^b)*(2^b)            = T*((2^b)^log8)  = T*8^b
T(16N0) = T*(2^b)*(2^b)*(2^b)*(2^b) = T*((2^b)^log16) = T*16^b
Thus we should have T(N)=T*(N/N0)^b

**Comment by reneargento** [comment]
I agree that we should take `N0` into account, but it is not clear to me how you go from 
`T*((2^b)^log1)` to `T1^b`
Can you elaborate on that part?

**Comment by luowyang** [comment]
Well, T*((2^b)^log1)=T*(2^(blog1))=T*((2^log1)^b)=T*(1^b).
Generally speaking, (2^b)^logK=2^(blogK)=(2^logK)^b=K^b for all K>0.
To avoid ambiguity, I will re-organize my answer as below:
T(N0) = T = T*((2^b)^log1) = T*(1^b)
T(2N0) = T*(2^b) = T*((2^b)^log2) = T*(2^b)
T(4N0) = T*(2^b)*(2^b) = T((2^b)^log4) = T*(4^b)
T(8N0) = T*(2^b)*(2^b)*(2^b) = T*((2^b)^log8) = T*(8^b)
T(16N0) = T*(2^b)*(2^b)*(2^b)*(2^b) = T((2^b)^log16) = T*(16^b)
Thus we should have T(N)=T*((N/N0)^b)

**Comment by reneargento** [comment]
Makes sense. I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/3a28ab20d3de5173e2bfe34a2f12380d3b43f38d
Thanks for the contribution!
