### ISSUE TITLE
A precise answer for Exercise 3.3.20

### ISSUE THREAD

**Issue by luowyang** [reneargento/algorithms-sedgewick-wayne#94]
I believe that a precise answer could be given for 3.3.20.
Current answer is the sum of i*2^i from 0 to h, which is a arithmetico-geometric sequence. Using the technique of telescoping series, the sum should be ((h-1)*2^(h+1)+2), if we substitute h with N=2^(h+1)-1, we will have the final answer: (N+1)lg(N+1)-2N
Arithmetico-geometric sequence is described in https://en.wikipedia.org/wiki/Arithmetico%E2%80%93geometric_sequence

**Comment by reneargento** [comment]
Nice catch noticing we can get a precise answer.

I followed the description from the link you sent about arithmetico-geometric sequences and got to the same result of `2 + (h - 1) * 2^(h + 1)`, but it is not clear to me why we need to replace h with `N=2^(h+1)-1` (the number of nodes) after that.

Shouldn’t `2 + (h - 1) * 2^(h + 1)` be the final answer?

**Comment by luowyang** [comment]
I have the old version of the book, and it mentions nothing about h, so I think the final answer should be something about N. But I believe both h-form and N-form are correct answers since they are equivalent.

**Comment by reneargento** [comment]
You are right, the exercise mentions the number of nodes, so it is better to have the answer as an expression based on it.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/e657c477b33d601b9d7ba9ab9ddc16b3e7f05ffc
Thanks for the contribution!
