### ISSUE TITLE
A complete answer for Exercise 3.4.24

### ISSUE THREAD

**Issue by luowyang** [reneargento/algorithms-sedgewick-wayne#95]
Given `R = 256` and `M = 255`, we shall prove that the hash of all strings with the same collection of chars are the same. In fact, we can prove the proposition that `hash(string) = (sum of chars) % 255` for all strings by induction on string length.
For any string with only one char, the proposition holds trivally.
Let `hash(str{k})` denotes the hash of a string no longer than k, `char(k)` is the k-th char. By induction assumption, we have:
`hash(str{k}) = (sum of k chars) % 255`
Then we have:
`hash(str{k+1}) = (hash(str{k}) * 256 + char(k+1)) % 255`
`= (hash(str{k}) * (255 + 1) + char(k+1)) % 255`
`= (hash(str{k}) * 255 + hash(str{k}) + char(k+1)) % 255`
`= (hash(str{k}) + char(k+1)) % 255`
`= ((sum of k chars) % 255 + char(k+1)) % 255`
`= ((sum of k chars + char(k+1)) % 255) % 255`
`= (sum of k+1 chars) % 255`
(Note that `(N*255)%255=0`, and char value is always less than 255 so char can be moved into modular expression)
Hence by induction, the proposition holds for strings of any length.
All strings with the same collection of chars must have the same sum of chars, so by the proposition they must have the same hash.

**Comment by reneargento** [comment]
Thanks for the contribution, I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/504d7d12484f9a34b880e65c6c3c9b0e44d54cd3
