### ISSUE TITLE
Excercise 4.3.12 may have wrong answer

### ISSUE THREAD

**Issue by luowyang** [reneargento/algorithms-sedgewick-wayne#96]
The last proposition is: a min-weight edge on every cycle has to belong to the MST.
This should be wrong. Consider the following counter-example：
A-B
| X |
C-D
weights:
|   A-B   | B-D | A-D | A-C | C-D | B-C |
| :------: | :------: | :------: |:------: |:------: |:------: |
| 1 | 2 | 3 | 4 | 5 | 6 |

The MST is formed by A-B, B-D and A-C with a total weight of 7 (clearly no spanning tree has less weight).
Now consider the cycle A-C-D-A, where A-D is the min-weight edge. However, A-D is NOT in MST, which contradicts the proposition.

**Comment by reneargento** [comment]
You are right, that last proposition is wrong.
I updated the exercise here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/c430a9995797d0a4c1a14518dd2bcbf2fea52a55
Thanks!
