### ISSUE TITLE
Excercise 5.4.3 may have wrong answer

### ISSUE THREAD

**Issue by luowyang** [reneargento/algorithms-sedgewick-wayne#97]
A RE with M "or" operators may match as many as 2^M strings.
Consider this 4-or pattern: (A|B)(A|B)(A|B)(A|B), every position has 2 choices, which will yield 2^4=16 strings:
AAAA
BAAA,ABAA,ABAA,AAAB
BBAA,BABA,BAAB,ABBA,ABAB,AABB
BBBA,BBAB,BABB,ABBB
BBBB
I believe it can be no more than 2^M since every "or" only yield 2 choices and there is no closure or recursion.

**Comment by reneargento** [comment]
Makes sense, I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/ee9bd55eb48c9197819e155eae92c2384da8690f
Thanks!
