### ISSUE TITLE
Exercise 5.4.11 may have wrong answer

### ISSUE THREAD

**Issue by luowyang** [reneargento/algorithms-sedgewick-wayne#98]
The answer for pattern c may be wrong
For  `(1|01)*`, the string must be a combination of k (01)'s and 1000-2k 1's, where k can be anywhere between 0 and 500. To calculate the total number of combinations, think of 1000-2k balls (1's) placed in between k separators (01's) on a line, as illustrated bellow (O is ball and | is separator)
...O|OO||OOO|O|...
There is no limitations on how to insert a separator, and the relative order of separators is irrelevant. For each separator, there are 1000-2k+1 places to insert into (including two ends), so the number of combinations will be (1000-2k+1)^k. Thus the total number of combinations will be a sum of (1000-2k+1)^k for k from 0 to 500.
I have do the calculation on my computer and it yields infinity, which is much larger than 2^500.

**Comment by luowyang** [comment]
I have cheched #59 and Mr LegendaryKokiri have regretfully made a mistake by ignoring situations where 0 could have odd indices. For example for a string length of 6:
10|11|11
01|10|11 
and many more are also possible combinations

**Comment by reneargento** [comment]
This was a tricky one, thanks for the contribution.
I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/e7d09c1b83a00b5ef1213ade365279608a5a2895
