### ISSUE TITLE
A problem about Excercise 5.4.15

### ISSUE THREAD

**Issue by luowyang** [reneargento/algorithms-sedgewick-wayne#99]
I find that the provided RE may result in false match, for example, a single star `*` will be matched but it is not a legal RE. Also a single `|`, a single `+` and other illegal REs will be matched.
Alternatively, I have a complicated RE which will only recognize legal REs with `0`, `1`, `*`, `|`, and parentheses, consecutive `*` like `**` are also allowed:
`([01\.]|\([01\.](\|[01\.])*\))(([01\.\*]|\|[01\.])|(\(|\|\()[01\.](\|[01\.])*\))*`
I cannot guarantee that it's 100% correct, because the corresponding DFA to get this RE is somewhat messy. You may also get the version where more symbols are supported, but it's too complicated for me.

**Comment by reneargento** [comment]
It may not contain all symbols but it is an improvement over the previous answer.
I updated it here: https://github.com/reneargento/algorithms-sedgewick-wayne/commit/d77576a036a427892d74298db9248f7838299e1f
Thanks!

**Comment by luowyang** [comment]
Your extraordinary work has done readers like me and others great favor, and I am truely honoured to contribute to it. Thanks for all your work and replies!

**Comment by reneargento** [comment]
I am happy it has been useful to you. Thanks for all the contributions!
